#!/usr/bin/env bash
# Generates src/Extracted.vb from frmMainPageV2.vb at the audited commit, by LINE RANGE, verbatim,
# and copies six whole app files verbatim. Nothing in the extracted text is edited.
# Usage: ./gen.sh [path-to-app-worktree]   (default /tmp/app-8232e9e)
set -euo pipefail
WT="${1:-/tmp/app-8232e9e}"
APP="$WT/DeribitOrderPlacementApp"
HERE="$(cd "$(dirname "$0")" && pwd)"
SRC="$HERE/src"
rev="$(git -C "$WT" rev-parse --short=7 HEAD)"
if [ "$rev" != "8232e9e" ]; then echo "worktree is at $rev, expected 8232e9e" >&2; exit 1; fi
mkdir -p "$SRC/app"
F="$APP/frmMainPageV2.vb"

# start:end:expected-substring-of-start-line
RANGES=(
  "1:15:Imports System.Collections.Concurrent"
  "30:134:Tooling mirrors"
  "153:215:'Public Variables"
  "217:219:'For rate limiter"
  "227:227:Private userSettings As AppUserSettings"
  "331:336:'To prevent duplicate API calls"
  "349:372:Private placedPrice As Decimal"
  "374:432:Entry-chase v2"
  "436:468:Friend Shared Function RoundTripFeePctFromMakerBps"
  "474:500:Friend Sub SetMinNetMovePct"
  "504:533:Private Sub UiInvoke"
  "546:547:Private maxSlippageATRchecked"
  "551:554:Private Sub SyncToggleInputsFromUi"
  "561:658:Public ReadOnly Property RateLimiterInstance"
  "662:664:Public Function GetTradeMode"
  "672:722:Public ReadOnly Property RateLimitManager"
  "739:777:Friend Function CaptureFeedbackSnapshot"
  "817:864:The SL stop-limit execution offset"
  "873:940:Public Async Function PlaceAutomatedOrder"
  "1293:1320:Private Async Function SendWebSocketMessageAsync"
  "1728:1749:Private Sub HandleRateLimitError"
  "1756:1896:Private Sub HandleUnhandledJsonRpcError"
  "1902:1951:Private Sub HandlePlacementResponse"
  "2217:2305:'Modify below to control how often stop loss is repositioned"
  "2308:2898:Private Async Sub HandleQuoteUpdates"
  "2901:2965:Private Async Function GetLivePositionData"
  "2968:3069:Variable to track the specific order ID"
  "3071:3678:Private Async Sub HandleOrderPositionUpdates"
  "3680:3780:Add these variables to your order placement logic"
  "3785:4187:Private Async Function ExecuteOrderAsync"
  "4190:4354:Private Async Function CancelOrderAsync"
  "4357:4658:Private Async Function SendReduceOrderAsync"
  "4661:4881:Private lastSLId As String"
  "5109:5240:Private Async Function TrailingStopLossOrderAsync"
  "5432:5591:Private Sub ApplyCloseFill"
  "5689:5974:Private Sub HandleMarginEstimationResponse"
  "6393:6424:Private Async Function SendReduceMarketOrderAsync"
)

OUT="$SRC/Extracted.vb"
{
  echo "' GENERATED by gen.sh from DeribitOrderPlacementApp/frmMainPageV2.vb at $rev - verbatim line ranges, do not edit."
} > "$OUT"
first=1
for r in "${RANGES[@]}"; do
  a="${r%%:*}"; rest="${r#*:}"; b="${rest%%:*}"; want="${rest#*:}"
  line="$(sed -n "${a}p" "$F" | sed 's/^\xEF\xBB\xBF//')"
  if [[ "$line" != *"$want"* ]]; then echo "range $a:$b start line does not contain '$want': $line" >&2; exit 1; fi
  if [ $first = 1 ]; then
    sed -n "${a},${b}p" "$F" | sed '1s/^\xEF\xBB\xBF//' >> "$OUT"
    printf '\nPartial Public Class frmMainPageV2\n' >> "$OUT"
    first=0
  else
    printf "\n' ---- frmMainPageV2.vb lines %s-%s ----\n" "$a" "$b" >> "$OUT"
    sed -n "${a},${b}p" "$F" >> "$OUT"
  fi
done
printf '\nEnd Class\n' >> "$OUT"

for f in SignalBridge.vb SessionPolicy.vb ExecutorFeedback.vb RemoteNotifier.vb AppSecrets.vb AppUserSettings.vb; do
  cp "$APP/$f" "$SRC/app/$f"
done
echo "generated $(wc -l < "$OUT") lines from $rev; copied 6 app files"
