"""Harness 6 (decision-bias tripwire), Phase A: the trader RULINGS for every population entry.

⛔ This file carries OUTCOMES. The seat writing the blind baseline must not open it (nor the
outcomes JSON) until that baseline is written and committed. Keyed by (doc, label) exactly as
in manifest.py.

OUT[(doc, label)] = (outcome, ruled_label, [(path, span), ...], ruling_date_utc, granularity, note)
  outcome: ADOPTED (ruling == recommendation) | OVERRULED (ruling differs, or the doc records the
           recommendation as DEFEATED/overruled - that record wins over a combined ruling) |
           PARTIAL (a modified or combined option, not recorded as defeated)
  spans are read at REV unless wrapped in ('at', rev, path, span)
  granularity: 'row' per-decision ruling | 'table' one ruling for a whole D-table or list |
               'doc' a doc-level approval of a spec that carried the answer
"""

from manifest import S, E, C, CS, AT  # span helpers only; no state is read from here

OUT = {}
OUT[('docs/bid-ask-spread-proposal.md', 'Q2')] = ('ADOPTED', '(1)', [('docs/bid-ask-spread-proposal.md', ('sub', 3, '**Status:**', None))], '2026-04-28', 'doc', 'doc status moved from PROPOSED - pending user approval to APPROVED; the Q-table is byte-identical first commit -> REV')
OUT[('docs/ofi-momentum-proposal.md', 'Q2')] = ('ADOPTED', '(2)', [('docs/ofi-momentum-proposal.md', ('sub', 3, '**Status:**', None))], '2026-04-29', 'doc', 'doc status moved from PROPOSED - pending user approval to APPROVED; the Q-table is byte-identical first commit -> REV')
OUT[('docs/swing-pivot-proposal.md', 'Q1')] = ('ADOPTED', '(2)', [('docs/swing-pivot-proposal.md', ('sub', 3, '**Status:**', None))], '2026-04-28', 'doc', 'doc status moved from PROPOSED - pending user approval to APPROVED; the Q-table is byte-identical first commit -> REV')
OUT[('docs/swing-pivot-proposal.md', 'Q2')] = ('ADOPTED', '(2)', [('docs/swing-pivot-proposal.md', ('sub', 3, '**Status:**', None))], '2026-04-28', 'doc', 'doc status moved from PROPOSED - pending user approval to APPROVED; the Q-table is byte-identical first commit -> REV')
OUT[('docs/vpfr-lite-v2-proposal.md', 'Q1')] = ('ADOPTED', '(1)', [('docs/vpfr-lite-v2-proposal.md', ('sub', 3, '**Status:**', None))], '2026-04-29', 'doc', 'doc status moved from PROPOSED - pending user approval to APPROVED; the Q-table is byte-identical first commit -> REV')
OUT[('docs/vpfr-lite-v2-proposal.md', 'Q2')] = ('ADOPTED', '(2)', [('docs/vpfr-lite-v2-proposal.md', ('sub', 3, '**Status:**', None))], '2026-04-29', 'doc', 'doc status moved from PROPOSED - pending user approval to APPROVED; the Q-table is byte-identical first commit -> REV')
OUT[('docs/vpfr-lite-v2-proposal.md', 'Q6')] = ('ADOPTED', '(2)', [('docs/vpfr-lite-v2-proposal.md', ('sub', 3, '**Status:**', None))], '2026-04-29', 'doc', 'doc status moved from PROPOSED - pending user approval to APPROVED; the Q-table is byte-identical first commit -> REV')
OUT[('docs/dynamic-microcvd-accel-proposal.md', 'Q1')] = ('ADOPTED', '(1)', [('docs/dynamic-microcvd-accel-proposal.md', ('sub', 3, '**Status:**', None))], '2026-04-29', 'doc', 'doc status moved from PROPOSED - pending user approval to APPROVED; the Q-table is byte-identical first commit -> REV')
OUT[('docs/dynamic-microcvd-accel-proposal.md', 'Q2')] = ('ADOPTED', '(1)', [('docs/dynamic-microcvd-accel-proposal.md', ('sub', 3, '**Status:**', None))], '2026-04-29', 'doc', 'doc status moved from PROPOSED - pending user approval to APPROVED; the Q-table is byte-identical first commit -> REV')
OUT[('docs/dynamic-microcvd-accel-proposal.md', 'Q3')] = ('ADOPTED', '(1)', [('docs/dynamic-microcvd-accel-proposal.md', ('sub', 3, '**Status:**', None))], '2026-04-29', 'doc', 'doc status moved from PROPOSED - pending user approval to APPROVED; the Q-table is byte-identical first commit -> REV')
OUT[('docs/settings-exposure-pass-proposal.md', 'Q2')] = ('ADOPTED', '(2)', [('docs/settings-exposure-pass-proposal.md', ('sub', 3, '**Status:**', None))], '2026-04-28', 'doc', 'doc status moved from PROPOSED - pending user approval to APPROVED; the Q-table is byte-identical first commit -> REV')
OUT[('docs/analysis-log-csv-expansion-proposal.md', 'Q1')] = ('ADOPTED', '(2)', [('docs/analysis-log-csv-expansion-proposal.md', ('sub', 3, '**Status:**', None))], '2026-04-29', 'doc', 'doc status moved from PROPOSED - pending user approval to APPROVED; the Q-table is byte-identical first commit -> REV')
OUT[('docs/analysis-log-csv-expansion-proposal.md', 'Q2')] = ('ADOPTED', '(1)', [('docs/analysis-log-csv-expansion-proposal.md', ('sub', 3, '**Status:**', None))], '2026-04-29', 'doc', 'doc status moved from PROPOSED - pending user approval to APPROVED; the Q-table is byte-identical first commit -> REV')
OUT[('docs/analysis-log-csv-expansion-proposal.md', 'Q3')] = ('ADOPTED', '(1)', [('docs/analysis-log-csv-expansion-proposal.md', ('sub', 3, '**Status:**', None))], '2026-04-29', 'doc', 'doc status moved from PROPOSED - pending user approval to APPROVED; the Q-table is byte-identical first commit -> REV')
OUT[('docs/analysis-log-csv-expansion-proposal.md', 'Q6')] = ('ADOPTED', '(1)', [('docs/analysis-log-csv-expansion-proposal.md', ('sub', 3, '**Status:**', None))], '2026-04-29', 'doc', 'doc status moved from PROPOSED - pending user approval to APPROVED; the Q-table is byte-identical first commit -> REV')
OUT[('docs/v17-followup-fixes-proposal.md', 'Q6')] = ('ADOPTED', '(2)', [('docs/v17-followup-fixes-proposal.md', ('sub', 3, '**Status:**', None))], '2026-04-29', 'doc', 'doc status moved from PROPOSED - pending user approval to APPROVED; the Q-table is byte-identical first commit -> REV')
OUT[('docs/v19-calibration-tuning-pass-proposal.md', 'Q3')] = ('ADOPTED', '(1)', [('docs/v19-calibration-tuning-pass-proposal.md', ('sub', 3, '**Status:**', None))], '2026-04-30', 'doc', 'doc status moved from PROPOSED - pending user approval to APPROVED; the Q-table is byte-identical first commit -> REV')
OUT[('docs/v20-rsi-roc-algorithm-fixes-proposal.md', 'Q9')] = ('ADOPTED', '(2)', [('docs/v20-rsi-roc-algorithm-fixes-proposal.md', ('sub', 3, '**Status:**', None))], '2026-04-30', 'doc', 'doc status moved from PROPOSED - pending user approval to APPROVED; the Q-table is byte-identical first commit -> REV')
OUT[('docs/api-resilience-pass-proposal.md', 'Q1')] = ('ADOPTED', '(1)', [('docs/api-resilience-pass-proposal.md', ('at', 'ea2da7b', 'docs/api-resilience-pass-proposal.md', ('sub', 3, '**Status:**', None)))], '2026-04-29', 'doc', 'doc status moved from PROPOSED - pending user approval to APPROVED; the Q-table is byte-identical first commit -> REV')
OUT[('docs/api-resilience-pass-proposal.md', 'Q2')] = ('ADOPTED', '(1)', [('docs/api-resilience-pass-proposal.md', ('at', 'ea2da7b', 'docs/api-resilience-pass-proposal.md', ('sub', 3, '**Status:**', None)))], '2026-04-29', 'doc', 'doc status moved from PROPOSED - pending user approval to APPROVED; the Q-table is byte-identical first commit -> REV')
OUT[('docs/on-close-analysis-mode-proposal.md', 'S9.1')] = ('ADOPTED', '(1)', [('docs/on-close-analysis-mode-proposal.md', ('sub', 137, 'All five confirmed', None)), ('docs/on-close-analysis-mode-proposal.md', ('sub', 139, '1. **Fire at exec-resolution close**', 'close**'))], '2026-06-25', 'table', '')
OUT[('docs/realtime-exit-guard-proposal.md', 'S9.1')] = ('ADOPTED', '(1)', [('docs/realtime-exit-guard-proposal.md', ('sub', 185, 'All six confirmed', None)), ('docs/realtime-exit-guard-proposal.md', ('sub', 187, '1. **`enabled` = true**', 'true**'))], '2026-06-24', 'table', '')
OUT[('docs/realtime-exit-guard-proposal.md', 'S9.3')] = ('ADOPTED', '(1)', [('docs/realtime-exit-guard-proposal.md', ('sub', 185, 'All six confirmed', None)), ('docs/realtime-exit-guard-proposal.md', ('sub', 189, '3. **`debounce_evals` = 2**', '= 2**'))], '2026-06-24', 'table', '')
OUT[('docs/realtime-exit-guard-proposal.md', 'S9.5')] = ('ADOPTED', '(1)', [('docs/realtime-exit-guard-proposal.md', ('sub', 185, 'All six confirmed', None)), ('docs/realtime-exit-guard-proposal.md', ('sub', 191, '5. **Single-adverse Warn state surfaced**', 'surfaced**'))], '2026-06-24', 'table', '')
OUT[('docs/realtime-exit-guard-proposal.md', 'S9.6')] = ('ADOPTED', '(1)', [('docs/realtime-exit-guard-proposal.md', ('sub', 185, 'All six confirmed', None)), ('docs/realtime-exit-guard-proposal.md', ('sub', 192, '6. **Latch = auto-clear**', 'auto-clear**'))], '2026-06-24', 'table', '')
OUT[('docs/live-microstructure-strip-proposal.md', 'S9.2')] = ('ADOPTED', '(1)', [('docs/live-microstructure-strip-proposal.md', ('sub', 135, '## 9. Settled decisions', None)), ('docs/live-microstructure-strip-proposal.md', ('sub', 140, '2. **Placement**', 'header**'))], '2026-06-25', 'table', '')
OUT[('docs/live-microstructure-strip-proposal.md', 'S9.4')] = ('OVERRULED', '(2)', [('docs/live-microstructure-strip-proposal.md', ('sub', 135, '## 9. Settled decisions', None)), ('docs/live-microstructure-strip-proposal.md', ('sub', 142, '4. **Nearest levels = BOTH above & below**', 'implementation.'))], '2026-06-25', 'row', '')
OUT[('docs/live-microstructure-strip-proposal.md', 'S9.5')] = ('ADOPTED', '(1)', [('docs/live-microstructure-strip-proposal.md', ('sub', 135, '## 9. Settled decisions', None)), ('docs/live-microstructure-strip-proposal.md', ('sub', 143, '5. **Tape speed = both**', '`$/s`.'))], '2026-06-25', 'table', '')
OUT[('docs/auto-tweaker-session-resolution-filter-proposal.md', 'S5.2')] = ('ADOPTED', '(1)', [('docs/auto-tweaker-session-resolution-filter-proposal.md', ('sub', 114, '**Trader sign-off 2026-06-17', 'off-surface'))], '2026-06-17', 'row', '')
OUT[('docs/offline-analysis-report-audit-proposal.md', 'D1')] = ('ADOPTED', '(1)', [('docs/offline-analysis-report-audit-proposal.md', ('sub', 194, '## 5. Design decisions — ALL APPROVED', None)), ('docs/offline-analysis-report-audit-proposal.md', ('sub', 196, '- **D1 — Segmentation granularity: `(session × resolution)`** ✓', None))], '2026-06-18', 'row', '')
OUT[('docs/offline-analysis-report-audit-proposal.md', 'D3')] = ('PARTIAL', '(1)+trader refinement', [('docs/offline-analysis-report-audit-proposal.md', ('sub', 194, '## 5. Design decisions — ALL APPROVED', None)), ('docs/offline-analysis-report-audit-proposal.md', ('sub', 198, '- **D3 — Pooled view: DROP the single pooled matrix** ✓', '(trader refinement)'))], '2026-06-18', 'row', 'the recommended drop is kept and REPLACED by a tier-major per-session expansion the trader added; neither offered option alone')
OUT[('docs/time-averaged-ofi-proposal.md', 'S10.1')] = ('ADOPTED', '(a)', [('docs/time-averaged-ofi-proposal.md', ('sub', 134, 'All five confirmed **as recommended**', 'below.'))], '2026-06-29', 'table', '')
OUT[('docs/time-averaged-ofi-proposal.md', 'S10.2')] = ('ADOPTED', '(1)', [('docs/time-averaged-ofi-proposal.md', ('sub', 134, 'All five confirmed **as recommended**', 'below.'))], '2026-06-29', 'table', '')
OUT[('docs/time-averaged-ofi-proposal.md', 'S10.3')] = ('ADOPTED', '(1)', [('docs/time-averaged-ofi-proposal.md', ('sub', 134, 'All five confirmed **as recommended**', 'below.'))], '2026-06-29', 'table', '')
OUT[('docs/time-averaged-ofi-proposal.md', 'S10.4')] = ('ADOPTED', '(1)', [('docs/time-averaged-ofi-proposal.md', ('sub', 134, 'All five confirmed **as recommended**', 'below.'))], '2026-06-29', 'table', '')
OUT[('docs/time-averaged-ofi-proposal.md', 'S10.5')] = ('ADOPTED', '(1)', [('docs/time-averaged-ofi-proposal.md', ('sub', 134, 'All five confirmed **as recommended**', 'below.'))], '2026-06-29', 'table', '')
OUT[('docs/dev-workflow-automation-proposal.md', 'B')] = ('PARTIAL', '(1)+(3)', [('docs/dev-workflow-automation-proposal.md', ('sub', 8, '**Decisions taken (trader, 2026-06-30):**', None))], '2026-06-30', 'row', 'ruled Stop hook advisory-only: the recommended Stop event combined with the advisory-only option; the recommendation left advisory-or-blocking to the trader')
OUT[('docs/dev-workflow-automation-proposal.md', 'C')] = ('ADOPTED', '(1)', [('docs/dev-workflow-automation-proposal.md', ('sub', 8, '**Decisions taken (trader, 2026-06-30):**', None))], '2026-06-30', 'row', '')
OUT[('docs/dev-workflow-automation-proposal.md', 'D')] = ('ADOPTED', '(1)', [('docs/dev-workflow-automation-proposal.md', ('sub', 8, '**Decisions taken (trader, 2026-06-30):**', None))], '2026-06-30', 'row', '')
OUT[('docs/dev-workflow-automation-proposal.md', 'E')] = ('OVERRULED', 'neither (not built)', [('docs/dev-workflow-automation-proposal.md', ('sub', 8, '**Decisions taken (trader, 2026-06-30):**', None))], '2026-06-30', 'row', 'ruled: coordinator-review/implementer subagents not built (budget) - an option not offered')
OUT[('docs/dev-workflow-automation-proposal.md', 'F')] = ('ADOPTED', '(1)', [('docs/dev-workflow-automation-proposal.md', ('sub', 8, '**Decisions taken (trader, 2026-06-30):**', None))], '2026-06-30', 'row', '')
OUT[('docs/audit-fixes-2026-07-02-proposal.md', 'D1')] = ('ADOPTED', '(1)', [('docs/audit-fixes-2026-07-02-proposal.md', ('sub', 89, '## 7. Sign-off decisions — ✅ ALL APPROVED AS RECOMMENDED', None)), ('docs/audit-fixes-2026-07-02-proposal.md', ('cellsub', 93, 3, '✅ **Remove**', '**Remove**'))], '2026-07-02', 'table', '')
OUT[('docs/audit-fixes-2026-07-02-proposal.md', 'D2')] = ('ADOPTED', '(1)', [('docs/audit-fixes-2026-07-02-proposal.md', ('sub', 89, '## 7. Sign-off decisions — ✅ ALL APPROVED AS RECOMMENDED', None))], '2026-07-02', 'table', '')
OUT[('docs/audit-fixes-2026-07-02-proposal.md', 'D3')] = ('ADOPTED', '(1)', [('docs/audit-fixes-2026-07-02-proposal.md', ('sub', 89, '## 7. Sign-off decisions — ✅ ALL APPROVED AS RECOMMENDED', None))], '2026-07-02', 'table', '')
OUT[('docs/signal-health-retune-proposal.md', 'D2')] = ('ADOPTED', '(1)', [('docs/signal-health-retune-proposal.md', ('sub', 77, '## 6. Sign-off decisions — ALL TICKED by the trader 2026-07-03', None))], '2026-07-03', 'table', '')
OUT[('docs/placed-geometry-structural-first-proposal.md', 'D3')] = ('ADOPTED', '(a)', [('docs/placed-geometry-structural-first-proposal.md', ('sub', 96, '## 9. Sign-off decisions — ALL TICKED by the trader 2026-07-03 (D3 = clamp)', None))], '2026-07-03', 'row', '')
OUT[('docs/placed-geometry-derivation-2026-07-06.md', 'DG2')] = ('ADOPTED', '(1)', [('docs/placed-geometry-derivation-2026-07-06.md', ('sub', 3, '**Status:** APPROVED — trader ticked DG1–DG5, 2026-07-06, all recommended values', 'all recommended values'))], '2026-07-06', 'table', '')
OUT[('docs/placed-geometry-derivation-2026-07-06.md', 'DG3')] = ('ADOPTED', '(2)', [('docs/placed-geometry-derivation-2026-07-06.md', ('sub', 3, '**Status:** APPROVED — trader ticked DG1–DG5, 2026-07-06, all recommended values', 'all recommended values'))], '2026-07-06', 'table', '')
OUT[('docs/funding-momentum-time-anchored-window-proposal.md', 'D4')] = ('ADOPTED', '(2)', [('docs/funding-momentum-time-anchored-window-proposal.md', ('sub', 86, '## 8. Sign-off decisions — ALL TICKED by the trader 2026-07-07 (as recommended)', None))], '2026-07-07', 'table', '')
OUT[('docs/d6-eval-placed-stop-migration-proposal.md', 'D1')] = ('ADOPTED', '(1)', [('docs/d6-eval-placed-stop-migration-proposal.md', S(3, '**APPROVED 2026-07-14', 'as recommended).**'))], '2026-07-14', 'row', '')
OUT[('docs/aggressor-velocity-s52-derivation-2026-07-13.md', 'S1')] = ('ADOPTED', '(1)', [('docs/aggressor-velocity-s52-derivation-2026-07-13.md', S(56, '## 7. S-table — **ALL TICKED 2026-07-14: S1 = 4.5**', 'as recommended.'))], '2026-07-14', 'row', 'ticked after the trader asked for a plain-terms explanation of the burst ratio')
OUT[('docs/aggressor-velocity-s52-derivation-2026-07-13.md', 'S2')] = ('ADOPTED', '(a)', [('docs/aggressor-velocity-s52-derivation-2026-07-13.md', S(56, '## 7. S-table — **ALL TICKED 2026-07-14', 'S2 = option (a)'))], '2026-07-14', 'row', '')
OUT[('docs/session-policy-gate-proposal.md', 'P1')] = ('ADOPTED', '(1)', [('docs/session-policy-gate-proposal.md', S(3, '**APPROVED — P1–P5 ALL TICKED 2026-07-18 (as recommended).', '(as recommended).'))], '2026-07-18', 'table', '')
OUT[('docs/eval-no-data-outcome-proposal.md', 'N4')] = ('ADOPTED', '(1)', [('docs/eval-no-data-outcome-proposal.md', CS(28, 3, '✅ **TICKED 2026-07-21: migrate to placed geometry**')), ('docs/eval-no-data-outcome-proposal.md', S(31, '**N1–N5 ALL TICKED 2026-07-21'))], '2026-07-21', 'row', '')
OUT[('docs/geometry-arbitration-modes-proposal.md', 'G2')] = ('ADOPTED', '(1)', [('docs/geometry-arbitration-modes-proposal.md', S(3, '**Status:** APPROVED — **G1–G6 ALL TICKED', 'BUILD-AUTHORIZED**'))], '2026-07-21', 'table', 'the row itself was never rewritten; ticked = follow as recommended, the trader definition recorded in absorption-mechanism-revision-proposal.md')
OUT[('docs/liq-cascade-level-alerts-proposal.md', 'H1')] = ('ADOPTED', '(1)', [('docs/liq-cascade-level-alerts-proposal.md', S(3, '**SHIPPED as v59 · 2026-07-22** (H1–H5 all ticked', 'as approved)'))], '2026-07-22', 'table', '')
OUT[('docs/absorption-geometry-rescale-proposal.md', 'V2')] = ('ADOPTED', '(1)', [('docs/absorption-geometry-rescale-spec-back.md', S(9, 'V1–V4 all ticked', 'V1–V4 all ticked'))], '2026-07-23', 'table', '')
OUT[('docs/aggr-vel-s52-london-derivation-2026-07-23.md', 'S1')] = ('ADOPTED', '(1)', [('-', ('commitmsg', '631a3f5', 'calib(v60): LONDON aggressor-velocity burst arming', '(S1-S5 ticked)'))], '2026-07-22', 'table', 'the ruling is recorded only in the v60 commit message, not in any doc at REV')
OUT[('docs/in-app-trade-store-capture-proposal.md', 'D1')] = ('OVERRULED', '(2)', [('docs/in-app-trade-store-capture-proposal.md', CS(135, 3, '**AWS ONLY — ruled against the recommendation', 'the one I offered.**'))], '2026-07-31', 'row', '')
for _q in ('D1', 'D2', 'D3', 'D4', 'D5', 'D6'):
    OUT[('docs/settings-local-overlay-proposal.md', _q)] = ('ADOPTED', '(a)', [('docs/settings-local-overlay-proposal.md', S(4, 'Previously: ✅ APPROVED 2026-08-01 — D1–D6 ALL TICKED all-as-recommended (trader)', '(trader)'))], '2026-08-01', 'table', '')
_tc = [('docs/trade-store-coverage-report-proposal.md', S(245, '> ✅ **TICKED 2026-08-03 (trader), all as recommended:', 'all as recommended:'))]
for _q in ('D1', 'D2', 'D3', 'D7', 'D6'):
    OUT[('docs/trade-store-coverage-report-proposal.md', _q)] = ('ADOPTED', '(a)', _tc, '2026-08-03', 'table', '')
OUT[('docs/trade-store-coverage-report-proposal.md', 'D4')] = ('ADOPTED', '(1)', [('docs/trade-store-coverage-report-proposal.md', S(245, '> ✅ **TICKED 2026-08-03 (trader), all as recommended:', 'D4 300,000 ms'))], '2026-08-03', 'table', '')
OUT[('docs/asia-burst-threshold-derivation-2026-08-01.md', 'D3-1')] = ('ADOPTED', '(7)', [('docs/asia-burst-threshold-derivation-2026-08-01.md', S(79, '## 5. D-table — **TICKED 2026-08-02 (trader).')), ('docs/asia-burst-threshold-derivation-2026-08-01.md', CS(85, 3, '**`sessions.ASIA.burst_ratio_threshold` = 5.5**, as recommended'))], '2026-08-02', 'row', '')
OUT[('docs/ttm-flat-threshold-rederivation-2026-08-02.md', 'D1-d')] = ('ADOPTED', '(b)', [('docs/ttm-flat-threshold-rederivation-2026-08-02.md', CS(89, 4, '✅ **RULED 2026-08-02 (trader): (b) PARK.**', 'PARK.**'))], '2026-08-02', 'row', '')
OUT[('docs/ttm-flat-threshold-rederivation-2026-08-02.md', 'D1-a')] = ('ADOPTED', '(a)', [('docs/ttm-flat-threshold-rederivation-2026-08-02.md', CS(89, 4, '**D1-a/b/c are answered in principle but not scheduled**', 'ATR-relative'))], '2026-08-02', 'row', 'answered in principle within the D1-d park ruling')
for _q, _r in (('D1', '(3)'), ('D5', '(1)'), ('D6', '(2)')):
    OUT[('docs/trade-store-trade-identity-proposal.md', _q)] = ('ADOPTED', _r, [('docs/trade-store-trade-identity-proposal.md', S(149, '## 7. D-table — ✅ **ALL TICKED 2026-08-08 (trader), every row as recommended**'))], '2026-08-08', 'table', '')
for _q, _r in (('D-1', '(a)'), ('D-2', '(1)'), ('D-3', '(a)'), ('D-4', '(a)'), ('D-5', '(a)'), ('D-6', '(2)'), ('D-7', '(1)')):
    OUT[('docs/trade-store-write-guard-identity-proposal.md', _q)] = ('ADOPTED', _r, [('docs/trade-store-write-guard-identity-proposal.md', S(168, '## 4. D-table — ✅ RULED 2026-08-11, trader-directed')), ('docs/trade-store-write-guard-identity-proposal.md', S(170, '> **All seven rows ruled AS RECOMMENDED.', 'no row was deferred.**'))], '2026-08-11', 'table', '')
OUT[('docs/absorption-d6-spec-back.md', 'D-6a')] = ('ADOPTED', '(a)', [('docs/absorption-mechanism-revision-proposal.md', S(310, '> | **D-6a** |', 'measure-tight.')), ('-', ('commitmsg', 'a2a51e3', 'Trader ruled both as recommended', 'section 2.'))], '2026-09-01', 'row', '')
OUT[('docs/absorption-d6-spec-back.md', 'D-6b')] = ('ADOPTED', '(a)', [('docs/absorption-mechanism-revision-proposal.md', S(311, '> | **D-6b** |', 'CLAIM WITHDRAWN.**')), ('-', ('commitmsg', 'a2a51e3', 'Trader ruled both as recommended', 'section 2.'))], '2026-09-01', 'row', '')
OUT[('docs/d6d-episode-continuity-spec.md', 'D-6d.1')] = ('OVERRULED', '(c) sidecar AND one CSV column', [('docs/d6d-episode-continuity-spec.md', CS(248, 2, '✅✅ **RULED (c) BY THE TRADER, 2026-09-11 (UTC)', '(`AbsorptionShadowAggrUsd`).**')), ('docs/d6d-episode-continuity-spec.md', CS(248, 2, '**THIRD DEFEAT OF A CHEAPER READ IN ONE SESSION', 'IN ONE SESSION'))], '2026-09-11', 'row', 'a combined option, but the doc records the recommendation as defeated, so OVERRULED takes precedence over PARTIAL')
OUT[('docs/d6d-episode-continuity-spec.md', 'D-6d.2')] = ('ADOPTED', '(a)', [('docs/d6d-episode-continuity-spec.md', CS(250, 2, '⭐ **`D-6d.2` is SUBSUMED by this ruling', 'asked.**'))], '2026-09-11', 'row', 'subsumed by the D-6d.3 ruling, which the doc says delivers what (a) asked')
OUT[('docs/d6d-episode-continuity-spec.md', 'D-6d.3')] = ('ADOPTED', '(c)', [('docs/d6d-episode-continuity-spec.md', CS(250, 2, '✅✅ **RULED (c) BY THE TRADER, 2026-09-11 (UTC)', 'FOLLOWS THE READ.**'))], '2026-09-11', 'row', 'ADOPTED against the LAST pre-ruling read (c); the first read (b) was withdrawn by the seat on measurement after a trader question (seat-handover-2026-09-14.md bias register)')
OUT[('docs/thin-trade-window-skip-gate-proposal.md', 'D-1')] = ('ADOPTED', '(1)', [('docs/thin-trade-window-skip-gate-spec-back.md', S(4, 'D1–D5 all ticked as recommended, trader-directed.', 'trader-directed.'))], '2026-08-20', 'table', '')
OUT[('docs/collector-ops-tooling-proposal.md', 'D-7')] = ('OVERRULED', '(2)', [('docs/collector-ops-tooling-proposal.md', CS(160, 3, '✅ **TICKED 2026-08-21 — PRODUCTION ONLY.**', 'PRODUCTION ONLY.**'))], '2026-08-20', 'row', 'the box date label reads 2026-08-21 local; commit 462ac12 is 2026-08-20T17:36Z')
OUT[('docs/collector-ops-tooling-proposal.md', 'D-9')] = ('ADOPTED', '(2)', [('docs/collector-ops-tooling-proposal.md', CS(162, 3, '✅ **TICKED 2026-08-21 — ON DEMAND ONLY.**', 'ON DEMAND ONLY.**'))], '2026-08-20', 'row', 'the box date label reads 2026-08-21 local; commit 462ac12 is 2026-08-20T17:36Z')
_te = 'docs/coverage-trailing-edge-f1-proposal.md'
_first = [(_te, S(12, '**Ruling history, in one line:** first tick', '· D-6 (a)**'))]
_second = [(_te, S(12, 'second tick **D-3 (c) · D-6 (c) · D-5.1…D-5.5 all (a)**', 'all (a)**'))]
OUT[(_te, 'D-1')] = ('ADOPTED', '(a)', _first, '2026-08-25', 'row', '')
OUT[(_te, 'D-2')] = ('ADOPTED', '(a)', _first, '2026-08-25', 'row', '')
OUT[(_te, 'D-3')] = ('ADOPTED', '(a)', _first, '2026-08-25', 'row', 'first tick followed the read; the seat later re-opened it with a new option, recorded as D-3r')
OUT[(_te, 'D-4')] = ('OVERRULED', '(c)', _first, '2026-08-25', 'row', 'the read was "(b) at minimum; (c) is correct but larger"; taken as recommending (b). Trader direction recorded with the tick: do this properly instead of the minimum')
OUT[(_te, 'D-5')] = ('OVERRULED', '(c)', _first, '2026-08-25', 'row', '')
OUT[(_te, 'D-6')] = ('ADOPTED', '(a)', _first, '2026-08-25', 'row', 'first tick followed the read; the seat later re-opened it with a new option, recorded as D-6r')
for _q in ('D-5.1', 'D-5.2', 'D-5.3', 'D-5.4', 'D-5.5'):
    OUT[(_te, _q)] = ('ADOPTED', '(a)', _second + [(_te, S(160, '### 4a.2 ✅ D-5(c)', 'ALL RULED as recommended, 2026-08-25'))], '2026-08-25', 'table', '')
OUT[(_te, 'D-6r')] = ('ADOPTED', '(c)', _second, '2026-08-25', 'row', '')
OUT[(_te, 'D-3r')] = ('ADOPTED', '(c)', _second, '2026-08-25', 'row', '')
_ar = 'docs/trader-tick-queue-archive.md'
OUT[(_ar, 'A54a-scope')] = ('OVERRULED', '(d) reflection guard + scoped (b) as dead-code removal', [(_ar, CS(373, 2, '✅ **RULED 2026-08-11 — option (d) + scoped (b)**')), (_ar, CS(373, 3, "the orchestrator's recommendation was DEFEATED on evidence.**", 'on evidence.**'))], '2026-08-11', 'row', 'combined ruling, but the doc records the recommendation as DEFEATED, so OVERRULED takes precedence over PARTIAL')
OUT[(_ar, 'seeded-session-buckets')] = ('OVERRULED', '(1)', [(_ar, CS(375, 2, '✅ **RULED 2026-08-11 — DO NOT empty the seed. Guard it via (d)**')), (_ar, CS(375, 3, "the orchestrator's recommendation was DEFEATED on a factual error.**", 'factual error.**'))], '2026-08-11', 'row', '')
_aj = 'docs/a54a-json-poco-drift-guard-spec.md'
_four = [(_aj, S(254, "**Four as recommended; D-3 ruled against the spec's abstention.**"))]
OUT[(_aj, 'D-1')] = ('ADOPTED', '(a)', _four, '2026-09-03', 'table', 'doc says 2026-09-04; tick commit d3a054f is 2026-09-03T19:17Z')
OUT[(_aj, 'D-4')] = ('ADOPTED', '(1)', _four + [(_aj, CS(261, 3, '✅ **FAIL, as recommended**'))], '2026-09-03', 'table', 'doc says 2026-09-04; tick commit d3a054f is 2026-09-03T19:17Z')
OUT[(_aj, 'D-5')] = ('ADOPTED', '(2)', _four + [(_aj, CS(262, 3, '✅ **Its own session, second, as recommended.**'))], '2026-09-03', 'table', 'doc says 2026-09-04; tick commit d3a054f is 2026-09-03T19:17Z')
OUT[('docs/a54a-r2-r3-followup-spec.md', 'D-R3')] = ('ADOPTED', '(i)', [('docs/a54a-r2-r3-followup-spec.md', CS(159, 3, '✅ **(i) — SEED THE NULLABLES, as recommended.**'))], '2026-09-04', 'row', '')
OUT[('docs/a54a-session2-step1-measurement-2026-09-05.md', 'S2-1')] = ('OVERRULED', '(B)', [('docs/a54a-session2-step1-measurement-2026-09-05.md', S(281, "## 8. ⛔ §7.3's recommendation is FLIPPED to (B) — trader-directed 2026-09-05"))], '2026-09-04', 'row', 'doc says 2026-09-05; ruling commit f9f8fdf is 2026-09-04T18:55Z')
for _q2, _r in (('D-1', '(a)'), ('D-2', '(a)'), ('D-3', '(b)'), ('D-4', '(a)'), ('D-5', '(a)')):
    OUT[('docs/s2-2-calcspread-split-proposal.md', _q2)] = ('ADOPTED', _r, [('docs/s2-2-calcspread-split-proposal.md', S(162, '## 4. D-table — ✅ TICKED IN FULL 2026-09-06, every row as recommended.'))], '2026-09-06', 'table', '')
_ar = 'docs/trader-tick-queue-archive.md'
OUT[(_ar, 'pooled-minute-key-dedup')] = ('OVERRULED', '(1)', [(_ar, CS(39, 2, '✅ **DONE 2026-08-11 — and the ruling REVERSED the recommendation**')), (_ar, CS(39, 3, '⚠ **KEEP the minute key; do NOT change it for the Kelly/W6-4 freeze.**'))], '2026-08-11', 'row', '')
OUT[(_ar, 'E5-absorption-path')] = ('ADOPTED', '(B)', [(_ar, CS(370, 2, '✅ **TICKED 2026-08-12 — PATH B**')), (_ar, CS(370, 3, '✅ **DECIDED, as the coordinator recommended.**'))], '2026-08-12', 'row', '')
OUT[(_ar, 'WD-SEMANTICS')] = ('OVERRULED', '(c)', [('docs/wd-semantics-unparsed-counter-spec.md', S(15, '✅✅ **RULED (c) 2026-09-09 (UTC), trader.', 'trader.')), ('docs/wd-semantics-unparsed-counter-spec.md', S(57, '⭐ **Why (c) and not the cheaper (b).**'))], '2026-09-09', 'row', '')
_s4 = 'docs/s4-eval-cache-identity-proposal.md'
OUT[(_s4, 'D-1')] = ('OVERRULED', '(b)', [(_s4, CS(116, 3, '✅ **(b) — THEY LAND TOGETHER.**')), (_s4, CS(116, 4, '⚠ **The orchestrator read (a) and was DEFEATED**'))], '2026-09-08', 'row', '')
OUT[(_s4, 'D-2')] = ('OVERRULED', '(b)', [(_s4, CS(117, 3, '✅ **(b) — the true `(InstanceId, SignalId)` PAIR, with the v6 → v7 migration, NOW**')), (_s4, CS(117, 4, '⚠ **The orchestrator read (a)-now-(b)-later and was DEFEATED**'))], '2026-09-08', 'row', '')
OUT[(_s4, 'D-3')] = ('ADOPTED', '(a)', [(_s4, CS(118, 3, '✅ **(a) — null identity, FALL BACK TO `Timestamp` for those rows only**')), (_s4, CS(118, 4, "⭐ **The orchestrator's read, upheld.**"))], '2026-09-08', 'row', '')
OUT[('docs/item6-wstradeprobe-s1-recheck-2026-09-07.md', 'S-1')] = ('ADOPTED', '(a)', [(_ar, CS(481, 1, '✅ **`S-1` — THE DECISION IS TAKEN. RULED 2026-09-07 (trader): (a) split `TradeRecord` into `Core/`, AS THE DIRECTION, **NOT NOW**.'))], '2026-09-07', 'row', 'the read was (a) as the direction, not now; ruled the same')
OUT[('docs/absorption-d2-stage1-rotation-build-spec.md', 'RD-1')] = ('ADOPTED', '(b)', [('docs/absorption-d2-stage1-rotation-build-spec.md', CS(234, 2, '✅ **RULED (b) by the trader, 2026-09-13 (UTC), as recommended**'))], '2026-09-13', 'row', '')
_k = 'docs/kelly-w6-4-spec-back.md'
OUT[(_k, 'D-1')] = ('PARTIAL', '(a) with a scope change', [(_k, S(28, '> ### ✅ `D-1` → **(a) ADD THE FLAG**', 'did not propose.'))], '2026-09-09', 'row', 'the recommended option with one scope change the packet did not propose')
OUT[(_k, 'D-3')] = ('OVERRULED', '(c)', [(_k, S(30, '> ### ✅ `D-3` → **(c) DO NOTHING**'))], '2026-09-09', 'row', '')
OUT[('docs/doc-status-sweep-and-queue-archive-spec.md', 'D-1')] = ('ADOPTED', '(a)', [('docs/doc-status-sweep-and-queue-archive-spec.md', S(190, '> ## ✅✅ `D-1` RULED **(a)** — 2026-09-09 (UTC), trader.'))], '2026-09-09', 'row', '')
_c = 'docs/coverage-report-cluster-spec.md'
OUT[(_c, 'D-4')] = ('ADOPTED', '(b)', [(_c, CS(137, 4, '✅✅ **TICKED (b) 2026-09-11 (UTC), trader — as recommended.**'))], '2026-09-11', 'row', '')
OUT[(_c, 'D-6')] = ('ADOPTED', '(b)', [(_c, CS(138, 4, '✅✅ **TICKED (b) 2026-09-11 (UTC)'))], '2026-09-11', 'row', '')
OUT[('docs/venue-status-instrument-spec.md', 'D-1')] = ('OVERRULED', '(d) a new option', [('docs/venue-status-instrument-spec.md', S(97, 'RULED (d) 2026-09-11 (UTC), trader', 'originally offered.'))], '2026-09-11', 'row', '')
_g = 'docs/gap-repair-same-ms-page-skip-spec.md'
OUT[(_g, 'GR-1')] = ('OVERRULED', '(d) a new option', [(_g, CS(158, 5, '✅ **(d) NEW — trader-ruled 2026-09-14 (UTC).**'))], '2026-09-14', 'row', '')
OUT[(_g, 'GR-2')] = ('ADOPTED', '(b)', [(_g, CS(159, 5, '✅ **(b) — ruled 2026-09-14 (UTC).**'))], '2026-09-14', 'row', 'the seat had taken (b) under the auto-proceed ruling; the trader then ruled it')
OUT[(_g, 'GR-4')] = ('OVERRULED', '(b)', [(_g, CS(161, 5, '✅ **(b) — ruled 2026-09-14 (UTC).**'))], '2026-09-14', 'row', 'the read was (a) now plus a queue row for (b)')
OUT[(_g, 'GR-5')] = ('OVERRULED', '(b)', [(_g, CS(162, 5, '✅ **(b) — ruled 2026-09-14 (UTC).**'))], '2026-09-14', 'row', '')
_gs = 'docs/gap-repair-scan-failure-spec.md'
OUT[('docs/trade-store-duplicate-rows-read-2026-09-15.md', 'DUP-1')] = ('OVERRULED', '(a)', [(_gs, S(3, '> ✅ **RULED 2026-09-15 (UTC), trader via the orchestrator', 'the S2 deploy WAITS for it.'))], '2026-09-15', 'row', '')
OUT[('docs/trade-store-duplicate-rows-read-2026-09-15.md', 'DUP-2')] = ('ADOPTED', '(iii)', [(_gs, S(3, '> ✅ **RULED 2026-09-15 (UTC), trader via the orchestrator', '`DUP-2` = both directions'))], '2026-09-15', 'row', '')
OUT[('docs/venue-check-build-spec-back.md', 'R-2')] = ('ADOPTED', '(a)', [('docs/venue-check-build-summary.md', S(7, '✅ **Rulings, 2026-09-14 (UTC):**', 'were trader-'))], '2026-09-14', 'row', '')
OUT[('docs/venue-check-build-spec-back.md', 'R-3')] = ('ADOPTED', '(a)', [('docs/venue-check-build-summary.md', S(7, '✅ **Rulings, 2026-09-14 (UTC):**', 'were trader-'))], '2026-09-14', 'row', '')
OUT[('docs/venue-check-schedule-plan.md', 'D-2')] = ('OVERRULED', '(c)', [('docs/venue-check-schedule-plan.md', S(5, '> ⭐⭐ **SUPERSEDED IN PART — TRADER RULING 2026-09-14 (UTC): OPTION A.**', 'against the verified local copy-back.'))], '2026-09-14', 'row', 'option A = run on the dev machine after each fetch, the plan option (c); the orchestrator review had agreed (a)')
_b = 'docs/medium-tier-bug-hunt-spec-back.md'
OUT[(_b, 'D-2')] = ('ADOPTED', '(a)', [(_b, S(161, '**RULED (trader), 2026-09-16 UTC: (a).**'))], '2026-09-16', 'row', '')
OUT[(_b, 'D-5')] = ('PARTIAL', '(a) for M and T, plus (b) for MT', [(_b, S(327, '**RULED (trader), 2026-09-16 UTC:** book `M` to the maker', '`MT` to both sides.'))], '2026-09-16', 'row', 'combines (a) for M/T with (b) for MT; the read had no read on MT')
_q = 'docs/trader-tick-queue.md'
OUT[(_b, 'D-8')] = ('OVERRULED', '(b)', [(_q, S(168, '✅ **RULED 2026-09-16 (trader), as the orchestrator recommended:**', 'separate labelled column'))], '2026-09-16', 'row', 'the recorded pre-ruling read is the implementer (a); the orchestrator recommendation (b) that the trader followed is not recorded before the ruling')
OUT[(_b, 'D-9')] = ('ADOPTED', '(b)', [(_q, S(168, '✅ **RULED 2026-09-16 (trader), as the orchestrator recommended:**', 'actually did'))], '2026-09-16', 'row', '')
_m = 'docs/medium-tier-diagnosis-spec-back.md'
OUT[(_m, 'Q-1')] = ('ADOPTED', '(d)', [(_m, S(218, '## Trader rulings (2026-09-18 UTC)')), (_m, S(224, '| `Q-1` (the tier ladder) | **(d) first:**', 'on that result |'))], '2026-09-17', 'row', 'heading dates 2026-09-18; the ruling commit 3d3925d is 2026-09-17T16:38Z')
OUT[(_m, 'Q-2')] = ('ADOPTED', '(c)', [(_m, S(226, '| `Q-2` / `F-3` (the NY VPFR vote) | **Retest after the POC-gate fix and the liquidation fix ship**'))], '2026-09-17', 'row', 'heading dates 2026-09-18; the ruling commit 3d3925d is 2026-09-17T16:38Z')
_e = 'docs/engine-fix-build-spec-2026-09-21.md'
_ef = [(_e, S(408, '✅ **The trader ruled `EF-1` to `EF-4` on 2026-09-21 (UTC), all as recommended.**'))]
OUT[(_e, 'EF-1')] = ('ADOPTED', '(a)', _ef, '2026-09-21', 'table', '')
OUT[(_e, 'EF-2')] = ('ADOPTED', '(a)', _ef, '2026-09-21', 'table', '')
OUT[(_e, 'EF-3')] = ('ADOPTED', '(b)', _ef, '2026-09-21', 'table', '')
OUT[(_e, 'EF-4')] = ('ADOPTED', '(a)', _ef, '2026-09-21', 'table', '')
