"""Harness 6 (decision-bias tripwire), Phase A: the trader RULINGS for every population entry.

⛔ This file carries OUTCOMES. The seat writing the blind baseline must not open it (nor the
outcomes JSON) until that baseline is written and committed. Keyed by (doc, label) exactly as
in manifest.py.

OUT[(doc, label)] = (outcome, ruled_label, [(path, span), ...], ruling_date_utc, granularity, note)
  outcome: ADOPTED (ruling == recommendation) | OVERRULED (ruling differs, or the doc records the
           recommendation as DEFEATED/overruled - that record wins over a combined ruling) |
           PARTIAL (a modified or combined option, not recorded as defeated)
  spans are read at REV unless wrapped in ('at', rev, path, span)
  granularity: 'row' per-decision ruling | 'table' one ruling for a whole D-table or list |
               'doc' a doc-level approval of a spec that carried the answer
"""

OUT = {}
OUT[('docs/bid-ask-spread-proposal.md', 'Q2')] = ('ADOPTED', '(1)', [('docs/bid-ask-spread-proposal.md', ('sub', 3, '**Status:**', None))], '2026-04-28', 'doc', 'doc status moved from PROPOSED - pending user approval to APPROVED; the Q-table is byte-identical first commit -> REV')
OUT[('docs/ofi-momentum-proposal.md', 'Q2')] = ('ADOPTED', '(2)', [('docs/ofi-momentum-proposal.md', ('sub', 3, '**Status:**', None))], '2026-04-29', 'doc', 'doc status moved from PROPOSED - pending user approval to APPROVED; the Q-table is byte-identical first commit -> REV')
OUT[('docs/swing-pivot-proposal.md', 'Q1')] = ('ADOPTED', '(2)', [('docs/swing-pivot-proposal.md', ('sub', 3, '**Status:**', None))], '2026-04-28', 'doc', 'doc status moved from PROPOSED - pending user approval to APPROVED; the Q-table is byte-identical first commit -> REV')
OUT[('docs/swing-pivot-proposal.md', 'Q2')] = ('ADOPTED', '(2)', [('docs/swing-pivot-proposal.md', ('sub', 3, '**Status:**', None))], '2026-04-28', 'doc', 'doc status moved from PROPOSED - pending user approval to APPROVED; the Q-table is byte-identical first commit -> REV')
OUT[('docs/vpfr-lite-v2-proposal.md', 'Q1')] = ('ADOPTED', '(1)', [('docs/vpfr-lite-v2-proposal.md', ('sub', 3, '**Status:**', None))], '2026-04-29', 'doc', 'doc status moved from PROPOSED - pending user approval to APPROVED; the Q-table is byte-identical first commit -> REV')
OUT[('docs/vpfr-lite-v2-proposal.md', 'Q2')] = ('ADOPTED', '(2)', [('docs/vpfr-lite-v2-proposal.md', ('sub', 3, '**Status:**', None))], '2026-04-29', 'doc', 'doc status moved from PROPOSED - pending user approval to APPROVED; the Q-table is byte-identical first commit -> REV')
OUT[('docs/vpfr-lite-v2-proposal.md', 'Q6')] = ('ADOPTED', '(2)', [('docs/vpfr-lite-v2-proposal.md', ('sub', 3, '**Status:**', None))], '2026-04-29', 'doc', 'doc status moved from PROPOSED - pending user approval to APPROVED; the Q-table is byte-identical first commit -> REV')
OUT[('docs/dynamic-microcvd-accel-proposal.md', 'Q1')] = ('ADOPTED', '(1)', [('docs/dynamic-microcvd-accel-proposal.md', ('sub', 3, '**Status:**', None))], '2026-04-29', 'doc', 'doc status moved from PROPOSED - pending user approval to APPROVED; the Q-table is byte-identical first commit -> REV')
OUT[('docs/dynamic-microcvd-accel-proposal.md', 'Q2')] = ('ADOPTED', '(1)', [('docs/dynamic-microcvd-accel-proposal.md', ('sub', 3, '**Status:**', None))], '2026-04-29', 'doc', 'doc status moved from PROPOSED - pending user approval to APPROVED; the Q-table is byte-identical first commit -> REV')
OUT[('docs/dynamic-microcvd-accel-proposal.md', 'Q3')] = ('ADOPTED', '(1)', [('docs/dynamic-microcvd-accel-proposal.md', ('sub', 3, '**Status:**', None))], '2026-04-29', 'doc', 'doc status moved from PROPOSED - pending user approval to APPROVED; the Q-table is byte-identical first commit -> REV')
OUT[('docs/settings-exposure-pass-proposal.md', 'Q2')] = ('ADOPTED', '(2)', [('docs/settings-exposure-pass-proposal.md', ('sub', 3, '**Status:**', None))], '2026-04-28', 'doc', 'doc status moved from PROPOSED - pending user approval to APPROVED; the Q-table is byte-identical first commit -> REV')
OUT[('docs/analysis-log-csv-expansion-proposal.md', 'Q1')] = ('ADOPTED', '(2)', [('docs/analysis-log-csv-expansion-proposal.md', ('sub', 3, '**Status:**', None))], '2026-04-29', 'doc', 'doc status moved from PROPOSED - pending user approval to APPROVED; the Q-table is byte-identical first commit -> REV')
OUT[('docs/analysis-log-csv-expansion-proposal.md', 'Q2')] = ('ADOPTED', '(1)', [('docs/analysis-log-csv-expansion-proposal.md', ('sub', 3, '**Status:**', None))], '2026-04-29', 'doc', 'doc status moved from PROPOSED - pending user approval to APPROVED; the Q-table is byte-identical first commit -> REV')
OUT[('docs/analysis-log-csv-expansion-proposal.md', 'Q3')] = ('ADOPTED', '(1)', [('docs/analysis-log-csv-expansion-proposal.md', ('sub', 3, '**Status:**', None))], '2026-04-29', 'doc', 'doc status moved from PROPOSED - pending user approval to APPROVED; the Q-table is byte-identical first commit -> REV')
OUT[('docs/analysis-log-csv-expansion-proposal.md', 'Q6')] = ('ADOPTED', '(1)', [('docs/analysis-log-csv-expansion-proposal.md', ('sub', 3, '**Status:**', None))], '2026-04-29', 'doc', 'doc status moved from PROPOSED - pending user approval to APPROVED; the Q-table is byte-identical first commit -> REV')
OUT[('docs/v17-followup-fixes-proposal.md', 'Q6')] = ('ADOPTED', '(2)', [('docs/v17-followup-fixes-proposal.md', ('sub', 3, '**Status:**', None))], '2026-04-29', 'doc', 'doc status moved from PROPOSED - pending user approval to APPROVED; the Q-table is byte-identical first commit -> REV')
OUT[('docs/v19-calibration-tuning-pass-proposal.md', 'Q3')] = ('ADOPTED', '(1)', [('docs/v19-calibration-tuning-pass-proposal.md', ('sub', 3, '**Status:**', None))], '2026-04-30', 'doc', 'doc status moved from PROPOSED - pending user approval to APPROVED; the Q-table is byte-identical first commit -> REV')
OUT[('docs/v20-rsi-roc-algorithm-fixes-proposal.md', 'Q9')] = ('ADOPTED', '(2)', [('docs/v20-rsi-roc-algorithm-fixes-proposal.md', ('sub', 3, '**Status:**', None))], '2026-04-30', 'doc', 'doc status moved from PROPOSED - pending user approval to APPROVED; the Q-table is byte-identical first commit -> REV')
OUT[('docs/api-resilience-pass-proposal.md', 'Q1')] = ('ADOPTED', '(1)', [('docs/api-resilience-pass-proposal.md', ('at', 'ea2da7b', 'docs/api-resilience-pass-proposal.md', ('sub', 3, '**Status:**', None)))], '2026-04-29', 'doc', 'doc status moved from PROPOSED - pending user approval to APPROVED; the Q-table is byte-identical first commit -> REV')
OUT[('docs/api-resilience-pass-proposal.md', 'Q2')] = ('ADOPTED', '(1)', [('docs/api-resilience-pass-proposal.md', ('at', 'ea2da7b', 'docs/api-resilience-pass-proposal.md', ('sub', 3, '**Status:**', None)))], '2026-04-29', 'doc', 'doc status moved from PROPOSED - pending user approval to APPROVED; the Q-table is byte-identical first commit -> REV')
OUT[('docs/on-close-analysis-mode-proposal.md', 'S9.1')] = ('ADOPTED', '(1)', [('docs/on-close-analysis-mode-proposal.md', ('sub', 137, 'All five confirmed', None)), ('docs/on-close-analysis-mode-proposal.md', ('sub', 139, '1. **Fire at exec-resolution close**', 'close**'))], '2026-06-25', 'table', '')
OUT[('docs/realtime-exit-guard-proposal.md', 'S9.1')] = ('ADOPTED', '(1)', [('docs/realtime-exit-guard-proposal.md', ('sub', 185, 'All six confirmed', None)), ('docs/realtime-exit-guard-proposal.md', ('sub', 187, '1. **`enabled` = true**', 'true**'))], '2026-06-24', 'table', '')
OUT[('docs/realtime-exit-guard-proposal.md', 'S9.3')] = ('ADOPTED', '(1)', [('docs/realtime-exit-guard-proposal.md', ('sub', 185, 'All six confirmed', None)), ('docs/realtime-exit-guard-proposal.md', ('sub', 189, '3. **`debounce_evals` = 2**', '= 2**'))], '2026-06-24', 'table', '')
OUT[('docs/realtime-exit-guard-proposal.md', 'S9.5')] = ('ADOPTED', '(1)', [('docs/realtime-exit-guard-proposal.md', ('sub', 185, 'All six confirmed', None)), ('docs/realtime-exit-guard-proposal.md', ('sub', 191, '5. **Single-adverse Warn state surfaced**', 'surfaced**'))], '2026-06-24', 'table', '')
OUT[('docs/realtime-exit-guard-proposal.md', 'S9.6')] = ('ADOPTED', '(1)', [('docs/realtime-exit-guard-proposal.md', ('sub', 185, 'All six confirmed', None)), ('docs/realtime-exit-guard-proposal.md', ('sub', 192, '6. **Latch = auto-clear**', 'auto-clear**'))], '2026-06-24', 'table', '')
OUT[('docs/live-microstructure-strip-proposal.md', 'S9.2')] = ('ADOPTED', '(1)', [('docs/live-microstructure-strip-proposal.md', ('sub', 135, '## 9. Settled decisions', None)), ('docs/live-microstructure-strip-proposal.md', ('sub', 140, '2. **Placement**', 'header**'))], '2026-06-25', 'table', '')
OUT[('docs/live-microstructure-strip-proposal.md', 'S9.4')] = ('OVERRULED', '(2)', [('docs/live-microstructure-strip-proposal.md', ('sub', 135, '## 9. Settled decisions', None)), ('docs/live-microstructure-strip-proposal.md', ('sub', 142, '4. **Nearest levels = BOTH above & below**', 'implementation.'))], '2026-06-25', 'row', '')
OUT[('docs/live-microstructure-strip-proposal.md', 'S9.5')] = ('ADOPTED', '(1)', [('docs/live-microstructure-strip-proposal.md', ('sub', 135, '## 9. Settled decisions', None)), ('docs/live-microstructure-strip-proposal.md', ('sub', 143, '5. **Tape speed = both**', '`$/s`.'))], '2026-06-25', 'table', '')
OUT[('docs/auto-tweaker-session-resolution-filter-proposal.md', 'S5.2')] = ('ADOPTED', '(1)', [('docs/auto-tweaker-session-resolution-filter-proposal.md', ('sub', 114, '**Trader sign-off 2026-06-17', 'off-surface'))], '2026-06-17', 'row', '')
OUT[('docs/offline-analysis-report-audit-proposal.md', 'D1')] = ('ADOPTED', '(1)', [('docs/offline-analysis-report-audit-proposal.md', ('sub', 194, '## 5. Design decisions — ALL APPROVED', None)), ('docs/offline-analysis-report-audit-proposal.md', ('sub', 196, '- **D1 — Segmentation granularity: `(session × resolution)`** ✓', None))], '2026-06-18', 'row', '')
OUT[('docs/offline-analysis-report-audit-proposal.md', 'D3')] = ('PARTIAL', '(1)+trader refinement', [('docs/offline-analysis-report-audit-proposal.md', ('sub', 194, '## 5. Design decisions — ALL APPROVED', None)), ('docs/offline-analysis-report-audit-proposal.md', ('sub', 198, '- **D3 — Pooled view: DROP the single pooled matrix** ✓', '(trader refinement)'))], '2026-06-18', 'row', 'the recommended drop is kept and REPLACED by a tier-major per-session expansion the trader added; neither offered option alone')
OUT[('docs/time-averaged-ofi-proposal.md', 'S10.1')] = ('ADOPTED', '(a)', [('docs/time-averaged-ofi-proposal.md', ('sub', 134, 'All five confirmed **as recommended**', 'below.'))], '2026-06-29', 'table', '')
OUT[('docs/time-averaged-ofi-proposal.md', 'S10.2')] = ('ADOPTED', '(1)', [('docs/time-averaged-ofi-proposal.md', ('sub', 134, 'All five confirmed **as recommended**', 'below.'))], '2026-06-29', 'table', '')
OUT[('docs/time-averaged-ofi-proposal.md', 'S10.3')] = ('ADOPTED', '(1)', [('docs/time-averaged-ofi-proposal.md', ('sub', 134, 'All five confirmed **as recommended**', 'below.'))], '2026-06-29', 'table', '')
OUT[('docs/time-averaged-ofi-proposal.md', 'S10.4')] = ('ADOPTED', '(1)', [('docs/time-averaged-ofi-proposal.md', ('sub', 134, 'All five confirmed **as recommended**', 'below.'))], '2026-06-29', 'table', '')
OUT[('docs/time-averaged-ofi-proposal.md', 'S10.5')] = ('ADOPTED', '(1)', [('docs/time-averaged-ofi-proposal.md', ('sub', 134, 'All five confirmed **as recommended**', 'below.'))], '2026-06-29', 'table', '')
OUT[('docs/dev-workflow-automation-proposal.md', 'B')] = ('PARTIAL', '(1)+(3)', [('docs/dev-workflow-automation-proposal.md', ('sub', 8, '**Decisions taken (trader, 2026-06-30):**', None))], '2026-06-30', 'row', 'ruled Stop hook advisory-only: the recommended Stop event combined with the advisory-only option; the recommendation left advisory-or-blocking to the trader')
OUT[('docs/dev-workflow-automation-proposal.md', 'C')] = ('ADOPTED', '(1)', [('docs/dev-workflow-automation-proposal.md', ('sub', 8, '**Decisions taken (trader, 2026-06-30):**', None))], '2026-06-30', 'row', '')
OUT[('docs/dev-workflow-automation-proposal.md', 'D')] = ('ADOPTED', '(1)', [('docs/dev-workflow-automation-proposal.md', ('sub', 8, '**Decisions taken (trader, 2026-06-30):**', None))], '2026-06-30', 'row', '')
OUT[('docs/dev-workflow-automation-proposal.md', 'E')] = ('OVERRULED', 'neither (not built)', [('docs/dev-workflow-automation-proposal.md', ('sub', 8, '**Decisions taken (trader, 2026-06-30):**', None))], '2026-06-30', 'row', 'ruled: coordinator-review/implementer subagents not built (budget) - an option not offered')
OUT[('docs/dev-workflow-automation-proposal.md', 'F')] = ('ADOPTED', '(1)', [('docs/dev-workflow-automation-proposal.md', ('sub', 8, '**Decisions taken (trader, 2026-06-30):**', None))], '2026-06-30', 'row', '')
OUT[('docs/audit-fixes-2026-07-02-proposal.md', 'D1')] = ('ADOPTED', '(1)', [('docs/audit-fixes-2026-07-02-proposal.md', ('sub', 89, '## 7. Sign-off decisions — ✅ ALL APPROVED AS RECOMMENDED', None)), ('docs/audit-fixes-2026-07-02-proposal.md', ('cellsub', 93, 3, '✅ **Remove**', '**Remove**'))], '2026-07-02', 'table', '')
OUT[('docs/audit-fixes-2026-07-02-proposal.md', 'D2')] = ('ADOPTED', '(1)', [('docs/audit-fixes-2026-07-02-proposal.md', ('sub', 89, '## 7. Sign-off decisions — ✅ ALL APPROVED AS RECOMMENDED', None))], '2026-07-02', 'table', '')
OUT[('docs/audit-fixes-2026-07-02-proposal.md', 'D3')] = ('ADOPTED', '(1)', [('docs/audit-fixes-2026-07-02-proposal.md', ('sub', 89, '## 7. Sign-off decisions — ✅ ALL APPROVED AS RECOMMENDED', None))], '2026-07-02', 'table', '')
OUT[('docs/signal-health-retune-proposal.md', 'D2')] = ('ADOPTED', '(1)', [('docs/signal-health-retune-proposal.md', ('sub', 77, '## 6. Sign-off decisions — ALL TICKED by the trader 2026-07-03', None))], '2026-07-03', 'table', '')
OUT[('docs/placed-geometry-structural-first-proposal.md', 'D3')] = ('ADOPTED', '(a)', [('docs/placed-geometry-structural-first-proposal.md', ('sub', 96, '## 9. Sign-off decisions — ALL TICKED by the trader 2026-07-03 (D3 = clamp)', None))], '2026-07-03', 'row', '')
OUT[('docs/placed-geometry-derivation-2026-07-06.md', 'DG2')] = ('ADOPTED', '(1)', [('docs/placed-geometry-derivation-2026-07-06.md', ('sub', 3, '**Status:** APPROVED — trader ticked DG1–DG5, 2026-07-06, all recommended values', 'all recommended values'))], '2026-07-06', 'table', '')
OUT[('docs/placed-geometry-derivation-2026-07-06.md', 'DG3')] = ('ADOPTED', '(2)', [('docs/placed-geometry-derivation-2026-07-06.md', ('sub', 3, '**Status:** APPROVED — trader ticked DG1–DG5, 2026-07-06, all recommended values', 'all recommended values'))], '2026-07-06', 'table', '')
OUT[('docs/funding-momentum-time-anchored-window-proposal.md', 'D4')] = ('ADOPTED', '(2)', [('docs/funding-momentum-time-anchored-window-proposal.md', ('sub', 86, '## 8. Sign-off decisions — ALL TICKED by the trader 2026-07-07 (as recommended)', None))], '2026-07-07', 'table', '')
