"""Harness 6 (decision-bias tripwire), Phase A: the trader RULINGS for every population entry.

⛔ This file carries OUTCOMES. The seat writing the blind baseline must not open it (nor the
outcomes JSON) until that baseline is written and committed. Keyed by (doc, label) exactly as
in manifest.py.

OUT[(doc, label)] = (outcome, ruled_label, [(path, span), ...], ruling_date_utc, granularity, note)
  outcome: ADOPTED (ruling == recommendation) | OVERRULED (ruling differs, or the doc records the
           recommendation as DEFEATED/overruled - that record wins over a combined ruling) |
           PARTIAL (a modified or combined option, not recorded as defeated)
  spans are read at REV unless wrapped in ('at', rev, path, span)
  granularity: 'row' per-decision ruling | 'table' one ruling for a whole D-table or list |
               'doc' a doc-level approval of a spec that carried the answer
"""

from manifest import S, E, C, CS, AT  # span helpers only; no state is read from here

OUT = {}
OUT[('docs/bid-ask-spread-proposal.md', 'Q2')] = ('ADOPTED', '(1)', [('docs/bid-ask-spread-proposal.md', ('sub', 3, '**Status:**', None))], '2026-04-28', 'doc', 'doc status moved from PROPOSED - pending user approval to APPROVED; the Q-table is byte-identical first commit -> REV')
OUT[('docs/ofi-momentum-proposal.md', 'Q2')] = ('ADOPTED', '(2)', [('docs/ofi-momentum-proposal.md', ('sub', 3, '**Status:**', None))], '2026-04-29', 'doc', 'doc status moved from PROPOSED - pending user approval to APPROVED; the Q-table is byte-identical first commit -> REV')
OUT[('docs/swing-pivot-proposal.md', 'Q1')] = ('ADOPTED', '(2)', [('docs/swing-pivot-proposal.md', ('sub', 3, '**Status:**', None))], '2026-04-28', 'doc', 'doc status moved from PROPOSED - pending user approval to APPROVED; the Q-table is byte-identical first commit -> REV')
OUT[('docs/swing-pivot-proposal.md', 'Q2')] = ('ADOPTED', '(2)', [('docs/swing-pivot-proposal.md', ('sub', 3, '**Status:**', None))], '2026-04-28', 'doc', 'doc status moved from PROPOSED - pending user approval to APPROVED; the Q-table is byte-identical first commit -> REV')
OUT[('docs/vpfr-lite-v2-proposal.md', 'Q1')] = ('ADOPTED', '(1)', [('docs/vpfr-lite-v2-proposal.md', ('sub', 3, '**Status:**', None))], '2026-04-29', 'doc', 'doc status moved from PROPOSED - pending user approval to APPROVED; the Q-table is byte-identical first commit -> REV')
OUT[('docs/vpfr-lite-v2-proposal.md', 'Q2')] = ('ADOPTED', '(2)', [('docs/vpfr-lite-v2-proposal.md', ('sub', 3, '**Status:**', None))], '2026-04-29', 'doc', 'doc status moved from PROPOSED - pending user approval to APPROVED; the Q-table is byte-identical first commit -> REV')
OUT[('docs/vpfr-lite-v2-proposal.md', 'Q6')] = ('ADOPTED', '(2)', [('docs/vpfr-lite-v2-proposal.md', ('sub', 3, '**Status:**', None))], '2026-04-29', 'doc', 'doc status moved from PROPOSED - pending user approval to APPROVED; the Q-table is byte-identical first commit -> REV')
OUT[('docs/dynamic-microcvd-accel-proposal.md', 'Q1')] = ('ADOPTED', '(1)', [('docs/dynamic-microcvd-accel-proposal.md', ('sub', 3, '**Status:**', None))], '2026-04-29', 'doc', 'doc status moved from PROPOSED - pending user approval to APPROVED; the Q-table is byte-identical first commit -> REV')
OUT[('docs/dynamic-microcvd-accel-proposal.md', 'Q2')] = ('ADOPTED', '(1)', [('docs/dynamic-microcvd-accel-proposal.md', ('sub', 3, '**Status:**', None))], '2026-04-29', 'doc', 'doc status moved from PROPOSED - pending user approval to APPROVED; the Q-table is byte-identical first commit -> REV')
OUT[('docs/dynamic-microcvd-accel-proposal.md', 'Q3')] = ('ADOPTED', '(1)', [('docs/dynamic-microcvd-accel-proposal.md', ('sub', 3, '**Status:**', None))], '2026-04-29', 'doc', 'doc status moved from PROPOSED - pending user approval to APPROVED; the Q-table is byte-identical first commit -> REV')
OUT[('docs/settings-exposure-pass-proposal.md', 'Q2')] = ('ADOPTED', '(2)', [('docs/settings-exposure-pass-proposal.md', ('sub', 3, '**Status:**', None))], '2026-04-28', 'doc', 'doc status moved from PROPOSED - pending user approval to APPROVED; the Q-table is byte-identical first commit -> REV')
OUT[('docs/analysis-log-csv-expansion-proposal.md', 'Q1')] = ('ADOPTED', '(2)', [('docs/analysis-log-csv-expansion-proposal.md', ('sub', 3, '**Status:**', None))], '2026-04-29', 'doc', 'doc status moved from PROPOSED - pending user approval to APPROVED; the Q-table is byte-identical first commit -> REV')
OUT[('docs/analysis-log-csv-expansion-proposal.md', 'Q2')] = ('ADOPTED', '(1)', [('docs/analysis-log-csv-expansion-proposal.md', ('sub', 3, '**Status:**', None))], '2026-04-29', 'doc', 'doc status moved from PROPOSED - pending user approval to APPROVED; the Q-table is byte-identical first commit -> REV')
OUT[('docs/analysis-log-csv-expansion-proposal.md', 'Q3')] = ('ADOPTED', '(1)', [('docs/analysis-log-csv-expansion-proposal.md', ('sub', 3, '**Status:**', None))], '2026-04-29', 'doc', 'doc status moved from PROPOSED - pending user approval to APPROVED; the Q-table is byte-identical first commit -> REV')
OUT[('docs/analysis-log-csv-expansion-proposal.md', 'Q6')] = ('ADOPTED', '(1)', [('docs/analysis-log-csv-expansion-proposal.md', ('sub', 3, '**Status:**', None))], '2026-04-29', 'doc', 'doc status moved from PROPOSED - pending user approval to APPROVED; the Q-table is byte-identical first commit -> REV')
OUT[('docs/v17-followup-fixes-proposal.md', 'Q6')] = ('ADOPTED', '(2)', [('docs/v17-followup-fixes-proposal.md', ('sub', 3, '**Status:**', None))], '2026-04-29', 'doc', 'doc status moved from PROPOSED - pending user approval to APPROVED; the Q-table is byte-identical first commit -> REV')
OUT[('docs/v19-calibration-tuning-pass-proposal.md', 'Q3')] = ('ADOPTED', '(1)', [('docs/v19-calibration-tuning-pass-proposal.md', ('sub', 3, '**Status:**', None))], '2026-04-30', 'doc', 'doc status moved from PROPOSED - pending user approval to APPROVED; the Q-table is byte-identical first commit -> REV')
OUT[('docs/v20-rsi-roc-algorithm-fixes-proposal.md', 'Q9')] = ('ADOPTED', '(2)', [('docs/v20-rsi-roc-algorithm-fixes-proposal.md', ('sub', 3, '**Status:**', None))], '2026-04-30', 'doc', 'doc status moved from PROPOSED - pending user approval to APPROVED; the Q-table is byte-identical first commit -> REV')
OUT[('docs/api-resilience-pass-proposal.md', 'Q1')] = ('ADOPTED', '(1)', [('docs/api-resilience-pass-proposal.md', ('at', 'ea2da7b', 'docs/api-resilience-pass-proposal.md', ('sub', 3, '**Status:**', None)))], '2026-04-29', 'doc', 'doc status moved from PROPOSED - pending user approval to APPROVED; the Q-table is byte-identical first commit -> REV')
OUT[('docs/api-resilience-pass-proposal.md', 'Q2')] = ('ADOPTED', '(1)', [('docs/api-resilience-pass-proposal.md', ('at', 'ea2da7b', 'docs/api-resilience-pass-proposal.md', ('sub', 3, '**Status:**', None)))], '2026-04-29', 'doc', 'doc status moved from PROPOSED - pending user approval to APPROVED; the Q-table is byte-identical first commit -> REV')
OUT[('docs/on-close-analysis-mode-proposal.md', 'S9.1')] = ('ADOPTED', '(1)', [('docs/on-close-analysis-mode-proposal.md', ('sub', 137, 'All five confirmed', None)), ('docs/on-close-analysis-mode-proposal.md', ('sub', 139, '1. **Fire at exec-resolution close**', 'close**'))], '2026-06-25', 'table', '')
OUT[('docs/realtime-exit-guard-proposal.md', 'S9.1')] = ('ADOPTED', '(1)', [('docs/realtime-exit-guard-proposal.md', ('sub', 185, 'All six confirmed', None)), ('docs/realtime-exit-guard-proposal.md', ('sub', 187, '1. **`enabled` = true**', 'true**'))], '2026-06-24', 'table', '')
OUT[('docs/realtime-exit-guard-proposal.md', 'S9.3')] = ('ADOPTED', '(1)', [('docs/realtime-exit-guard-proposal.md', ('sub', 185, 'All six confirmed', None)), ('docs/realtime-exit-guard-proposal.md', ('sub', 189, '3. **`debounce_evals` = 2**', '= 2**'))], '2026-06-24', 'table', '')
OUT[('docs/realtime-exit-guard-proposal.md', 'S9.5')] = ('ADOPTED', '(1)', [('docs/realtime-exit-guard-proposal.md', ('sub', 185, 'All six confirmed', None)), ('docs/realtime-exit-guard-proposal.md', ('sub', 191, '5. **Single-adverse Warn state surfaced**', 'surfaced**'))], '2026-06-24', 'table', '')
OUT[('docs/realtime-exit-guard-proposal.md', 'S9.6')] = ('ADOPTED', '(1)', [('docs/realtime-exit-guard-proposal.md', ('sub', 185, 'All six confirmed', None)), ('docs/realtime-exit-guard-proposal.md', ('sub', 192, '6. **Latch = auto-clear**', 'auto-clear**'))], '2026-06-24', 'table', '')
OUT[('docs/live-microstructure-strip-proposal.md', 'S9.2')] = ('ADOPTED', '(1)', [('docs/live-microstructure-strip-proposal.md', ('sub', 135, '## 9. Settled decisions', None)), ('docs/live-microstructure-strip-proposal.md', ('sub', 140, '2. **Placement**', 'header**'))], '2026-06-25', 'table', '')
OUT[('docs/live-microstructure-strip-proposal.md', 'S9.4')] = ('OVERRULED', '(2)', [('docs/live-microstructure-strip-proposal.md', ('sub', 135, '## 9. Settled decisions', None)), ('docs/live-microstructure-strip-proposal.md', ('sub', 142, '4. **Nearest levels = BOTH above & below**', 'implementation.'))], '2026-06-25', 'row', '')
OUT[('docs/live-microstructure-strip-proposal.md', 'S9.5')] = ('ADOPTED', '(1)', [('docs/live-microstructure-strip-proposal.md', ('sub', 135, '## 9. Settled decisions', None)), ('docs/live-microstructure-strip-proposal.md', ('sub', 143, '5. **Tape speed = both**', '`$/s`.'))], '2026-06-25', 'table', '')
OUT[('docs/auto-tweaker-session-resolution-filter-proposal.md', 'S5.2')] = ('ADOPTED', '(1)', [('docs/auto-tweaker-session-resolution-filter-proposal.md', ('sub', 114, '**Trader sign-off 2026-06-17', 'off-surface'))], '2026-06-17', 'row', '')
OUT[('docs/offline-analysis-report-audit-proposal.md', 'D1')] = ('ADOPTED', '(1)', [('docs/offline-analysis-report-audit-proposal.md', ('sub', 194, '## 5. Design decisions — ALL APPROVED', None)), ('docs/offline-analysis-report-audit-proposal.md', ('sub', 196, '- **D1 — Segmentation granularity: `(session × resolution)`** ✓', None))], '2026-06-18', 'row', '')
OUT[('docs/offline-analysis-report-audit-proposal.md', 'D3')] = ('PARTIAL', '(1)+trader refinement', [('docs/offline-analysis-report-audit-proposal.md', ('sub', 194, '## 5. Design decisions — ALL APPROVED', None)), ('docs/offline-analysis-report-audit-proposal.md', ('sub', 198, '- **D3 — Pooled view: DROP the single pooled matrix** ✓', '(trader refinement)'))], '2026-06-18', 'row', 'the recommended drop is kept and REPLACED by a tier-major per-session expansion the trader added; neither offered option alone')
OUT[('docs/time-averaged-ofi-proposal.md', 'S10.1')] = ('ADOPTED', '(a)', [('docs/time-averaged-ofi-proposal.md', ('sub', 134, 'All five confirmed **as recommended**', 'below.'))], '2026-06-29', 'table', '')
OUT[('docs/time-averaged-ofi-proposal.md', 'S10.2')] = ('ADOPTED', '(1)', [('docs/time-averaged-ofi-proposal.md', ('sub', 134, 'All five confirmed **as recommended**', 'below.'))], '2026-06-29', 'table', '')
OUT[('docs/time-averaged-ofi-proposal.md', 'S10.3')] = ('ADOPTED', '(1)', [('docs/time-averaged-ofi-proposal.md', ('sub', 134, 'All five confirmed **as recommended**', 'below.'))], '2026-06-29', 'table', '')
OUT[('docs/time-averaged-ofi-proposal.md', 'S10.4')] = ('ADOPTED', '(1)', [('docs/time-averaged-ofi-proposal.md', ('sub', 134, 'All five confirmed **as recommended**', 'below.'))], '2026-06-29', 'table', '')
OUT[('docs/time-averaged-ofi-proposal.md', 'S10.5')] = ('ADOPTED', '(1)', [('docs/time-averaged-ofi-proposal.md', ('sub', 134, 'All five confirmed **as recommended**', 'below.'))], '2026-06-29', 'table', '')
OUT[('docs/dev-workflow-automation-proposal.md', 'B')] = ('PARTIAL', '(1)+(3)', [('docs/dev-workflow-automation-proposal.md', ('sub', 8, '**Decisions taken (trader, 2026-06-30):**', None))], '2026-06-30', 'row', 'ruled Stop hook advisory-only: the recommended Stop event combined with the advisory-only option; the recommendation left advisory-or-blocking to the trader')
OUT[('docs/dev-workflow-automation-proposal.md', 'C')] = ('ADOPTED', '(1)', [('docs/dev-workflow-automation-proposal.md', ('sub', 8, '**Decisions taken (trader, 2026-06-30):**', None))], '2026-06-30', 'row', '')
OUT[('docs/dev-workflow-automation-proposal.md', 'D')] = ('ADOPTED', '(1)', [('docs/dev-workflow-automation-proposal.md', ('sub', 8, '**Decisions taken (trader, 2026-06-30):**', None))], '2026-06-30', 'row', '')
OUT[('docs/dev-workflow-automation-proposal.md', 'E')] = ('OVERRULED', 'neither (not built)', [('docs/dev-workflow-automation-proposal.md', ('sub', 8, '**Decisions taken (trader, 2026-06-30):**', None))], '2026-06-30', 'row', 'ruled: coordinator-review/implementer subagents not built (budget) - an option not offered')
OUT[('docs/dev-workflow-automation-proposal.md', 'F')] = ('ADOPTED', '(1)', [('docs/dev-workflow-automation-proposal.md', ('sub', 8, '**Decisions taken (trader, 2026-06-30):**', None))], '2026-06-30', 'row', '')
OUT[('docs/audit-fixes-2026-07-02-proposal.md', 'D1')] = ('ADOPTED', '(1)', [('docs/audit-fixes-2026-07-02-proposal.md', ('sub', 89, '## 7. Sign-off decisions — ✅ ALL APPROVED AS RECOMMENDED', None)), ('docs/audit-fixes-2026-07-02-proposal.md', ('cellsub', 93, 3, '✅ **Remove**', '**Remove**'))], '2026-07-02', 'table', '')
OUT[('docs/audit-fixes-2026-07-02-proposal.md', 'D2')] = ('ADOPTED', '(1)', [('docs/audit-fixes-2026-07-02-proposal.md', ('sub', 89, '## 7. Sign-off decisions — ✅ ALL APPROVED AS RECOMMENDED', None))], '2026-07-02', 'table', '')
OUT[('docs/audit-fixes-2026-07-02-proposal.md', 'D3')] = ('ADOPTED', '(1)', [('docs/audit-fixes-2026-07-02-proposal.md', ('sub', 89, '## 7. Sign-off decisions — ✅ ALL APPROVED AS RECOMMENDED', None))], '2026-07-02', 'table', '')
OUT[('docs/signal-health-retune-proposal.md', 'D2')] = ('ADOPTED', '(1)', [('docs/signal-health-retune-proposal.md', ('sub', 77, '## 6. Sign-off decisions — ALL TICKED by the trader 2026-07-03', None))], '2026-07-03', 'table', '')
OUT[('docs/placed-geometry-structural-first-proposal.md', 'D3')] = ('ADOPTED', '(a)', [('docs/placed-geometry-structural-first-proposal.md', ('sub', 96, '## 9. Sign-off decisions — ALL TICKED by the trader 2026-07-03 (D3 = clamp)', None))], '2026-07-03', 'row', '')
OUT[('docs/placed-geometry-derivation-2026-07-06.md', 'DG2')] = ('ADOPTED', '(1)', [('docs/placed-geometry-derivation-2026-07-06.md', ('sub', 3, '**Status:** APPROVED — trader ticked DG1–DG5, 2026-07-06, all recommended values', 'all recommended values'))], '2026-07-06', 'table', '')
OUT[('docs/placed-geometry-derivation-2026-07-06.md', 'DG3')] = ('ADOPTED', '(2)', [('docs/placed-geometry-derivation-2026-07-06.md', ('sub', 3, '**Status:** APPROVED — trader ticked DG1–DG5, 2026-07-06, all recommended values', 'all recommended values'))], '2026-07-06', 'table', '')
OUT[('docs/funding-momentum-time-anchored-window-proposal.md', 'D4')] = ('ADOPTED', '(2)', [('docs/funding-momentum-time-anchored-window-proposal.md', ('sub', 86, '## 8. Sign-off decisions — ALL TICKED by the trader 2026-07-07 (as recommended)', None))], '2026-07-07', 'table', '')
OUT[('docs/d6-eval-placed-stop-migration-proposal.md', 'D1')] = ('ADOPTED', '(1)', [('docs/d6-eval-placed-stop-migration-proposal.md', S(3, '**APPROVED 2026-07-14', 'as recommended).**'))], '2026-07-14', 'row', '')
OUT[('docs/aggressor-velocity-s52-derivation-2026-07-13.md', 'S1')] = ('ADOPTED', '(1)', [('docs/aggressor-velocity-s52-derivation-2026-07-13.md', S(56, '## 7. S-table — **ALL TICKED 2026-07-14: S1 = 4.5**', 'as recommended.'))], '2026-07-14', 'row', 'ticked after the trader asked for a plain-terms explanation of the burst ratio')
OUT[('docs/aggressor-velocity-s52-derivation-2026-07-13.md', 'S2')] = ('ADOPTED', '(a)', [('docs/aggressor-velocity-s52-derivation-2026-07-13.md', S(56, '## 7. S-table — **ALL TICKED 2026-07-14', 'S2 = option (a)'))], '2026-07-14', 'row', '')
OUT[('docs/session-policy-gate-proposal.md', 'P1')] = ('ADOPTED', '(1)', [('docs/session-policy-gate-proposal.md', S(3, '**APPROVED — P1–P5 ALL TICKED 2026-07-18 (as recommended).', '(as recommended).'))], '2026-07-18', 'table', '')
OUT[('docs/eval-no-data-outcome-proposal.md', 'N4')] = ('ADOPTED', '(1)', [('docs/eval-no-data-outcome-proposal.md', CS(28, 3, '✅ **TICKED 2026-07-21: migrate to placed geometry**')), ('docs/eval-no-data-outcome-proposal.md', S(31, '**N1–N5 ALL TICKED 2026-07-21'))], '2026-07-21', 'row', '')
OUT[('docs/geometry-arbitration-modes-proposal.md', 'G2')] = ('ADOPTED', '(1)', [('docs/geometry-arbitration-modes-proposal.md', S(3, '**Status:** APPROVED — **G1–G6 ALL TICKED', 'BUILD-AUTHORIZED**'))], '2026-07-21', 'table', 'the row itself was never rewritten; ticked = follow as recommended, the trader definition recorded in absorption-mechanism-revision-proposal.md')
OUT[('docs/liq-cascade-level-alerts-proposal.md', 'H1')] = ('ADOPTED', '(1)', [('docs/liq-cascade-level-alerts-proposal.md', S(3, '**SHIPPED as v59 · 2026-07-22** (H1–H5 all ticked', 'as approved)'))], '2026-07-22', 'table', '')
OUT[('docs/absorption-geometry-rescale-proposal.md', 'V2')] = ('ADOPTED', '(1)', [('docs/absorption-geometry-rescale-spec-back.md', S(9, 'V1–V4 all ticked', 'V1–V4 all ticked'))], '2026-07-23', 'table', '')
OUT[('docs/aggr-vel-s52-london-derivation-2026-07-23.md', 'S1')] = ('ADOPTED', '(1)', [('-', ('commitmsg', '631a3f5', 'calib(v60): LONDON aggressor-velocity burst arming', '(S1-S5 ticked)'))], '2026-07-22', 'table', 'the ruling is recorded only in the v60 commit message, not in any doc at REV')
OUT[('docs/in-app-trade-store-capture-proposal.md', 'D1')] = ('OVERRULED', '(2)', [('docs/in-app-trade-store-capture-proposal.md', CS(135, 3, '**AWS ONLY — ruled against the recommendation', 'the one I offered.**'))], '2026-07-31', 'row', '')
for _q in ('D1', 'D2', 'D3', 'D4', 'D5', 'D6'):
    OUT[('docs/settings-local-overlay-proposal.md', _q)] = ('ADOPTED', '(a)', [('docs/settings-local-overlay-proposal.md', S(4, 'Previously: ✅ APPROVED 2026-08-01 — D1–D6 ALL TICKED all-as-recommended (trader)', '(trader)'))], '2026-08-01', 'table', '')
_tc = [('docs/trade-store-coverage-report-proposal.md', S(245, '> ✅ **TICKED 2026-08-03 (trader), all as recommended:', 'all as recommended:'))]
for _q in ('D1', 'D2', 'D3', 'D7', 'D6'):
    OUT[('docs/trade-store-coverage-report-proposal.md', _q)] = ('ADOPTED', '(a)', _tc, '2026-08-03', 'table', '')
OUT[('docs/trade-store-coverage-report-proposal.md', 'D4')] = ('ADOPTED', '(1)', [('docs/trade-store-coverage-report-proposal.md', S(245, '> ✅ **TICKED 2026-08-03 (trader), all as recommended:', 'D4 300,000 ms'))], '2026-08-03', 'table', '')
OUT[('docs/asia-burst-threshold-derivation-2026-08-01.md', 'D3-1')] = ('ADOPTED', '(7)', [('docs/asia-burst-threshold-derivation-2026-08-01.md', S(79, '## 5. D-table — **TICKED 2026-08-02 (trader).')), ('docs/asia-burst-threshold-derivation-2026-08-01.md', CS(85, 3, '**`sessions.ASIA.burst_ratio_threshold` = 5.5**, as recommended'))], '2026-08-02', 'row', '')
OUT[('docs/ttm-flat-threshold-rederivation-2026-08-02.md', 'D1-d')] = ('ADOPTED', '(b)', [('docs/ttm-flat-threshold-rederivation-2026-08-02.md', CS(89, 4, '✅ **RULED 2026-08-02 (trader): (b) PARK.**', 'PARK.**'))], '2026-08-02', 'row', '')
OUT[('docs/ttm-flat-threshold-rederivation-2026-08-02.md', 'D1-a')] = ('ADOPTED', '(a)', [('docs/ttm-flat-threshold-rederivation-2026-08-02.md', CS(89, 4, '**D1-a/b/c are answered in principle but not scheduled**', 'ATR-relative'))], '2026-08-02', 'row', 'answered in principle within the D1-d park ruling')
for _q, _r in (('D1', '(3)'), ('D5', '(1)'), ('D6', '(2)')):
    OUT[('docs/trade-store-trade-identity-proposal.md', _q)] = ('ADOPTED', _r, [('docs/trade-store-trade-identity-proposal.md', S(149, '## 7. D-table — ✅ **ALL TICKED 2026-08-08 (trader), every row as recommended**'))], '2026-08-08', 'table', '')
for _q, _r in (('D-1', '(a)'), ('D-2', '(1)'), ('D-3', '(a)'), ('D-4', '(a)'), ('D-5', '(a)'), ('D-6', '(2)'), ('D-7', '(1)')):
    OUT[('docs/trade-store-write-guard-identity-proposal.md', _q)] = ('ADOPTED', _r, [('docs/trade-store-write-guard-identity-proposal.md', S(168, '## 4. D-table — ✅ RULED 2026-08-11, trader-directed')), ('docs/trade-store-write-guard-identity-proposal.md', S(170, '> **All seven rows ruled AS RECOMMENDED.', 'no row was deferred.**'))], '2026-08-11', 'table', '')
OUT[('docs/absorption-d6-spec-back.md', 'D-6a')] = ('ADOPTED', '(a)', [('docs/absorption-mechanism-revision-proposal.md', S(310, '> | **D-6a** |', 'measure-tight.')), ('-', ('commitmsg', 'a2a51e3', 'Trader ruled both as recommended', 'section 2.'))], '2026-09-01', 'row', '')
OUT[('docs/absorption-d6-spec-back.md', 'D-6b')] = ('ADOPTED', '(a)', [('docs/absorption-mechanism-revision-proposal.md', S(311, '> | **D-6b** |', 'CLAIM WITHDRAWN.**')), ('-', ('commitmsg', 'a2a51e3', 'Trader ruled both as recommended', 'section 2.'))], '2026-09-01', 'row', '')
OUT[('docs/d6d-episode-continuity-spec.md', 'D-6d.1')] = ('OVERRULED', '(c) sidecar AND one CSV column', [('docs/d6d-episode-continuity-spec.md', CS(248, 2, '✅✅ **RULED (c) BY THE TRADER, 2026-09-11 (UTC)', '(`AbsorptionShadowAggrUsd`).**')), ('docs/d6d-episode-continuity-spec.md', CS(248, 2, '**THIRD DEFEAT OF A CHEAPER READ IN ONE SESSION', 'IN ONE SESSION'))], '2026-09-11', 'row', 'a combined option, but the doc records the recommendation as defeated, so OVERRULED takes precedence over PARTIAL')
OUT[('docs/d6d-episode-continuity-spec.md', 'D-6d.2')] = ('ADOPTED', '(a)', [('docs/d6d-episode-continuity-spec.md', CS(250, 2, '⭐ **`D-6d.2` is SUBSUMED by this ruling', 'asked.**'))], '2026-09-11', 'row', 'subsumed by the D-6d.3 ruling, which the doc says delivers what (a) asked')
OUT[('docs/d6d-episode-continuity-spec.md', 'D-6d.3')] = ('ADOPTED', '(c)', [('docs/d6d-episode-continuity-spec.md', CS(250, 2, '✅✅ **RULED (c) BY THE TRADER, 2026-09-11 (UTC)', 'FOLLOWS THE READ.**'))], '2026-09-11', 'row', 'ADOPTED against the LAST pre-ruling read (c); the first read (b) was withdrawn by the seat on measurement after a trader question (seat-handover-2026-09-14.md bias register)')
OUT[('docs/thin-trade-window-skip-gate-proposal.md', 'D-1')] = ('ADOPTED', '(1)', [('docs/thin-trade-window-skip-gate-spec-back.md', S(4, 'D1–D5 all ticked as recommended, trader-directed.', 'trader-directed.'))], '2026-08-20', 'table', '')
OUT[('docs/collector-ops-tooling-proposal.md', 'D-7')] = ('OVERRULED', '(2)', [('docs/collector-ops-tooling-proposal.md', CS(160, 3, '✅ **TICKED 2026-08-21 — PRODUCTION ONLY.**', 'PRODUCTION ONLY.**'))], '2026-08-20', 'row', 'the box date label reads 2026-08-21 local; commit 462ac12 is 2026-08-20T17:36Z')
OUT[('docs/collector-ops-tooling-proposal.md', 'D-9')] = ('ADOPTED', '(2)', [('docs/collector-ops-tooling-proposal.md', CS(162, 3, '✅ **TICKED 2026-08-21 — ON DEMAND ONLY.**', 'ON DEMAND ONLY.**'))], '2026-08-20', 'row', 'the box date label reads 2026-08-21 local; commit 462ac12 is 2026-08-20T17:36Z')
