#!/usr/bin/env python3
# tools/ops/medium_tier_diagnosis.py
#
# The MEDIUM-tier diagnosis, session 2 (docs/medium-tier-diagnosis-brief-2026-09-16.md section 3, questions D-1 to D-12;
# read: docs/medium-tier-diagnosis-read-2026-09-17.md). Python 3 standard library only (no numpy).
#
# Inputs (gitignored, regenerated by the instrument):
#   <cache>/diagnosis-rows.csv          SwingFallbackRead --mode diagexport: one line per swing read population row,
#                                        the candle-walk outcomes (main window, carried 24 h), the half, logged context.
#   <cache>/rescore-attribution.csv     SwingFallbackRead --mode rescore: per-vote signed points per row (session 1).
#   settings.json (tracked, read-only)  verdict percentages and nominal penalty and bonus magnitudes.
#   <cache>/rescore-eras/settings-v*.json  (optional) proves those values are identical in every era.
#
# Rules fixed before the first run (brief section 4 discipline):
#   * Population: the swing read population (8,810 rows). Sessions separate, never pooled for outcomes.
#   * Outcome: net EV per trade, bps, maker/maker, main window primary, carried 24 h secondary. Success = target hit.
#   * Tier: the logged verdict tier. Scores: the LOGGED scores (diagnosis-rows). Votes: the re-scored breakdown
#     (attribution); rows whose re-score does not match all six fields are kept and counted (sensitivity: excluded).
#   * Vote lean for the trade side X and the other side Y: points(X) - points(Y). Agree > 0, oppose < 0, absent = 0.
#   * Halves: the stability read's split (first floor(D/2) UTC trading days), carried in the export.
#   * CI: 95 % percentile bootstrap of whole UTC trading days, fixed seed, --resamples (default 10,000).
#   * Readable: n >= 100 in every cell a statistic uses, else NOT READABLE.
#   * Label for a comparison d, first match wins (the census rule):
#       NOT READABLE (FULL n < 100 in a cell) -> CONFIRMED (both halves readable, both CIs exclude 0, same sign)
#       -> H1 FINDING, H2 SAME SIGN NOT SIGNIFICANT -> H1 FINDING, H2 CONTRADICTS OR NOT READABLE
#       -> DISCOVERY ONLY (H2) -> NO DIFFERENCE SHOWN.
#   * A cause counts as CONFIRMED only with the CONFIRMED label. Everything else is DISCOVERY ONLY or no finding.
#   * D-1 monotone: OLS slope of per-row net EV on the effective score share (per 0.1 of regime max) and on the
#     effective margin (per point). Monotone increasing = slope > 0 CONFIRMED.
#   * D-3 anti-predictive vote: d = EV(agree) - EV(oppose) < 0 CONFIRMED. Also reported within tier (weights = the
#     tier's agree + oppose rows in each resample).
#   * D-4 tier crossing: counterfactual effective score = effective - applied delta of that mutation on the trade side.
#     Applied delta = the label's points where the label carries only that mutation on that side, else the nominal
#     magnitude (named per mutation). Ka: crossed rows vs untouched rows of the landing tier. Kb: crossed rows vs
#     untouched rows of the origin tier.
#   * D-7 re-weighting: MEDIUM post-stratified to WEAK's stratum mix over strata where both tiers have rows.
#   * D-8 extension terciles: cut points from the session's H1 rows (all tiers), then applied to every row.
#   * D-9 episode: same-side population signals, each within the session's main window of the previous one.
#   * D-12 era segments per session at the scoring edges that touch it; H1/H2 is not used there.
#
# Run (from the repo root):
#   dotnet build tools/ops/SwingFallbackRead/SwingFallbackRead.vbproj -c Release
#   dotnet tools/ops/SwingFallbackRead/bin/Release/net8.0/SwingFallbackRead.dll --root . --mode rescore \
#     --fetch aws_fetch/20260913-153704 --pooled AWS-copybacks/pooled-book-2026-09-09/analysis_log_pooled.csv
#   dotnet tools/ops/SwingFallbackRead/bin/Release/net8.0/SwingFallbackRead.dll --root . --mode diagexport \
#     --fetch aws_fetch/20260913-153704 --pooled AWS-copybacks/pooled-book-2026-09-09/analysis_log_pooled.csv
#   python tools/ops/medium_tier_diagnosis.py --root .

import argparse, csv, glob, hashlib, json, math, os, random, re, sys
from collections import Counter, defaultdict
from datetime import datetime, timezone

SESSIONS = ["NY", "LONDON", "ASIA"]
TIERS = ["STRONG", "MEDIUM", "WEAK"]
FLOOR = 100
LABELS = ["ROC", "RSI", "DMI", "ADX", "VOL", "VWAP", "BBW_TTM", "EMA", "FUNDING", "OI", "OFI", "CVD", "TFI", "MICROCVD",
          "LIQ", "SPREAD", "EMA200", "DONCHIAN", "OBV", "VPFR", "REGIME_ALIGN", "TREND_STRUCTURE"]
ATR_STEP = datetime(2026, 8, 20)
MODES = [("main", "MainNetEv", "MainOutcome", "MainResolveMin"), ("C24", "C24NetEv", "C24Outcome", "C24ResolveMin")]

ap = argparse.ArgumentParser()
ap.add_argument("--root", default=".")
ap.add_argument("--cache", default=os.path.join("backtest_data", "swing-fallback-read"))
ap.add_argument("--resamples", type=int, default=10000)
ap.add_argument("--seed", type=int, default=20260917)
ap.add_argument("--out", default=None)
args = ap.parse_args()
ROOT = os.path.abspath(args.root)
CACHE = os.path.join(ROOT, args.cache)
OUT = args.out or os.path.join(CACHE, "medium-tier-diagnosis-output.md")
R = args.resamples

out = []
def p(s=""):
    out.append(s)

def md5(path):
    h = hashlib.md5()
    with open(path, "rb") as f:
        for b in iter(lambda: f.read(1 << 20), b""):
            h.update(b)
    return h.hexdigest()

# ------------------------------------------------------------------ settings
cfg = json.load(open(os.path.join(ROOT, "settings.json"), encoding="utf-8-sig"))
PCT = (cfg["scoring"]["verdict_strong_pct"], cfg["scoring"]["verdict_med_pct"], cfg["scoring"]["verdict_weak_pct"])
NOM = {
    "SQUEEZE_PEN": -cfg["scoring"]["bbw_squeeze_penalty"],
    "DECEL_PEN": -cfg["indicators"]["MicroCVD"]["decel_penalty"],
    "STALL_PEN": -cfg["indicators"]["MicroCVD"]["decel_penalty"],
    "CVD_DIV_PEN": -cfg["indicators"]["CVD"]["divergence_penalty"],
    "RSI_DIV_PEN": -1,  # literal in Core/ScoringEngine_Calculate_Scoring.vb:194-198 (no settings key)
    "OICVD_CONFIRM": cfg["indicators"]["oi_cvd_cross"]["upgrade_bonus"],
    "OICVD_CONFLICT": -cfg["indicators"]["oi_cvd_cross"]["conflict_penalty"],
    "BURST_CONFIRM": cfg["indicators"]["aggressor_velocity"]["upgrade_bonus"],
    "BURST_CONTRA": -cfg["indicators"]["aggressor_velocity"]["contra_penalty"],
    "P2C_ALIGN": cfg["regime_weights"]["trending"]["alignment_bonus"],
    "P2C_CONFLICT": -cfg["regime_weights"]["trending"]["conflict_penalty"],
    "TS_BONUS": cfg["indicators"]["trend_structure"]["structure_bonus"],
    "SPREAD_PEN": -cfg["scoring"]["spread_wide_penalty"],
    "UPGRADE": 1,  # Pass 2 partial -> upgraded, "+= 1" in Core/ScoringEngine_Calculate_Scoring.vb:478-517 (no settings key)
}

def thresholds(mx):
    return tuple(math.ceil(mx * q - 1e-9) for q in PCT)

def tier_of(score, mx):
    s, m, w = thresholds(mx)
    if score >= s: return "STRONG"
    if score >= m: return "MEDIUM"
    if score >= w: return "WEAK"
    return "BELOW"

# ------------------------------------------------------------------ load
def load_attr(path):
    rows = {}
    repaired = 0
    with open(path, encoding="utf-8") as f:
        rd = csv.reader(f)
        h = next(rd)
        for x in rd:
            if len(x) == len(h) + 1:
                # The Class field "unlogged VPFR label (another label, no verification)" is written unquoted
                # (MediumTierRescore.vb): rejoin fields 12 and 13.
                x = x[:12] + [x[12] + "," + x[13]] + x[14:]
                repaired += 1
            if len(x) != len(h):
                raise SystemExit("attribution row with %d fields: %s" % (len(x), x[0]))
            rows[x[0]] = dict(zip(h, x))
    return rows, repaired

attr_path = os.path.join(CACHE, "rescore-attribution.csv")
rows_path = os.path.join(CACHE, "diagnosis-rows.csv")
attr, n_repaired = load_attr(attr_path)
diag = list(csv.DictReader(open(rows_path, encoding="utf-8")))

def fnum(s):
    try:
        return float(s)
    except (TypeError, ValueError):
        return float("nan")

def inum(s):
    try:
        return int(float(s))
    except (TypeError, ValueError):
        return 0

pop = []
n_noattr = 0
for d in diag:
    a = attr.get(d["Timestamp"])
    if a is None:
        n_noattr += 1
        continue
    r = {}
    r["ts"] = datetime.strptime(d["Timestamp"], "%Y-%m-%d %H:%M:%S")
    r["day"] = d["Day"]; r["half"] = d["Half"]; r["session"] = d["Session"]; r["side"] = d["Side"]; r["tier"] = d["Tier"]
    r["cap"] = d["Cap"]; r["execres"] = d["ExecRes"]; r["price"] = fnum(d["Price"]); r["atr"] = fnum(d["Atr"])
    r["win"] = inum(d["MainWindowMin"])
    for m, evc, occ, rmc in MODES:
        r["ev_" + m] = fnum(d[evc]); r["out_" + m] = inum(d[occ]); r["rmin_" + m] = fnum(d[rmc])
    r["regime"] = d["Regime"]; r["adx"] = fnum(d["ADX"]); r["max"] = inum(d["MaxScore"])
    L, S = "LONG", "SHORT"
    isL = r["side"] == L
    r["raw"] = inum(d["LongScore"] if isL else d["ShortScore"])
    r["raw_opp"] = inum(d["ShortScore"] if isL else d["LongScore"])
    r["eff"] = inum(d["EffectiveLongScore"] if isL else d["EffectiveShortScore"])
    r["eff_opp"] = inum(d["EffectiveShortScore"] if isL else d["EffectiveLongScore"])
    r["pen"] = inum(d["RegimePenalty"])
    r["share"] = r["eff"] / r["max"] if r["max"] > 0 else float("nan")
    r["margin"] = r["eff"] - r["eff_opp"]
    sg = 1.0 if isL else -1.0
    atr = r["atr"]
    px = r["price"]
    r["f_vwap_atr"] = sg * (px - fnum(d["VWAP"])) / atr
    r["f_ema21_atr"] = sg * (px - fnum(d["EMA21"])) / atr
    r["f_roc"] = sg * fnum(d["ROC"])
    rsi = fnum(d["RSI"])
    r["f_rsi"] = rsi if isL else 100.0 - rsi
    hi5, lo5 = fnum(d["LastSwingHigh5m"]), fnum(d["LastSwingLow5m"])
    r["f_swing_ext_atr"] = ((px - lo5) if isL else (hi5 - px)) / atr if (lo5 > 0 and hi5 > 0) else float("nan")
    r["f_room_atr"] = ((hi5 - px) if isL else (px - lo5)) / atr if (lo5 > 0 and hi5 > 0) else float("nan")
    r["f_ttm_atr"] = sg * fnum(d["TTMHistogram"]) / atr
    r["ctx"] = d["VerdictContext"]
    r["hour"] = r["ts"].hour
    r["rregime"] = "R1" if r["ts"] < ATR_STEP else "R2"
    r["match"] = a["MatchSix"] == "1"
    r["vpfr_verified"] = a["VpfrVerified"] == "1"
    r["vpfr_label"] = a["VpfrSignal"]
    r["era"] = a["Era"]
    X, Y = ("_L", "_S") if isL else ("_S", "_L")
    r["pts"] = {}
    r["lean"] = {}
    r["blank"] = set()
    for lb in LABELS:
        px_, py_ = a[lb + X], a[lb + Y]
        if px_ == "" and py_ == "":
            r["blank"].add(lb)
        vx, vy = inum(px_), inum(py_)
        r["pts"][lb] = (vx, vy)
        r["lean"][lb] = vx - vy
    muts = [m for m in a["Mutations"].split(";") if m]
    r["muts"] = muts
    r["mutset"] = set(muts)
    r["xs"] = X[1]; r["ys"] = Y[1]
    pop.append(r)

# ------------------------------------------------------------------ bootstrap core
def pctl(sorted_vals, q):
    if not sorted_vals: return float("nan")
    k = max(1, min(len(sorted_vals), math.ceil(q / 100.0 * len(sorted_vals))))
    return sorted_vals[k - 1]

SEEDC = [0]
def boot(rows, contribs, K, stat):
    """contribs(row) -> list of (cell, value). Day-level resampling. Returns (point, lo, hi, counts)."""
    days = {}
    for r in rows:
        cs = contribs(r)
        if not cs: continue
        i = days.get(r["day"])
        if i is None:
            i = days[r["day"]] = len(days)
        for k, v in cs:
            pass
    D = len(days)
    S = [[0.0] * D for _ in range(K)]
    C = [[0] * D for _ in range(K)]
    for r in rows:
        cs = contribs(r)
        if not cs: continue
        i = days[r["day"]]
        for k, v in cs:
            S[k][i] += v
            C[k][i] += 1
    tS = [sum(s) for s in S]; tC = [sum(c) for c in C]
    point = stat(tS, tC)
    SEEDC[0] += 1
    if D == 0:
        return point, float("nan"), float("nan"), tC
    rng = random.Random(args.seed * 1000 + SEEDC[0])
    rngD = range(D)
    draws = []
    for _ in range(R):
        idx = rng.choices(rngD, k=D)
        bs = [sum(map(S[k].__getitem__, idx)) for k in range(K)]
        bc = [sum(map(C[k].__getitem__, idx)) for k in range(K)]
        v = stat(bs, bc)
        if v == v:
            draws.append(v)
    draws.sort()
    return point, pctl(draws, 2.5), pctl(draws, 97.5), tC

def mean_of(k):
    return lambda s, c: s[k] / c[k] if c[k] > 0 else float("nan")

def diff_of(a, b):
    return lambda s, c: (s[a] / c[a] - s[b] / c[b]) if c[a] > 0 and c[b] > 0 else float("nan")

def f1(x):
    return "n/a" if x != x else ("%+.1f" % x)

def ci(pt, lo, hi):
    return "%s [%s, %s]" % (f1(pt), f1(lo), f1(hi))

def halves(rows):
    return {"FULL": rows, "H1": [r for r in rows if r["half"] == "H1"], "H2": [r for r in rows if r["half"] == "H2"]}

ALL_LABELS = []
def compare(rows, cell_a, cell_b, value, name, context, need_cells=(0, 1), stat=None, K=2, contribs=None):
    """Two-group comparison with halves and the pre-registered label. cell_a/cell_b: predicates."""
    res = {}
    for hn, hr in halves(rows).items():
        if contribs is None:
            def cb(r, ca=cell_a, cbb=cell_b):
                out_ = []
                if ca(r): out_.append((0, value(r)))
                if cbb(r): out_.append((1, value(r)))
                return out_
            res[hn] = boot(hr, cb, K, stat or diff_of(0, 1))
        else:
            res[hn] = boot(hr, contribs, K, stat)
    lab = label(res, need_cells)
    ALL_LABELS.append((context, name, lab, res["FULL"]))
    return res, lab

def readable(r, need):
    return all(r[3][k] >= FLOOR for k in need)

def sig(r, need):
    return readable(r, need) and r[1] == r[1] and (r[1] > 0 or r[2] < 0)

def label(res, need):
    f, h1, h2 = res["FULL"], res["H1"], res["H2"]
    if not readable(f, need): return "NOT READABLE"
    sgn = lambda x: (x > 0) - (x < 0)
    side = lambda r: "d > 0" if r[0] > 0 else "d < 0"
    if sig(h1, need) and sig(h2, need) and sgn(h1[0]) == sgn(h2[0]): return "CONFIRMED (%s)" % side(h1)
    if sig(h1, need) and readable(h2, need) and sgn(h1[0]) == sgn(h2[0]): return "H1 FINDING, H2 SAME SIGN NOT SIGNIFICANT (%s)" % side(h1)
    if sig(h1, need): return "H1 FINDING, H2 CONTRADICTS OR NOT READABLE (%s)" % side(h1)
    if sig(h2, need): return "DISCOVERY ONLY (H2) (%s)" % side(h2)
    return "NO DIFFERENCE SHOWN"

def cmp_row(res, lab, need=(0, 1)):
    f, h1, h2 = res["FULL"], res["H1"], res["H2"]
    nt = lambda r: "/".join(str(r[3][k]) for k in need)
    return "%s (%s) | %s (%s) | %s (%s) | %s" % (ci(*f[:3]), nt(f), ci(*h1[:3]), nt(h1), ci(*h2[:3]), nt(h2), lab)

CMP_HDR = "| FULL d [95 % CI] (n) | H1 d [95 % CI] (n) | H2 d [95 % CI] (n) | Label |"

def cell_stats(rows, mode):
    n = len(rows)
    if n == 0: return "0 | n/a | n/a"
    res = boot(rows, lambda r: [(0, r["ev_" + mode])], 1, mean_of(0))
    succ = 100.0 * sum(1 for r in rows if r["out_" + mode] == 1) / n
    return "%d%s | %.1f | %s" % (n, "" if n >= FLOOR else " (NOT READABLE)", succ, ci(*res[:3]))

def sess_rows(s, rows=None):
    return [r for r in (rows or pop) if r["session"] == s]

# ================================================================== 0. setup and self-checks
p("# medium_tier_diagnosis.py output (MEDIUM-tier diagnosis, session 2)")
p()
p("- Run at (UTC): " + datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S"))
p("- Brief: docs/medium-tier-diagnosis-brief-2026-09-16.md section 3. Rules: this script's header.")
p("- Inputs: `%s` (MD5 %s), `%s` (MD5 %s)." % (os.path.relpath(attr_path, ROOT), md5(attr_path), os.path.relpath(rows_path, ROOT), md5(rows_path)))
p("- Bootstrap: %d resamples of whole UTC trading days, seed %d + call index; readable n >= %d." % (R, args.seed, FLOOR))
p("- Verdict percentages (tracked settings.json version %s): STRONG %.2f, MEDIUM %.2f, WEAK %.2f." % (cfg["version"], *PCT))
p()
p("## 0. Self-checks")
p()
p("| Check | Result |")
p("|---|---|")
p("| Export rows | %d |" % len(diag))
p("| Export rows without an attribution row (must be 0) | %d |" % n_noattr)
p("| Attribution rows repaired (unquoted comma in the Class field) | %d |" % n_repaired)
p("| Joined population rows | %d |" % len(pop))
p("| Attribution InPopulation flag = 1 on joined rows | %d |" % sum(1 for r in pop if attr[r["ts"].strftime("%Y-%m-%d %H:%M:%S")]["InPopulation"] == "1"))
tier_mis = sum(1 for r in pop if tier_of(r["eff"], r["max"]) != r["tier"])
p("| Logged tier = tier of the logged effective score against Ceiling(MaxScore x pct) (mismatches, must be 0) | %d |" % tier_mis)
p("| Rows whose re-score matches all six fields | %d |" % sum(1 for r in pop if r["match"]))
p("| Rows with a verified VPFR profile | %d |" % sum(1 for r in pop if r["vpfr_verified"]))
p("| Rows with MaxScore outside {20, 19, 15} | %d |" % sum(1 for r in pop if r["max"] not in (20, 19, 15)))
p("| Rows with a missing main-window or carried outcome value | %d |" % sum(1 for r in pop if r["ev_main"] != r["ev_main"] or r["ev_C24"] != r["ev_C24"]))
# ledger: attribution points sum to the re-scored raw score on matching rows
led = 0
for r in pop:
    if not r["match"]: continue
    a = attr[r["ts"].strftime("%Y-%m-%d %H:%M:%S")]
    sx = sum(r["pts"][lb][0] for lb in LABELS)
    if sx != r["raw"]: led += 1
p("| Matching rows where the trade side's breakdown points do not sum to the logged raw score (must be 0) | %d |" % led)
era_files = sorted(glob.glob(os.path.join(CACHE, "rescore-eras", "settings-v*.json")))
if era_files:
    keyvals = defaultdict(set)
    for fpath in era_files:
        e = json.load(open(fpath, encoding="utf-8-sig"))
        for path_, getter in [("verdict pcts", lambda e: (e["scoring"]["verdict_strong_pct"], e["scoring"]["verdict_med_pct"], e["scoring"]["verdict_weak_pct"])),
                              ("squeeze", lambda e: e["scoring"]["bbw_squeeze_penalty"]), ("decel", lambda e: e["indicators"]["MicroCVD"]["decel_penalty"]),
                              ("cvd div", lambda e: e["indicators"]["CVD"]["divergence_penalty"]), ("oicvd", lambda e: (e["indicators"]["oi_cvd_cross"]["upgrade_bonus"], e["indicators"]["oi_cvd_cross"]["conflict_penalty"])),
                              ("burst", lambda e: (e["indicators"]["aggressor_velocity"]["upgrade_bonus"], e["indicators"]["aggressor_velocity"]["contra_penalty"])),
                              ("p2c", lambda e: (e["regime_weights"]["trending"]["alignment_bonus"], e["regime_weights"]["trending"]["conflict_penalty"], e["regime_weights"]["range_bound"]["alignment_bonus"], e["regime_weights"]["range_bound"]["conflict_penalty"])),
                              ("ts", lambda e: e["indicators"]["trend_structure"]["structure_bonus"]), ("spread", lambda e: e["scoring"]["spread_wide_penalty"]),
                              ("funding", lambda e: (e["scoring"]["funding_high_penalty"], e["scoring"]["funding_high_boost"], e["scoring"]["funding_low_penalty"], e["indicators"]["funding"]["momentum_amplify"], e["indicators"]["funding"]["momentum_soften"]))]:
            keyvals[path_].add(json.dumps(getter(e)))
    changed = [k for k, v in keyvals.items() if len(v) > 1]
    p("| Era settings files read / magnitude groups that differ between eras (must be none) | %d / %s |" % (len(era_files), ", ".join(changed) if changed else "none"))
p()
p("| Session | Rows | STRONG | MEDIUM | WEAK | H1 rows | H2 rows | Trading days |")
p("|---|---|---|---|---|---|---|---|")
for s in SESSIONS:
    sr = sess_rows(s)
    c = Counter(r["tier"] for r in sr)
    p("| %s | %d | %d | %d | %d | %d | %d | %d |" % (s, len(sr), c["STRONG"], c["MEDIUM"], c["WEAK"], sum(1 for r in sr if r["half"] == "H1"), sum(1 for r in sr if r["half"] == "H2"), len(set(r["day"] for r in sr))))
p()

# Baseline tier gaps (reference for every later section)
p("## 1. Baseline: tier outcomes and the tier gap per session")
p()
for m, *_ in MODES:
    p("### 1.%d %s" % (1 if m == "main" else 2, "main window" if m == "main" else "carried 24 h"))
    p()
    p("| Session | Tier | n | Success % | Net EV [95 % CI] |")
    p("|---|---|---|---|---|")
    for s in SESSIONS:
        for t in TIERS:
            p("| %s | %s | %s |" % (s, t, cell_stats([r for r in sess_rows(s) if r["tier"] == t], m)))
    p()
    p("| Session | Comparison " + CMP_HDR)
    p("|---|---|---|---|---|---|")
    for s in SESSIONS:
        sr = sess_rows(s)
        for a_, b_ in [("MEDIUM", "WEAK"), ("MEDIUM", "STRONG")]:
            res, lab = compare(sr, lambda r, a_=a_: r["tier"] == a_, lambda r, b_=b_: r["tier"] == b_, lambda r, m=m: r["ev_" + m],
                               "%s - %s" % (a_, b_), "1 baseline %s %s" % (m, s))
            p("| %s | %s - %s | %s |" % (s, a_, b_, cmp_row(res, lab)))
    p()

# ================================================================== D-1
p("## 2. D-1: is the score monotone in quality?")
p()
SHARE_BINS = [(0.0, 0.45, "< 0.45"), (0.45, 0.53, "0.45-0.53"), (0.53, 0.60, "0.53-0.60"), (0.60, 0.70, "0.60-0.70"), (0.70, 9.0, ">= 0.70")]
MARGIN_BINS = [(1, 3, "1-2"), (3, 5, "3-4"), (5, 7, "5-6"), (7, 10, "7-9"), (10, 99, ">= 10")]
def slope_stat(s, c):
    n = c[0]
    if n < 3: return float("nan")
    sx, sy, sxy, sxx = s[1], s[2], s[3], s[4]
    den = n * sxx - sx * sx
    return (n * sxy - sx * sy) / den if den > 0 else float("nan")
for m, *_ in MODES:
    for feat, bins, scale, fname in [("share", SHARE_BINS, 10.0, "effective score share of regime max (slope per 0.1)"), ("margin", MARGIN_BINS, 1.0, "effective margin, dominant minus opposite (slope per point)")]:
        p("### D-1 %s, %s" % (fname.split(" (")[0], "main window" if m == "main" else "carried 24 h"))
        p()
        p("| Session | Bin | n | Success % | Net EV [95 % CI] | H1 EV | H2 EV |")
        p("|---|---|---|---|---|---|---|")
        for s in SESSIONS:
            sr = sess_rows(s)
            for lo, hi, nm in bins:
                cell = [r for r in sr if lo <= r[feat] < hi]
                h1 = [r["ev_" + m] for r in cell if r["half"] == "H1"]; h2 = [r["ev_" + m] for r in cell if r["half"] == "H2"]
                p("| %s | %s | %s | %s | %s |" % (s, nm, cell_stats(cell, m), f1(sum(h1) / len(h1)) if h1 else "n/a", f1(sum(h2) / len(h2)) if h2 else "n/a"))
        p()
        p("| Session | Statistic " + CMP_HDR)
        p("|---|---|---|---|---|---|")
        for s in SESSIONS:
            sr = sess_rows(s)
            contribs = lambda r, m=m, feat=feat, scale=scale: [(0, 0.0), (1, r[feat] * scale), (2, r["ev_" + m]), (3, r[feat] * scale * r["ev_" + m]), (4, (r[feat] * scale) ** 2)]
            res = {hn: boot(hr, contribs, 5, slope_stat) for hn, hr in halves(sr).items()}
            lab = label(res, (0,))
            ALL_LABELS.append(("2 D-1 %s %s %s" % (feat, m, s), "OLS slope", lab, res["FULL"]))
            p("| %s | slope of net EV on %s | %s |" % (s, fname, cmp_row(res, lab, (0,))))
        p()

# ================================================================== D-2
p("## 3. D-2: net EV by exact effective score")
p()
for m, *_ in MODES[:1]:
    p("| Session | MaxScore (regime) | Effective score | Tier | n | Success % | Net EV [95 % CI] |")
    p("|---|---|---|---|---|---|---|")
    for s in SESSIONS:
        sr = sess_rows(s)
        for mx, rg in [(20, "TRENDING"), (19, "RANGE_BOUND"), (15, "TRANSITIONAL")]:
            for sc in sorted(set(r["eff"] for r in sr if r["max"] == mx)):
                cell = [r for r in sr if r["max"] == mx and r["eff"] == sc]
                p("| %s | %d (%s) | %d | %s | %s |" % (s, mx, rg, sc, tier_of(sc, mx), cell_stats(cell, m)))
    p()
    p("Boundary comparisons (main window): the lowest integer of the upper tier minus the highest integer of the lower tier.")
    p()
    p("| Session | MaxScore | Comparison " + CMP_HDR)
    p("|---|---|---|---|---|---|---|")
    for s in SESSIONS:
        sr = sess_rows(s)
        for mx in (20, 19, 15):
            st, md, wk = thresholds(mx)
            for up, dn, nm in [(md, md - 1, "MEDIUM floor %d - WEAK top %d" % (md, md - 1)), (st, st - 1, "STRONG floor %d - MEDIUM top %d" % (st, st - 1)), (md, wk, "MEDIUM floor %d - WEAK floor %d" % (md, wk))]:
                sub = [r for r in sr if r["max"] == mx]
                res, lab = compare(sub, lambda r, up=up: r["eff"] == up, lambda r, dn=dn: r["eff"] == dn, lambda r: r["ev_main"], nm, "3 D-2 %s %d" % (s, mx))
                p("| %s | %d | %s | %s |" % (s, mx, nm, cmp_row(res, lab)))
    p()

# ================================================================== D-3
p("## 4. D-3: which votes lift a signal into MEDIUM, and do they help?")
p()
fire_pop = {lb: sum(1 for r in pop if r["pts"][lb] != (0, 0)) for lb in LABELS}
p("### 4.1 Vote composition by tier: share of rows where the vote agrees / opposes the trade side (%)")
p()
p("| Vote | " + " | ".join("%s %s agree / oppose" % (s, t) for s in SESSIONS for t in TIERS) + " |")
p("|---|" + "---|" * (len(SESSIONS) * len(TIERS)))
for lb in LABELS:
    cells = []
    for s in SESSIONS:
        for t in TIERS:
            c = [r for r in pop if r["session"] == s and r["tier"] == t]
            ag = 100.0 * sum(1 for r in c if r["lean"][lb] > 0) / max(1, len(c))
            op = 100.0 * sum(1 for r in c if r["lean"][lb] < 0) / max(1, len(c))
            cells.append("%.0f / %.0f" % (ag, op))
    p("| %s | %s |" % (lb, " | ".join(cells)))
p()
p("- Mean net lean of the trade side, summed over votes, equals the logged effective margin plus the regime penalty on matching rows; see section 0 for the ledger.")
p()
p("### 4.2 Per vote: net EV when the vote agrees, opposes or is absent (pooled over tiers)")
p()
d3_results = {}
for m, *_ in MODES:
    p("#### %s" % ("main window" if m == "main" else "carried 24 h"))
    p()
    p("| Session | Vote | n agree / oppose / absent | EV agree | EV oppose | EV absent | Comparison " + CMP_HDR)
    p("|---|---|---|---|---|---|---|---|---|---|---|")
    for s in SESSIONS:
        sr = sess_rows(s)
        for lb in LABELS:
            if fire_pop[lb] == 0: continue
            na = sum(1 for r in sr if r["lean"][lb] > 0); no = sum(1 for r in sr if r["lean"][lb] < 0); nz = len(sr) - na - no
            mean = lambda pred: (lambda v: f1(sum(v) / len(v)) if v else "n/a")([r["ev_" + m] for r in sr if pred(r)])
            for nm, pa, pb in [("agree - oppose", lambda r, lb=lb: r["lean"][lb] > 0, lambda r, lb=lb: r["lean"][lb] < 0),
                               ("agree - absent", lambda r, lb=lb: r["lean"][lb] > 0, lambda r, lb=lb: r["lean"][lb] == 0)]:
                res, lab = compare(sr, pa, pb, lambda r, m=m: r["ev_" + m], nm, "4 D-3 %s %s %s" % (m, s, lb))
                d3_results[(m, s, lb, nm)] = (res, lab)
                p("| %s | %s | %d / %d / %d | %s | %s | %s | %s | %s |" % (s, lb, na, no, nz, mean(lambda r, lb=lb: r["lean"][lb] > 0), mean(lambda r, lb=lb: r["lean"][lb] < 0), mean(lambda r, lb=lb: r["lean"][lb] == 0), nm, cmp_row(res, lab)))
    p()

def within_tier_contribs(lb, m):
    def cb(r):
        t = TIERS.index(r["tier"])
        if r["lean"][lb] > 0: return [(2 * t, r["ev_" + m])]
        if r["lean"][lb] < 0: return [(2 * t + 1, r["ev_" + m])]
        return []
    return cb

def within_tier_stat(s, c):
    num = 0.0; w = 0
    for t in range(3):
        if c[2 * t] > 0 and c[2 * t + 1] > 0:
            wt = c[2 * t] + c[2 * t + 1]
            num += wt * (s[2 * t] / c[2 * t] - s[2 * t + 1] / c[2 * t + 1]); w += wt
    return num / w if w > 0 else float("nan")

p("### 4.3 Per vote: agree - oppose WITHIN tier (main window; weights = agree + oppose rows per tier)")
p()
p("| Session | Vote | Comparison " + CMP_HDR)
p("|---|---|---|---|---|---|---|")
for s in SESSIONS:
    sr = sess_rows(s)
    for lb in LABELS:
        if fire_pop[lb] == 0: continue
        res = {hn: boot(hr, within_tier_contribs(lb, "main"), 6, within_tier_stat) for hn, hr in halves(sr).items()}
        # readability: total agree and total oppose rows
        for hn in res:
            f = res[hn]; cnt = f[3]
            res[hn] = (f[0], f[1], f[2], [cnt[0] + cnt[2] + cnt[4], cnt[1] + cnt[3] + cnt[5]])
        lab = label(res, (0, 1))
        ALL_LABELS.append(("4.3 D-3 within-tier main %s %s" % (s, lb), "agree - oppose within tier", lab, res["FULL"]))
        p("| %s | %s | agree - oppose, within tier | %s |" % (s, lb, cmp_row(res, lab)))
p()

p("### 4.5 Which votes lift a row into MEDIUM (main window)")
p()
p("- Lifted: a MEDIUM row whose effective score, minus that vote's positive points on the trade side, falls below the MEDIUM floor. A row can be lifted by several votes (explanation sets, not first match).")
p()
p("| Session | Vote | MEDIUM rows lifted | % of MEDIUM | EV lifted | EV other MEDIUM | Comparison " + CMP_HDR)
p("|---|---|---|---|---|---|---|---|---|---|---|")
for s in SESSIONS:
    med = [r for r in sess_rows(s) if r["tier"] == "MEDIUM"]
    for lb in LABELS:
        lift = lambda r, lb=lb: r["pts"][lb][0] > 0 and tier_of(r["eff"] - r["pts"][lb][0], r["max"]) != "MEDIUM"
        nl = [r["ev_main"] for r in med if lift(r)]
        if not nl: continue
        no = [r["ev_main"] for r in med if not lift(r)]
        res, lab = compare(med, lift, lambda r, lift=lift: not lift(r), lambda r: r["ev_main"], "lifted - other MEDIUM", "4.5 D-3 lift %s %s" % (s, lb))
        p("| %s | %s | %d | %.1f | %s | %s | lifted - other MEDIUM | %s |" % (s, lb, len(nl), 100.0 * len(nl) / len(med), f1(sum(nl) / len(nl)), f1(sum(no) / len(no)) if no else "n/a", cmp_row(res, lab)))
p()
p("| Session | MEDIUM rows lifted by 0 / 1 / 2 / 3+ votes | Most common lift sets (top 5) |")
p("|---|---|---|")
for s in SESSIONS:
    med = [r for r in sess_rows(s) if r["tier"] == "MEDIUM"]
    sets = Counter(); nset = Counter()
    for r in med:
        ls_ = tuple(lb for lb in LABELS if r["pts"][lb][0] > 0 and tier_of(r["eff"] - r["pts"][lb][0], r["max"]) != "MEDIUM")
        nset[min(3, len(ls_))] += 1; sets[ls_] += 1
    p("| %s | %d / %d / %d / %d | %s |" % (s, nset[0], nset[1], nset[2], nset[3], "; ".join("{%s} %d" % (", ".join(k) or "none", v) for k, v in sets.most_common(5))))
p()

# ---- VPFR deep dive
p("### 4.4 The VPFR score vote (priority): verified VPFR profiles only")
p()
vp = [r for r in pop if r["vpfr_verified"]]
p("- Rows: %d verified of %d. Vote geometry (`Core/ScoringEngine_Calculate_Scoring.vb:457-458`, label producer `Core/Indicators_Structure.vb:171-185`): NEAR_HVN_SUPPORT (price just below the POC) and IN_LVN_BULL vote LONG; NEAR_HVN_RESIST (price at or just above the POC) and IN_LVN_BEAR vote SHORT." % (len(vp), len(pop)))
def vpfr_geom_ok(r):
    lp, sp = (r["pts"]["VPFR"] if r["side"] == "LONG" else r["pts"]["VPFR"][::-1])
    if r["vpfr_label"] == "NEUTRAL": return lp == 0 and sp == 0
    exp_long = r["vpfr_label"] in ("NEAR_HVN_SUPPORT", "IN_LVN_BULL")
    return (lp == 1 and sp == 0) if exp_long else (lp == 0 and sp == 1)
p("- Verified rows where the recomputed label and the breakdown points disagree (must be 0): %d." % sum(1 for r in vp if not vpfr_geom_ok(r)))
p()
nh = [r for r in vp if r["vpfr_label"] in ("NEAR_HVN_SUPPORT", "NEAR_HVN_RESIST")]
p("- Reproduces session 1's descriptive share (`docs/medium-tier-bug-hunt-2026-09-16.md` section 5): on verified population rows with a NEAR_HVN label, the vote opposes the verdict side on %d of %d (%.1f %%)." % (sum(1 for r in nh if r["lean"]["VPFR"] < 0), len(nh), 100.0 * sum(1 for r in nh if r["lean"]["VPFR"] < 0) / max(1, len(nh))))
p()
p("| Session | Label | Side | Vote vs trade | n | Success % | Net EV main [95 % CI] | Net EV carried [95 % CI] |")
p("|---|---|---|---|---|---|---|---|")
for s in SESSIONS:
    for lab_ in ["NEAR_HVN_SUPPORT", "NEAR_HVN_RESIST", "IN_LVN_BULL", "IN_LVN_BEAR", "NEUTRAL"]:
        for side in ["LONG", "SHORT"]:
            c = [r for r in vp if r["session"] == s and r["vpfr_label"] == lab_ and r["side"] == side]
            if not c: continue
            rel = "absent" if lab_ == "NEUTRAL" else ("agrees" if (lab_ in ("NEAR_HVN_SUPPORT", "IN_LVN_BULL")) == (side == "LONG") else "opposes")
            cm = boot(c, lambda r: [(0, r["ev_C24"])], 1, mean_of(0))
            p("| %s | %s | %s | %s | %s | %s |" % (s, lab_, side, rel, cell_stats(c, "main"), ci(*cm[:3])))
p()
p("| Session | Family | Window | Comparison " + CMP_HDR)
p("|---|---|---|---|---|---|---|---|")
vpfr_answers = {}
for s in SESSIONS:
    sr = [r for r in vp if r["session"] == s]
    for fam, labs in [("NEAR_HVN", ("NEAR_HVN_SUPPORT", "NEAR_HVN_RESIST")), ("IN_LVN", ("IN_LVN_BULL", "IN_LVN_BEAR")), ("ALL labels", ("NEAR_HVN_SUPPORT", "NEAR_HVN_RESIST", "IN_LVN_BULL", "IN_LVN_BEAR"))]:
        fr = [r for r in sr if r["vpfr_label"] in labs]
        for m, *_ in MODES:
            res, lab = compare(fr, lambda r: r["lean"]["VPFR"] > 0, lambda r: r["lean"]["VPFR"] < 0, lambda r, m=m: r["ev_" + m], "agree - oppose", "4.4 VPFR %s %s %s" % (s, fam, m))
            vpfr_answers[(s, fam, m)] = (res, lab)
            p("| %s | %s | %s | agree - oppose | %s |" % (s, fam, m, cmp_row(res, lab)))
        # within tier
        res = {hn: boot(hr, within_tier_contribs("VPFR", "main"), 6, within_tier_stat) for hn, hr in halves(fr).items()}
        for hn in res:
            f = res[hn]; cnt = f[3]
            res[hn] = (f[0], f[1], f[2], [cnt[0] + cnt[2] + cnt[4], cnt[1] + cnt[3] + cnt[5]])
        lab = label(res, (0, 1))
        ALL_LABELS.append(("4.4 VPFR within-tier %s %s" % (s, fam), "agree - oppose within tier", lab, res["FULL"]))
        vpfr_answers[(s, fam, "within")] = (res, lab)
        p("| %s | %s | main | agree - oppose, within tier | %s |" % (s, fam, cmp_row(res, lab)))
        # agree vs no label (NEUTRAL rows of the same session)
        neu = [r for r in sr if r["vpfr_label"] == "NEUTRAL"]
        res, lab = compare(fr + neu, lambda r, labs=labs: r["vpfr_label"] in labs and r["lean"]["VPFR"] > 0, lambda r: r["vpfr_label"] == "NEUTRAL", lambda r: r["ev_main"], "agree - NEUTRAL", "4.4 VPFR %s %s agree-neutral" % (s, fam))
        vpfr_answers[(s, fam, "agree-neutral")] = (res, lab)
        p("| %s | %s | main | agree - NEUTRAL label (no vote) | %s |" % (s, fam, cmp_row(res, lab)))
        res, lab = compare(fr + neu, lambda r, labs=labs: r["vpfr_label"] in labs and r["lean"]["VPFR"] < 0, lambda r: r["vpfr_label"] == "NEUTRAL", lambda r: r["ev_main"], "oppose - NEUTRAL", "4.4 VPFR %s %s oppose-neutral" % (s, fam))
        p("| %s | %s | main | oppose - NEUTRAL label (no vote) | %s |" % (s, fam, cmp_row(res, lab)))
        # side-specific (long rows and short rows) to rule out a side artefact
        for side in ("LONG", "SHORT"):
            sd = [r for r in fr if r["side"] == side]
            res, lab = compare(sd, lambda r: r["lean"]["VPFR"] > 0, lambda r: r["lean"]["VPFR"] < 0, lambda r: r["ev_main"], "agree - oppose", "4.4 VPFR %s %s %s-only" % (s, fam, side))
            p("| %s | %s | main | agree - oppose, %s trades only | %s |" % (s, fam, side, cmp_row(res, lab)))
p()
p("#### 4.4.1 Tier lift by the VPFR vote")
p()
p("| Session | Rows whose tier falls one step without the agreeing VPFR vote | ... of which MEDIUM -> WEAK | ... STRONG -> MEDIUM | ... WEAK -> below WEAK | Rows whose tier rises one step without the opposing VPFR point (no vote on the trade side, vote on the other side does not change the trade side) |")
p("|---|---|---|---|---|---|")
for s in SESSIONS:
    sr = sess_rows(s)
    lifted = [r for r in sr if r["pts"]["VPFR"][0] > 0 and tier_of(r["eff"] - r["pts"]["VPFR"][0], r["max"]) != r["tier"]]
    cc = Counter((r["tier"], tier_of(r["eff"] - 1, r["max"])) for r in lifted)
    p("| %s | %d | %d | %d | %d | n/a (a vote on the other side scores the other side only) |" % (s, len(lifted), cc[("MEDIUM", "WEAK")], cc[("STRONG", "MEDIUM")], cc[("WEAK", "BELOW")]))
p()

# ================================================================== D-4
p("## 5. D-4: mutations that cross a tier boundary")
p()
# applied delta on the trade side, per mutation family
def applied(r, fam):
    X = r["xs"]
    ms = r["mutset"]
    if fam == "SQUEEZE_PEN":
        return r["pts"]["BBW_TTM"][0] if "SQUEEZE_PEN" in ms else 0
    if fam in ("DECEL_PEN", "STALL_PEN"):
        return r["pts"]["MICROCVD"][0] if (fam + "_" + X) in ms else 0
    if fam == "CVD_DIV_PEN":
        return r["pts"]["CVD"][0] if ("CVD_DIV_PEN_" + X) in ms else 0
    if fam == "SPREAD_PEN":
        return r["pts"]["SPREAD"][0] if ("SPREAD_PEN_" + X) in ms else 0
    if fam == "P2C_ALIGN":
        return r["pts"]["REGIME_ALIGN"][0] if ("P2C_ALIGN_" + X) in ms else 0
    if fam == "P2C_CONFLICT":
        return r["pts"]["REGIME_ALIGN"][0] if ("P2C_CONFLICT_" + X) in ms else 0
    if fam == "TS_BONUS":
        return r["pts"]["TREND_STRUCTURE"][0] if ("TS_BONUS_" + X) in ms else 0
    if fam == "FUNDING_STEP3_3B":
        return r["pts"]["FUNDING"][0]
    if fam in ("RSI_DIV_PEN", "OICVD_CONFIRM", "OICVD_CONFLICT", "BURST_CONFIRM", "BURST_CONTRA"):
        return NOM[fam] if (fam + "_" + X) in ms else 0
    if fam == "PASS2_UPGRADES":
        return sum(1 for mm in ms if mm.endswith("_UPGRADE_" + X))
    if fam == "TRANSITIONAL_ADX_PENALTY":
        return -r["pen"]
    raise KeyError(fam)

MUT_FAMS = [("SQUEEZE_PEN", "BBW squeeze penalty, both sides", "label points (exclusive with the TTM vote)"),
            ("DECEL_PEN", "MicroCVD decel penalty", "label points (exclusive with the ACCEL vote)"),
            ("STALL_PEN", "MicroCVD stall penalty", "label points (FLAT: no vote)"),
            ("CVD_DIV_PEN", "CVD divergence penalty", "label points (divergence sign excludes the same-side vote)"),
            ("RSI_DIV_PEN", "RSI divergence penalty", "nominal -1 (label also carries the RSI vote)"),
            ("P2C_ALIGN", "Pass 2c alignment bonus", "label points"),
            ("P2C_CONFLICT", "Pass 2c conflict penalty", "label points"),
            ("OICVD_CONFIRM", "Pass 2b OI x CVD bonus", "nominal (label also carries the OI vote)"),
            ("OICVD_CONFLICT", "Pass 2b OI x CVD penalty", "nominal (label also carries the OI vote)"),
            ("BURST_CONFIRM", "aggressor-velocity upgrade", "nominal (label also carries the TFI vote)"),
            ("BURST_CONTRA", "aggressor-velocity contra penalty", "nominal (label also carries the TFI vote)"),
            ("SPREAD_PEN", "spread WIDE penalty", "label points"),
            ("TS_BONUS", "trend structure bonus", "label points"),
            ("FUNDING_STEP3_3B", "funding Step 3 + 3b modifiers", "label points (the label carries only Step 3 and 3b)"),
            ("PASS2_UPGRADES", "Pass 2 partial upgrades (ROC, RSI, VWAP, OI, Donchian, Volume, OBV)", "+1 per upgrade flag"),
            ("TRANSITIONAL_ADX_PENALTY", "TRANSITIONAL ADX penalty (Step 4; the census)", "logged RegimePenalty")]
LIQ_NOTE = "Liquidation penalty: never fired (finding L-1 of docs/medium-tier-bug-hunt-2026-09-16.md): 0 rows."
p("- " + LIQ_NOTE)
p("- OFI momentum confirm and suppress: disabled in every era (`docs/medium-tier-bug-hunt-2026-09-16.md` section R.4 row 7): 0 rows.")
p()
p("| Session | Mutation | Applied delta from | Rows touched on the trade side | Crossed up into tier (from -> to: n) | Crossed down into tier (from -> to: n) |")
p("|---|---|---|---|---|---|")
cross = {}
for s in SESSIONS:
    sr = sess_rows(s)
    for fam, nm, how in MUT_FAMS:
        touched = [r for r in sr if applied(r, fam) != 0]
        ups, downs = Counter(), Counter()
        for r in touched:
            a_ = applied(r, fam)
            cf = tier_of(r["eff"] - a_, r["max"])
            r.setdefault("cf", {})[fam] = cf
            if cf != r["tier"]:
                (ups if a_ > 0 else downs)[(cf, r["tier"])] += 1
        cross[(s, fam)] = touched
        fmt = lambda cc: "; ".join("%s -> %s: %d" % (k[0], k[1], v) for k, v in sorted(cc.items())) or "0"
        p("| %s | %s | %s | %d | %s | %s |" % (s, nm, how, len(touched), fmt(ups), fmt(downs)))
p()
p("Comparisons (main window). Ka: crossed rows vs untouched rows of the landing tier. Kb: crossed rows vs untouched rows of the origin tier. Only crossings with n >= 100 are labelled; the rest are NOT READABLE by construction.")
p()
p("| Session | Mutation | Crossing | Comparison " + CMP_HDR)
p("|---|---|---|---|---|---|---|---|")
for s in SESSIONS:
    sr = sess_rows(s)
    for fam, nm, how in MUT_FAMS:
        crossed = Counter()
        for r in cross[(s, fam)]:
            cf = r["cf"][fam]
            if cf != r["tier"]: crossed[(cf, r["tier"])] += 1
        for (frm, to), n in sorted(crossed.items()):
            if frm == "BELOW": frm_ok = False
            else: frm_ok = True
            isx = lambda r, fam=fam, frm=frm, to=to: applied(r, fam) != 0 and r["cf"][fam] == frm and r["tier"] == to
            untouched = lambda r, fam=fam: applied(r, fam) == 0
            res, lab = compare(sr, isx, lambda r, to=to, untouched=untouched: untouched(r) and r["tier"] == to, lambda r: r["ev_main"], "Ka", "5 D-4 %s %s %s->%s" % (s, fam, frm, to))
            p("| %s | %s | %s -> %s | Ka crossed - untouched %s | %s |" % (s, fam, frm, to, to, cmp_row(res, lab)))
            if frm_ok:
                res, lab = compare(sr, isx, lambda r, frm=frm, untouched=untouched: untouched(r) and r["tier"] == frm, lambda r: r["ev_main"], "Kb", "5 D-4 %s %s %s->%s" % (s, fam, frm, to))
                p("| %s | %s | %s -> %s | Kb crossed - untouched %s | %s |" % (s, fam, frm, to, frm, cmp_row(res, lab)))
p()

# ================================================================== D-5
p("## 6. D-5: clamps and caps by tier")
p()
p("- Method: a clamp at 0 or a cap at regime max binds when the applied points are smaller in magnitude than the nominal magnitude. Exact only where the label carries that mutation alone (squeeze, decel, stall, CVD divergence, spread, Pass 2c, trend structure, funding). The funding nominal comes from the breakdown note text (`STEP3:` / `STEP3b:` flags).")
p()
def fund_nominal(r, side):
    tot = 0
    for mm in r["muts"]:
        if mm.startswith("STEP3"):
            for val, sd in re.findall(r"([+-]\d+)\[([LS])\]", mm):
                if sd == side: tot += int(val)
    return tot
def binds(r, side_idx):
    """Return list of binding kinds on the trade side (side_idx 0) or the other side (1)."""
    sd = r["xs"] if side_idx == 0 else r["ys"]
    ms = r["mutset"]; b = []
    pts = lambda lb: r["pts"][lb][side_idx]
    if "SQUEEZE_PEN" in ms and pts("BBW_TTM") > NOM["SQUEEZE_PEN"]: b.append("squeeze clamp")
    if ("DECEL_PEN_" + sd) in ms and pts("MICROCVD") > NOM["DECEL_PEN"]: b.append("decel clamp")
    if ("STALL_PEN_" + sd) in ms and pts("MICROCVD") > NOM["STALL_PEN"]: b.append("stall clamp")
    if ("CVD_DIV_PEN_" + sd) in ms and pts("CVD") > NOM["CVD_DIV_PEN"]: b.append("CVD divergence clamp")
    if ("SPREAD_PEN_" + sd) in ms and pts("SPREAD") > NOM["SPREAD_PEN"]: b.append("spread clamp")
    if ("P2C_CONFLICT_" + sd) in ms and pts("REGIME_ALIGN") > NOM["P2C_CONFLICT"]: b.append("Pass 2c conflict clamp")
    if ("P2C_ALIGN_" + sd) in ms and pts("REGIME_ALIGN") < NOM["P2C_ALIGN"]: b.append("Pass 2c align cap")
    if ("TS_BONUS_" + sd) in ms and pts("TREND_STRUCTURE") < NOM["TS_BONUS"]: b.append("trend structure cap")
    fn = fund_nominal(r, sd)
    if fn != pts("FUNDING"): b.append("funding clamp or cap")
    return b
fund_bad = 0
for a in attr.values():
    if a["MatchSix"] != "1": continue
    for sd in "LS":
        nom = 0
        for mm in a["Mutations"].split(";"):
            if mm.startswith("STEP3"):
                for val, s2 in re.findall(r"([+-]\d+)\[([LS])\]", mm):
                    if s2 == sd: nom += int(val)
        if nom != inum(a["FUNDING_" + sd]) and inum(a["LongScore" if sd == "L" else "ShortScore"]) > 1: fund_bad += 1
p("- Parser check: matching trading-week sides where the funding points differ from the note's nominal AND the final raw score is above 1 (a clamp at 0 plus a Step 3b soften cannot explain these; must be 0): %d." % fund_bad)
p()
p("| Session | Tier | Rows | Trade side: rows with a binding clamp or cap (%) | Other side: rows with a binding clamp or cap (%) | Trade-side raw score = regime max (a cap could bind) | Binding kinds, trade side | Binding kinds, other side |")
p("|---|---|---|---|---|---|---|---|")
for s in SESSIONS:
    for t in TIERS:
        c = [r for r in pop if r["session"] == s and r["tier"] == t]
        k0, k1 = Counter(), Counter()
        n0 = n1 = 0
        for r in c:
            b0 = binds(r, 0); b1 = binds(r, 1)
            if b0: n0 += 1
            if b1: n1 += 1
            k0.update(b0); k1.update(b1)
        p("| %s | %s | %d | %d (%.1f) | %d (%.1f) | %d | %s | %s |" % (s, t, len(c), n0, 100.0 * n0 / max(1, len(c)), n1, 100.0 * n1 / max(1, len(c)), sum(1 for r in c if r["raw"] >= r["max"]),
            "; ".join("%s %d" % kv for kv in k0.most_common()) or "none", "; ".join("%s %d" % kv for kv in k1.most_common()) or "none"))
p()

# ================================================================== D-6
p("## 7. D-6: dead and rare votes, and the reachable score")
p()
allrows = list(attr.values())
tw_sessions = defaultdict(list)
for a in allrows:
    tw_sessions[a["Session"]].append(a)
p("### 7.1 Fire rate per vote (either side non-zero)")
p()
p("| Vote | Population, all sessions % | " + " | ".join("%s all trading-week rows %%" % s for s in SESSIONS) + " |")
p("|---|---|" + "---|" * len(SESSIONS))
for lb in LABELS:
    cells = []
    for s in SESSIONS:
        rs = tw_sessions[s]
        n = sum(1 for a in rs if inum(a[lb + "_L"]) != 0 or inum(a[lb + "_S"]) != 0)
        cells.append("%.2f" % (100.0 * n / max(1, len(rs))))
    p("| %s | %.2f | %s |" % (lb, 100.0 * fire_pop[lb] / len(pop), " | ".join(cells)))
p()
p("- All trading-week rows: %d (the re-score's rows, NO TRADE kept; their scores are the re-scored scores)." % len(allrows))
p()
p("### 7.2 Reachable score: dominant effective score over all trading-week rows")
p()
p("| Session | MaxScore | Rows | WEAK / MEDIUM / STRONG floors | p50 | p90 | p99 | Max observed | Share >= WEAK % | Share >= MEDIUM % | Share >= STRONG % | Max observed raw (one side) |")
p("|---|---|---|---|---|---|---|---|---|---|---|---|")
for s in SESSIONS:
    for mx in (20, 19, 15):
        rs = [a for a in tw_sessions[s] if inum(a["MaxScore"]) == mx]
        if not rs: continue
        dom = sorted(max(inum(a["EffectiveLongScore"]), inum(a["EffectiveShortScore"])) for a in rs)
        st, md, wk = thresholds(mx)
        p("| %s | %d | %d | %d / %d / %d | %d | %d | %d | %d | %.1f | %.1f | %.2f | %d |" % (s, mx, len(rs), wk, md, st, pctl(dom, 50), pctl(dom, 90), pctl(dom, 99), dom[-1],
            100.0 * sum(1 for x in dom if x >= wk) / len(dom), 100.0 * sum(1 for x in dom if x >= md) / len(dom), 100.0 * sum(1 for x in dom if x >= st) / len(dom),
            max(max(inum(a["LongScore"]), inum(a["ShortScore"])) for a in rs)))
p()
# max simultaneous positive labels observed
p("### 7.3 Votes that can add a point but never or rarely do (population rows)")
p()
p("| Vote | Rows with a positive point on the trade side | % |")
p("|---|---|---|")
for lb in LABELS:
    n = sum(1 for r in pop if r["pts"][lb][0] > 0)
    p("| %s | %d | %.2f |" % (lb, n, 100.0 * n / len(pop)))
p()

# Extension terciles per session, cut on H1 rows (used by D-7 strata, D-8 and the cause sets)
TERC_CUTS = {}
for s in SESSIONS:
    for fk in ("f_vwap_atr", "f_rsi", "f_ema21_atr"):
        h1v = sorted(r[fk] for r in sess_rows(s) if r["half"] == "H1" and r[fk] == r[fk])
        c1, c2 = pctl(h1v, 100 / 3.0), pctl(h1v, 200 / 3.0)
        TERC_CUTS[(s, fk)] = (c1, c2)
        for r in sess_rows(s):
            r["terc_" + fk] = "nan" if r[fk] != r[fk] else ("T1" if r[fk] <= c1 else ("T2" if r[fk] <= c2 else "T3"))

# ================================================================== D-7
p("## 8. D-7: is MEDIUM just a worse mix?")
p()
def hour_bucket(r):
    h = r["hour"]
    if r["session"] == "NY": return "13-15" if h <= 15 else ("16-19" if h <= 19 else "20-23")
    if r["session"] == "LONDON": return "08-09" if h <= 9 else ("10-11" if h <= 11 else "12")
    return "00-02" if h <= 2 else ("03-05" if h <= 5 else "06-07")
DIMS = [("regime", lambda r: r["regime"]), ("hour bucket", hour_bucket), ("ATR regime", lambda r: r["rregime"]), ("side", lambda r: r["side"]), ("target type", lambda r: r["cap"]), ("ExecResolution", lambda r: r["execres"])]
p("### 8.1 Composition per tier (% of the tier's rows)")
p()
p("| Session | Dimension | Value | STRONG % | MEDIUM % | WEAK % |")
p("|---|---|---|---|---|---|")
for s in SESSIONS:
    sr = sess_rows(s)
    for dn, fn in DIMS:
        vals = sorted(set(fn(r) for r in sr))
        for v in vals:
            cells = []
            for t in TIERS:
                c = [r for r in sr if r["tier"] == t]
                cells.append("%.1f" % (100.0 * sum(1 for r in c if fn(r) == v) / max(1, len(c))))
            p("| %s | %s | %s | %s |" % (s, dn, v, " | ".join(cells)))
p()
def rw_run(sr, strat, name, ctx):
    keys = sorted(set(strat(r) for r in sr))
    K = len(keys)
    kidx = {k: i for i, k in enumerate(keys)}
    def cb(r):
        if r["tier"] == "MEDIUM": return [(kidx[strat(r)], r["ev_main"])]
        if r["tier"] == "WEAK": return [(K + kidx[strat(r)], r["ev_main"])]
        return []
    def stat(s, c):
        cov = [i for i in range(K) if c[i] > 0 and c[K + i] > 0]
        wn = sum(c[K + i] for i in cov)
        if wn == 0: return float("nan")
        med = sum(c[K + i] / wn * s[i] / c[i] for i in cov)
        wk = sum(s[K + i] for i in cov) / wn
        return med - wk
    res = {}
    for hn, hr in halves(sr).items():
        pt, lo, hi, cnt = boot(hr, cb, 2 * K, stat)
        res[hn] = (pt, lo, hi, [sum(cnt[:K]), sum(cnt[K:])])
    lab = label(res, (0, 1))
    ALL_LABELS.append((ctx, name, lab, res["FULL"]))
    return res, lab, keys
p("### 8.2 MEDIUM re-weighted to WEAK's mix (main window, d = MEDIUM - WEAK)")
p()
p("| Session | Strata | Strata count | WEAK rows in covered strata % | Raw d " + CMP_HDR.replace("| FULL d", "| Re-weighted FULL d"))
p("|---|---|---|---|---|---|---|---|---|")
STRATA = [("regime x side x ATR regime x target type", lambda r: (r["regime"], r["side"], r["rregime"], r["cap"])),
          ("regime x hour bucket x side", lambda r: (r["regime"], hour_bucket(r), r["side"])),
          ("regime x side x ATR regime x target type x ExecResolution", lambda r: (r["regime"], r["side"], r["rregime"], r["cap"], r["execres"])),
          ("VWAP-extension tercile x side", lambda r: (r["terc_f_vwap_atr"], r["side"])),
          ("RSI tercile x EMA21-extension tercile x side", lambda r: (r["terc_f_rsi"], r["terc_f_ema21_atr"], r["side"]))]
for s in SESSIONS:
    sr = sess_rows(s)
    rawd = boot(sr, lambda r: [(0, r["ev_main"])] if r["tier"] == "MEDIUM" else ([(1, r["ev_main"])] if r["tier"] == "WEAK" else []), 2, diff_of(0, 1))
    for nm, fn in STRATA:
        res, lab, keys = rw_run(sr, fn, "MEDIUM reweighted - WEAK (%s)" % nm, "8 D-7 %s %s" % (s, nm))
        medk = set(fn(r) for r in sr if r["tier"] == "MEDIUM")
        wk = [r for r in sr if r["tier"] == "WEAK"]
        covw = 100.0 * sum(1 for r in wk if fn(r) in medk) / max(1, len(wk))
        p("| %s | %s | %d | %.1f | %s | %s |" % (s, nm, len(keys), covw, ci(*rawd[:3]), cmp_row(res, lab)))
p()

# ================================================================== D-8
p("## 9. D-8: is MEDIUM a late entry?")
p()
FEATS = [("f_vwap_atr", "distance from VWAP in ATR, signed to the trade side"), ("f_ema21_atr", "distance from EMA21 in ATR, signed"), ("f_roc", "ROC, signed"),
         ("f_rsi", "RSI toward the trade side (100 - RSI for shorts)"), ("f_swing_ext_atr", "extension from the opposite 5m swing extreme in ATR"),
         ("f_room_atr", "room to the same-side 5m swing extreme in ATR"), ("f_ttm_atr", "TTM histogram in ATR, signed")]
p("### 9.1 Medians at entry by tier")
p()
p("| Session | Feature | STRONG median | MEDIUM median | WEAK median | MEDIUM - WEAK mean d " + CMP_HDR)
p("|---|---|---|---|---|---|---|---|---|---|")
for s in SESSIONS:
    sr = [r for r in sess_rows(s)]
    for fk, fname in FEATS:
        meds = []
        for t in TIERS:
            v = sorted(r[fk] for r in sr if r["tier"] == t and r[fk] == r[fk])
            meds.append("%.2f" % pctl(v, 50) if v else "n/a")
        ok = [r for r in sr if r[fk] == r[fk] and abs(r[fk]) < 1e6]
        res, lab = compare(ok, lambda r: r["tier"] == "MEDIUM", lambda r: r["tier"] == "WEAK", lambda r, fk=fk: r[fk], "MEDIUM - WEAK mean " + fk, "9.1 D-8 %s %s" % (s, fk))
        p("| %s | %s | %s | MEDIUM - WEAK | %s |" % (s, fname, " | ".join(meds), cmp_row(res, lab)))
p()
p("### 9.2 Does extension predict outcome? Terciles cut on the session's H1 rows (main window)")
p()
p("| Session | Feature | H1 cut points | Top tercile MEDIUM % / WEAK % | EV bottom / middle / top | Comparison " + CMP_HDR)
p("|---|---|---|---|---|---|---|---|---|---|")
d8_terc = {}
for s in SESSIONS:
    sr = sess_rows(s)
    for fk, fname in FEATS:
        ok = [r for r in sr if r[fk] == r[fk]]
        h1v = sorted(r[fk] for r in ok if r["half"] == "H1")
        if len(h1v) < 3: continue
        c1, c2 = pctl(h1v, 100 / 3.0), pctl(h1v, 200 / 3.0)
        terc = lambda r, c1=c1, c2=c2, fk=fk: 0 if r[fk] <= c1 else (1 if r[fk] <= c2 else 2)
        med = [r for r in ok if r["tier"] == "MEDIUM"]; wk = [r for r in ok if r["tier"] == "WEAK"]
        tm = 100.0 * sum(1 for r in med if terc(r) == 2) / max(1, len(med)); tw = 100.0 * sum(1 for r in wk if terc(r) == 2) / max(1, len(wk))
        evs = []
        for k in range(3):
            v = [r["ev_main"] for r in ok if terc(r) == k]
            evs.append(f1(sum(v) / len(v)) if v else "n/a")
        res, lab = compare(ok, lambda r, terc=terc: terc(r) == 2, lambda r, terc=terc: terc(r) == 0, lambda r: r["ev_main"], "top - bottom tercile", "9.2 D-8 %s %s" % (s, fk))
        d8_terc[(s, fk)] = (terc, res, lab)
        p("| %s | %s | %.2f / %.2f | %.1f / %.1f | %s | top - bottom | %s |" % (s, fk, c1, c2, tm, tw, " / ".join(evs), cmp_row(res, lab)))
p()

# ================================================================== D-9
p("## 10. D-9: which path led into MEDIUM?")
p()
for s in SESSIONS:
    sr = sorted(sess_rows(s), key=lambda r: r["ts"])
    prev = None
    for r in sr:
        if prev is not None and prev["side"] == r["side"] and (r["ts"] - prev["ts"]).total_seconds() <= r["win"] * 60:
            r["path_prev"] = prev["tier"]; r["ep_first"] = False
        else:
            r["path_prev"] = None; r["ep_first"] = True
        prev = r
p("| Session | Tier | Path (previous signal in the episode) | n | Success % | Net EV main [95 % CI] |")
p("|---|---|---|---|---|---|")
for s in SESSIONS:
    for t in TIERS:
        for pth in [None, "WEAK", "MEDIUM", "STRONG"]:
            c = [r for r in sess_rows(s) if r["tier"] == t and r["path_prev"] == pth]
            if not c: continue
            p("| %s | %s | %s | %s |" % (s, t, "first in episode" if pth is None else "after " + pth, cell_stats(c, "main")))
p()
p("| Session | Comparison " + CMP_HDR)
p("|---|---|---|---|---|---|")
for s in SESSIONS:
    sr = sess_rows(s)
    fr = [r for r in sr if r["ep_first"]]
    for m, *_ in MODES:
        res, lab = compare(fr, lambda r: r["tier"] == "MEDIUM", lambda r: r["tier"] == "WEAK", lambda r, m=m: r["ev_" + m], "first-in-episode MEDIUM - WEAK", "10 D-9 %s %s" % (s, m))
        p("| %s | first signal in episode only, MEDIUM - WEAK, %s | %s |" % (s, m, cmp_row(res, lab)))
    res, lab = compare(sr, lambda r: r["tier"] == "MEDIUM" and r["path_prev"] == "WEAK", lambda r: r["tier"] == "MEDIUM" and r["path_prev"] == "STRONG", lambda r: r["ev_main"], "MEDIUM rising - MEDIUM decaying", "10 D-9 %s" % s)
    p("| %s | MEDIUM after WEAK - MEDIUM after STRONG | %s |" % (s, cmp_row(res, lab)))
    res, lab = compare(sr, lambda r: r["tier"] == "MEDIUM" and r["path_prev"] is None, lambda r: r["tier"] == "MEDIUM" and r["path_prev"] is not None, lambda r: r["ev_main"], "MEDIUM first - MEDIUM continuation", "10 D-9 %s" % s)
    p("| %s | MEDIUM first in episode - MEDIUM continuation | %s |" % (s, cmp_row(res, lab)))
    p("| %s | episodes: %d; signals per episode mean %.2f |  |  |  |  |" % (s, len(fr), len(sr) / max(1, len(fr))))
p()

# ================================================================== D-10
p("## 11. D-10: context and horizon")
p()
p("### 11.1 VerdictContext by tier")
p()
p("| Session | Tier | VerdictContext | Share of tier % | n | Success % | Net EV main [95 % CI] |")
p("|---|---|---|---|---|---|---|")
for s in SESSIONS:
    for t in TIERS:
        c = [r for r in sess_rows(s) if r["tier"] == t]
        for ctx in sorted(set(r["ctx"] for r in c)):
            cc = [r for r in c if r["ctx"] == ctx]
            p("| %s | %s | %s | %.1f | %s |" % (s, t, ctx, 100.0 * len(cc) / len(c), cell_stats(cc, "main")))
p()
p("| Session | Comparison " + CMP_HDR)
p("|---|---|---|---|---|---|")
for s in SESSIONS:
    sr = sess_rows(s)
    for ctx in sorted(set(r["ctx"] for r in sr)):
        res, lab = compare([r for r in sr if r["ctx"] == ctx], lambda r: r["tier"] == "MEDIUM", lambda r: r["tier"] == "WEAK", lambda r: r["ev_main"], "MEDIUM - WEAK within " + ctx, "11 D-10 %s" % s)
        p("| %s | MEDIUM - WEAK within %s | %s |" % (s, ctx, cmp_row(res, lab)))
p()
p("### 11.2 Horizon: time to resolution (carried 24 h) and the gap by window")
p()
p("| Session | Tier | Resolved in carried 24 h % | Median minutes to resolution (resolved rows) | p90 | Resolved inside the main window % | Unresolved at main-window close that hit target later % |")
p("|---|---|---|---|---|---|---|")
for s in SESSIONS:
    for t in TIERS:
        c = [r for r in sess_rows(s) if r["tier"] == t]
        res_ = sorted(r["rmin_C24"] for r in c if r["out_C24"] != 0)
        inwin = sum(1 for r in c if r["out_main"] != 0)
        late = [r for r in c if r["out_main"] == 0]
        p("| %s | %s | %.1f | %.0f | %.0f | %.1f | %.1f |" % (s, t, 100.0 * len(res_) / len(c), pctl(res_, 50), pctl(res_, 90), 100.0 * inwin / len(c), 100.0 * sum(1 for r in late if r["out_C24"] == 1) / max(1, len(late))))
p()
p("| Session | Comparison " + CMP_HDR)
p("|---|---|---|---|---|---|")
for s in SESSIONS:
    sr = sess_rows(s)
    res, lab = compare([r for r in sr if r["out_C24"] != 0], lambda r: r["tier"] == "MEDIUM", lambda r: r["tier"] == "WEAK", lambda r: r["rmin_C24"], "MEDIUM - WEAK minutes to resolution (carried)", "11.2 D-10 %s" % s)
    p("| %s | MEDIUM - WEAK mean minutes to resolution, carried 24 h, resolved rows | %s |" % (s, cmp_row(res, lab)))
    # gap change with horizon: d(C24) - d(main), paired per row
    def cbh(r):
        v = r["ev_C24"] - r["ev_main"]
        if r["tier"] == "MEDIUM": return [(0, v)]
        if r["tier"] == "WEAK": return [(1, v)]
        return []
    res = {hn: boot(hr, cbh, 2, diff_of(0, 1)) for hn, hr in halves(sr).items()}
    lab = label(res, (0, 1))
    ALL_LABELS.append(("11.2 D-10 %s" % s, "gap(C24) - gap(main)", lab, res["FULL"]))
    p("| %s | (MEDIUM - WEAK carried) - (MEDIUM - WEAK main): does a longer horizon close the gap? | %s |" % (s, cmp_row(res, lab)))
p()

# ================================================================== D-11
p("## 12. D-11: direction asymmetry")
p()
p("| Session | Tier | Side | n | Success % | Net EV main [95 % CI] |")
p("|---|---|---|---|---|---|")
for s in SESSIONS:
    for t in TIERS:
        for sd in ("LONG", "SHORT"):
            p("| %s | %s | %s | %s |" % (s, t, sd, cell_stats([r for r in sess_rows(s) if r["tier"] == t and r["side"] == sd], "main")))
p()
p("| Session | Comparison " + CMP_HDR)
p("|---|---|---|---|---|---|")
for s in SESSIONS:
    sr = sess_rows(s)
    for sd in ("LONG", "SHORT"):
        res, lab = compare([r for r in sr if r["side"] == sd], lambda r: r["tier"] == "MEDIUM", lambda r: r["tier"] == "WEAK", lambda r: r["ev_main"], "MEDIUM - WEAK, " + sd, "12 D-11 %s" % s)
        p("| %s | MEDIUM - WEAK, %s only | %s |" % (s, sd, cmp_row(res, lab)))
    for t in TIERS:
        res, lab = compare([r for r in sr if r["tier"] == t], lambda r: r["side"] == "LONG", lambda r: r["side"] == "SHORT", lambda r: r["ev_main"], "LONG - SHORT within " + t, "12 D-11 %s" % s)
        p("| %s | LONG - SHORT within %s | %s |" % (s, t, cmp_row(res, lab)))
p()

# ================================================================== D-12
p("## 13. D-12: era edges")
p()
p("- ⚠ The stability read's H1/H2 split date (2026-08-10 00:00 UTC) sits 18.6 h before the v66 collector deploy (2026-08-10 18:36:01 UTC). H1 versus H2 is therefore almost the same cut as before versus after v66. A cause CONFIRMED on both halves holds across v66; a cause seen in one half only may be an era effect.")
p()
EDGES = {"NY": [(datetime(2026, 7, 14, 14, 19, 52), "v52 NY burst modifier armed"), (datetime(2026, 8, 10, 18, 36, 1), "v66 OBV trend_gate 18 -> 23 (collector deploy)"), (ATR_STEP, "ATR step 2026-08-20")],
         "LONDON": [(datetime(2026, 7, 22, 17, 35, 47), "v60 LONDON burst modifier armed"), (datetime(2026, 8, 10, 18, 36, 1), "v66 OBV trend_gate (collector deploy)"), (ATR_STEP, "ATR step 2026-08-20")],
         "ASIA": [(datetime(2026, 7, 22, 9, 35, 58), "v58 ASIA volume multipliers -> 1.00"), (datetime(2026, 8, 1, 18, 45, 0), "v65 ASIA burst modifier armed"), (datetime(2026, 8, 10, 18, 36, 1), "v66 OBV trend_gate (collector deploy)"), (ATR_STEP, "ATR step 2026-08-20")]}
p("| Session | Segment | Rows | MEDIUM n | WEAK n | MEDIUM EV | WEAK EV | d = MEDIUM - WEAK [95 % CI] | Readable | Burst flag rate MEDIUM / WEAK % | OBV vote fire % | Volume vote fire % |")
p("|---|---|---|---|---|---|---|---|---|---|---|---|")
for s in SESSIONS:
    sr = sess_rows(s)
    edges = [(datetime(2026, 7, 6, 13, 8, 51), "v51 edge")] + EDGES[s] + [(datetime(2100, 1, 1), "end")]
    for i in range(len(edges) - 1):
        a0, na = edges[i]; a1, _ = edges[i + 1]
        seg = [r for r in sr if a0 <= r["ts"] < a1]
        if not seg: continue
        med = [r for r in seg if r["tier"] == "MEDIUM"]; wk = [r for r in seg if r["tier"] == "WEAK"]
        d = boot(seg, lambda r: [(0, r["ev_main"])] if r["tier"] == "MEDIUM" else ([(1, r["ev_main"])] if r["tier"] == "WEAK" else []), 2, diff_of(0, 1))
        brate = lambda c: 100.0 * sum(1 for r in c if any(mm.startswith("BURST_") for mm in r["muts"])) / max(1, len(c))
        p("| %s | from %s (%s) | %d | %d | %d | %s | %s | %s | %s | %.1f / %.1f | %.1f | %.1f |" % (s, a0.strftime("%Y-%m-%d %H:%M"), na, len(seg), len(med), len(wk),
            f1(sum(r["ev_main"] for r in med) / len(med)) if med else "n/a", f1(sum(r["ev_main"] for r in wk) / len(wk)) if wk else "n/a", ci(*d[:3]),
            "yes" if len(med) >= FLOOR and len(wk) >= FLOOR else "NOT READABLE", brate(med), brate(wk),
            100.0 * sum(1 for r in seg if r["pts"]["OBV"] != (0, 0)) / len(seg), 100.0 * sum(1 for r in seg if r["pts"]["VOL"] != (0, 0)) / len(seg)))
p()

p("## 13a. Candidate-cause explanation sets on MEDIUM rows (descriptive)")
p()
p("- Predicates fixed after a 200-resample pilot run of this script, before the 10,000-resample run. Descriptive only: the labels in the sections above decide CONFIRMED or not.")
p()
CAUSES = [("TRANSITIONAL ADX penalty applied", lambda r: r["pen"] > 0),
          ("decaying path (previous episode signal STRONG)", lambda r: r.get("path_prev") == "STRONG"),
          ("top VWAP-extension tercile", lambda r: r["terc_f_vwap_atr"] == "T3"),
          ("ROC vote agrees", lambda r: r["lean"]["ROC"] > 0),
          ("BBW/TTM vote agrees", lambda r: r["lean"]["BBW_TTM"] > 0),
          ("VPFR vote opposes", lambda r: r["lean"]["VPFR"] < 0),
          ("lifted by Pass 2 partial upgrades", lambda r: tier_of(r["eff"] - sum(1 for mm in r["mutset"] if mm.endswith("_UPGRADE_" + r["xs"])), r["max"]) != "MEDIUM")]
p("| Session | Candidate cause | MEDIUM rows in set | % | EV in set | EV outside set |")
p("|---|---|---|---|---|---|")
for s in SESSIONS:
    med = [r for r in sess_rows(s) if r["tier"] == "MEDIUM"]
    for nm, fn in CAUSES:
        a_ = [r["ev_main"] for r in med if fn(r)]; b_ = [r["ev_main"] for r in med if not fn(r)]
        p("| %s | %s | %d | %.1f | %s | %s |" % (s, nm, len(a_), 100.0 * len(a_) / len(med), f1(sum(a_) / len(a_)) if a_ else "n/a", f1(sum(b_) / len(b_)) if b_ else "n/a"))
p()
p("| Session | MEDIUM rows in 0 / 1 / 2 / 3 / 4+ candidate sets | EV by set count 0 / 1 / 2 / 3 / 4+ |")
p("|---|---|---|")
for s in SESSIONS:
    med = [r for r in sess_rows(s) if r["tier"] == "MEDIUM"]
    byk = defaultdict(list)
    for r in med:
        byk[min(4, sum(1 for nm, fn in CAUSES if fn(r)))].append(r["ev_main"])
    p("| %s | %s | %s |" % (s, " / ".join(str(len(byk[k])) for k in range(5)), " / ".join(f1(sum(byk[k]) / len(byk[k])) if byk[k] else "n/a" for k in range(5))))
p()

# ================================================================== sensitivity
p("## 14. Sensitivity: rows whose re-score matches all six fields only")
p()
p("| Session | Vote or statistic | Comparison " + CMP_HDR)
p("|---|---|---|---|---|---|---|")
for s in SESSIONS:
    sr = [r for r in sess_rows(s) if r["match"]]
    res, lab = compare(sr, lambda r: r["tier"] == "MEDIUM", lambda r: r["tier"] == "WEAK", lambda r: r["ev_main"], "MEDIUM - WEAK (matching rows)", "14 sens %s" % s)
    p("| %s | tier gap | MEDIUM - WEAK | %s |" % (s, cmp_row(res, lab)))
    srv = [r for r in sr if r["vpfr_verified"] and r["vpfr_label"] != "NEUTRAL"]
    res, lab = compare(srv, lambda r: r["lean"]["VPFR"] > 0, lambda r: r["lean"]["VPFR"] < 0, lambda r: r["ev_main"], "VPFR agree - oppose (matching, verified)", "14 sens %s" % s)
    p("| %s | VPFR | agree - oppose | %s |" % (s, cmp_row(res, lab)))
p()

# ================================================================== labels
p("## 15. Every labelled comparison")
p()
cnt = Counter(l[2].split(" (")[0] for l in ALL_LABELS)
p("- Labelled comparisons: %d. %s." % (len(ALL_LABELS), "; ".join("%s %d" % kv for kv in sorted(cnt.items()))))
readable_n = sum(v for k, v in cnt.items() if k != "NOT READABLE")
p("- Multiplicity: under no true effect, a readable comparison reaches CONFIRMED with probability about 2 x 0.025 x 0.025 = 0.00125 (independent halves). Expected false CONFIRMED over %d readable comparisons: %.2f." % (readable_n, readable_n * 0.00125))
p()
p("| Section | Comparison | FULL d [95 % CI] | Label |")
p("|---|---|---|---|")
for ctx, nm, lab, f in ALL_LABELS:
    if lab.startswith("NOT READABLE") or lab.startswith("NO DIFFERENCE"): continue
    p("| %s | %s | %s | %s |" % (ctx, nm, ci(*f[:3]), lab))
p()

text = "\n".join(out) + "\n"
with open(OUT, "w", encoding="utf-8", newline="\n") as f:
    f.write(text)
print("Wrote " + OUT)
print("\n".join(l for l in out if l.startswith("- Labelled") or l.startswith("- Multiplicity")))
