#!/usr/bin/env python3
# tools/ops/q1d_tier_geometry.py
#
# Q-1 option (d): target and stop distance by tier (docs/medium-tier-diagnosis-spec-back.md, decision Q-1, ruled (d)
# first by the trader 2026-09-18). Read: docs/q1d-tier-geometry-read-2026-09-24.md. Python 3 standard library only.
# Host-agnostic: no engine code, no settings write, no network. Vocabulary: docs/DeribitIndicatorProject.md section 5a.
#
# Question: success rate rises at the top score bins while net EV per trade does not. Is the rise bought with
# nearer targets (payoff down), or does the ladder carry direction information that the geometry spends?
#
# Inputs (gitignored, regenerated by the instrument, see the read's re-run section):
#   --rows        SwingFallbackRead --mode diagexport on the newest fetch (one line per swing read population row).
#   --prior-rows  The same export on the fetch the MEDIUM-tier diagnosis used (aws_fetch/20260913-153704). It defines
#                 the main population P0 (8,810 rows) and carries its H1/H2 halves unchanged.
#   --attr        SwingFallbackRead --mode rescore attribution (recomputed VPFR label), for the POC-fix slice.
#   --logs        analysis_log copies (pooled book, box live log), first timestamp wins, for SwingStopLong/Short.
#   settings.json (tracked, read-only): fees, stop bound, stop floor.
#
# Rules fixed before the first run:
#   * Populations: P0 = the prior read's rows (v51 edge to 2026-09-11), halves H1/H2 as the prior read.
#     H3 = rows from 2026-09-14 in --rows and not in P0: a forward segment, reported separately, never pooled with P0.
#     Sessions separate, never pooled for outcomes. Weekday rows only (the export applies the trading-week rule).
#   * Window: main window (NY 15 min, LONDON and ASIA 45 min), maker/maker fee from scoring.trade_costs. Carried 24 h
#     is secondary and for P0 only.
#   * Distances: per signal, bps of entry, from the logged Price and Placed* levels (export TBps, SBps).
#     Pooled rates use the section 5a sums: gross breakeven = sum S / sum (T + S); net breakeven = sum (S + fee) /
#     sum (T + S). Edges in pp. Net EV per trade from the export's candle-walk result.
#   * Coined here: distance-weighted success rate = sum over wins of (T + S) / sum (T + S). Exact identity per cell:
#       net EV = mean(T + S) x (distance-weighted success - gross breakeven) + timeout term - fee,
#       timeout term = (1/n) x sum over timeouts of (S + mark). Self-checked on every cell.
#   * Stop label, derived from the logged SwingStop and ATR by the shipped DG1 rule (SignalEmitter mode 0):
#       SWING_STOP if 0 < swing distance, >= 4 ticks and <= stop_max_atr_mult x ATR; STOP_CLAMPED if the swing
#       distance exceeds the bound; else FALLBACK_ATR. Self-check against the logged placed stop.
#   * CI: 95 % percentile bootstrap of whole UTC trading days, fixed seed, --resamples (default 10,000).
#   * Readable: n >= 100 in each group a comparison uses. Label rule: the census rule, copied from
#     tools/ops/medium_tier_diagnosis.py (first match wins): NOT READABLE -> CONFIRMED -> H1 FINDING, H2 SAME SIGN NOT
#     SIGNIFICANT -> H1 FINDING, H2 CONTRADICTS OR NOT READABLE -> DISCOVERY ONLY (H2) -> NO DIFFERENCE SHOWN.
#     The label is two-sided: it names the sign it found (d > 0 or d < 0), so both directions are tested at once.
#   * Geometry control: rows stratified by per-signal breakeven S / (T + S) quintile x (T + S) tercile, cut points
#     from the session's H1 rows (all tiers). Tier A re-weighted to tier B's stratum mix over strata where A has rows;
#     B restricted to the same strata. d_within = A_reweighted - B_covered.
#   * POC-fix slice (commit a6b33fe, not deployed): P0 rows whose verified recomputed VPFR label opens the POC tier
#     only under the fix (LONG + NEAR_HVN_SUPPORT, SHORT + NEAR_HVN_RESIST) and whose logged target is the ATR
#     fallback ("none"). A superset of the 143 population rows the fix moves (the ladder reaches the POC tier only
#     when swing and HVN fail). Sensitivity = the key comparisons with the slice removed.
#
# Run (from the repo root): see the read's re-run section.

import argparse, csv, hashlib, json, math, os, random, sys
from collections import Counter, defaultdict
from datetime import datetime, timezone

SESSIONS = ["NY", "LONDON", "ASIA"]
TIERS = ["STRONG", "MEDIUM", "WEAK"]
FLOOR = 100
V66 = datetime(2026, 8, 10, 18, 36, 1)
ATR_STEP = datetime(2026, 8, 20)
P0_END = datetime(2026, 9, 12)
H3_START = datetime(2026, 9, 14)
TICK = 0.5  # SignalEmitter.TickSize (Core/SignalEmitter.vb, Public Const)

ap = argparse.ArgumentParser()
ap.add_argument("--root", default=".")
ap.add_argument("--rows", default=os.path.join("backtest_data", "q1d-tier-geometry", "diagnosis-rows-20260924.csv"))
ap.add_argument("--prior-rows", default=os.path.join("backtest_data", "swing-fallback-read", "diagnosis-rows.csv"))
ap.add_argument("--attr", default=os.path.join("backtest_data", "swing-fallback-read", "rescore-attribution.csv"))
ap.add_argument("--logs", nargs="+", default=[os.path.join("AWS-copybacks", "pooled-book-2026-09-09", "analysis_log_pooled.csv"),
                                              os.path.join("aws_fetch", "20260924-084613", "analysis_log.csv")])
ap.add_argument("--resamples", type=int, default=10000)
ap.add_argument("--seed", type=int, default=20260924)
ap.add_argument("--out", default=os.path.join("backtest_data", "q1d-tier-geometry", "q1d-tier-geometry-output.md"))
args = ap.parse_args()
ROOT = os.path.abspath(args.root)
J = lambda p_: p_ if os.path.isabs(p_) else os.path.join(ROOT, p_)
R = args.resamples

out = []
def p(s=""):
    out.append(s)

def md5(path):
    h = hashlib.md5()
    with open(path, "rb") as f:
        for b in iter(lambda: f.read(1 << 20), b""):
            h.update(b)
    return h.hexdigest()

def fnum(s):
    try:
        return float(s)
    except (TypeError, ValueError):
        return float("nan")

# ------------------------------------------------------------------ settings
cfg = json.load(open(J("settings.json"), encoding="utf-8-sig"))
tc = cfg["scoring"]["trade_costs"]
if tc["round_trip_style"] != "maker_maker":
    raise SystemExit("fee style %s: the export's MainNetEv uses maker/maker; re-derive. STOP." % tc["round_trip_style"])
FEE = 2.0 * tc["maker_fee_bps"]
SLV = cfg["scoring"]["structural_levels"]
STOP_BOUND = SLV["stop_max_atr_mult"]
STOP_FLOOR = SLV["stop_min_floor_ticks"] * TICK
FB_STOP = cfg["scoring"]["atr_stop_multiplier"]

# ------------------------------------------------------------------ load
prior = {r["Timestamp"]: r for r in csv.DictReader(open(J(args.prior_rows), encoding="utf-8"))}
rows_all = list(csv.DictReader(open(J(args.rows), encoding="utf-8")))

attr = {}
with open(J(args.attr), encoding="utf-8") as f:
    rd = csv.reader(f)
    h = next(rd)
    for x in rd:
        if len(x) == len(h) + 1:  # unquoted comma in the Class field (tools/ops/medium_tier_diagnosis.py, TOOL-2)
            x = x[:12] + [x[12] + "," + x[13]] + x[14:]
        if len(x) != len(h):
            raise SystemExit("attribution row with %d fields: %s" % (len(x), x[0]))
        attr[x[0]] = dict(zip(h, x))

logrow = {}
for lp in args.logs:
    with open(J(lp), encoding="utf-8", errors="replace") as f:
        rd = csv.reader(f)
        h = next(rd)
        ix = {c: i for i, c in enumerate(h)}
        for x in rd:
            if not x or x[0] in logrow:
                continue
            if len(x) <= ix["SwingStopShort"]:
                continue
            logrow[x[0]] = (fnum(x[ix["SwingStopLong"]]), fnum(x[ix["SwingStopShort"]]), fnum(x[ix["ATR"]]),
                            fnum(x[ix["PlacedStopLong"]]), fnum(x[ix["PlacedStopShort"]]),
                            fnum(x[ix["SwingTargetLong"]]), fnum(x[ix["SwingTargetShort"]]),
                            fnum(x[ix["VPFRNearestHvnAbove"]]), fnum(x[ix["VPFRNearestHvnBelow"]]))

pop = []
n_nolog = 0
n_prior_mismatch = 0
stop_check = Counter()
for d in rows_all:
    ts = d["Timestamp"]
    r = {"tsS": ts, "ts": datetime.strptime(ts, "%Y-%m-%d %H:%M:%S"), "day": d["Day"], "session": d["Session"],
         "side": d["Side"], "tier": d["Tier"], "cap": d["Cap"], "price": fnum(d["Price"]), "atr": fnum(d["Atr"]),
         "T": fnum(d["TBps"]), "S": fnum(d["SBps"]), "TA": fnum(d["TAtr"]), "SA": fnum(d["SAtr"]),
         "out": int(d["MainOutcome"]), "ev": fnum(d["MainNetEv"]), "rmin": fnum(d["MainResolveMin"]),
         "out24": int(d["C24Outcome"]), "ev24": fnum(d["C24NetEv"]),
         "max": int(float(d["MaxScore"]))}
    isL = r["side"] == "LONG"
    r["eff"] = int(float(d["EffectiveLongScore"] if isL else d["EffectiveShortScore"]))
    r["share"] = r["eff"] / r["max"]
    r["atr_bps"] = r["atr"] / r["price"] * 10000.0
    if ts in prior:
        if r["ts"] >= P0_END:
            raise SystemExit("prior row after the P0 end: %s" % ts)
        pr = prior[ts]
        if any(pr[c] != d[c] for c in d if c != "Half"):
            n_prior_mismatch += 1
        r["seg"] = "P0"
        r["half"] = pr["Half"]
    elif r["ts"] >= H3_START:
        r["seg"] = "H3"
        r["half"] = "H3"
    else:
        raise SystemExit("row neither in P0 nor in H3: %s" % ts)
    # stop label (DG1, mode 0)
    lg = logrow.get(ts)
    if lg is None:
        n_nolog += 1
        r["slabel"] = "?"
        r["swingwhy"] = "?"
    else:
        swl, sws, atr_log, psl, pss, stl, sts, hva, hvb = lg
        # why the swing tier did not place (target ladder, shipped mode 0; bound = target_max_atr_mult x ATR)
        st_ = stl if isL else sts
        tdist = (1.0 if isL else -1.0) * (st_ - r["price"])
        tbound = SLV["target_max_atr_mult"] * atr_log
        if not (st_ > 0):
            r["swingwhy"] = "no swing target"
        elif tdist <= 0:
            r["swingwhy"] = "swing target behind entry"
        elif tdist > tbound:
            r["swingwhy"] = "swing target beyond bound"
        else:
            r["swingwhy"] = "swing target qualifies"
        sw = swl if isL else sws
        placed = psl if isL else pss
        sg = 1.0 if isL else -1.0
        dist = sg * (r["price"] - sw)
        bound = STOP_BOUND * atr_log
        if sw > 0 and dist > 0 and dist >= STOP_FLOOR and dist <= bound:
            lab = "SWING_STOP"
            ok = abs(placed - sw) <= 0.006
        elif sw > 0 and dist > bound:
            lab = "STOP_CLAMPED"
            ok = abs(sg * (r["price"] - placed) - bound) <= 0.02
        else:
            lab = "FALLBACK_ATR"
            ok = abs(sg * (r["price"] - placed) - FB_STOP * atr_log) <= 0.02
        r["slabel"] = lab
        stop_check[(lab, ok)] += 1
    # POC-fix slice (P0 only; the attribution covers P0)
    a = attr.get(ts)
    r["pocslice"] = bool(a and a["VpfrVerified"] == "1" and r["cap"] == "none" and
                         ((isL and a["VpfrSignal"] == "NEAR_HVN_SUPPORT") or (not isL and a["VpfrSignal"] == "NEAR_HVN_RESIST")))
    r["win"] = 1.0 if r["out"] == 1 else 0.0
    r["lose"] = 1.0 if r["out"] in (2, 3) else 0.0
    r["open"] = 1.0 if r["out"] == 0 else 0.0
    r["mark"] = r["ev"] + FEE if r["out"] == 0 else 0.0
    r["win24"] = 1.0 if r["out24"] == 1 else 0.0
    r["W"] = r["T"] + r["S"]
    r["pbe"] = r["S"] / r["W"]
    pop.append(r)

P0 = [r for r in pop if r["seg"] == "P0"]
H3 = [r for r in pop if r["seg"] == "H3"]

# ------------------------------------------------------------------ statistics core (bootstrap + label copied from medium_tier_diagnosis.py)
def pctl(sorted_vals, q):
    if not sorted_vals: return float("nan")
    k = max(1, min(len(sorted_vals), math.ceil(q / 100.0 * len(sorted_vals))))
    return sorted_vals[k - 1]

SEEDC = [0]
def boot(rows, contribs, K, stat):
    days = {}
    for r in rows:
        if contribs(r) and r["day"] not in days:
            days[r["day"]] = len(days)
    D = len(days)
    S = [[0.0] * D for _ in range(K)]
    C = [[0] * D for _ in range(K)]
    for r in rows:
        cs = contribs(r)
        if not cs: continue
        i = days[r["day"]]
        for k, v in cs:
            S[k][i] += v
            C[k][i] += 1
    tS = [sum(s) for s in S]; tC = [sum(c) for c in C]
    point = stat(tS, tC)
    SEEDC[0] += 1
    if D == 0:
        return point, float("nan"), float("nan"), tC
    rng = random.Random(args.seed * 1000 + SEEDC[0])
    rngD = range(D)
    draws = []
    for _ in range(R):
        idx = rng.choices(rngD, k=D)
        bs = [sum(map(S[k].__getitem__, idx)) for k in range(K)]
        bc = [sum(map(C[k].__getitem__, idx)) for k in range(K)]
        v = stat(bs, bc)
        if v == v:
            draws.append(v)
    draws.sort()
    return point, pctl(draws, 2.5), pctl(draws, 97.5), tC

def readable(r, need):
    return all(r[3][k] >= FLOOR for k in need)

def sig(r, need):
    return readable(r, need) and r[1] == r[1] and (r[1] > 0 or r[2] < 0)

def label(res, need):
    f, h1, h2 = res["FULL"], res["H1"], res["H2"]
    if not readable(f, need): return "NOT READABLE"
    sgn = lambda x: (x > 0) - (x < 0)
    side = lambda r: "d > 0" if r[0] > 0 else "d < 0"
    if sig(h1, need) and sig(h2, need) and sgn(h1[0]) == sgn(h2[0]): return "CONFIRMED (%s)" % side(h1)
    if sig(h1, need) and readable(h2, need) and sgn(h1[0]) == sgn(h2[0]): return "H1 FINDING, H2 SAME SIGN NOT SIGNIFICANT (%s)" % side(h1)
    if sig(h1, need): return "H1 FINDING, H2 CONTRADICTS OR NOT READABLE (%s)" % side(h1)
    if sig(h2, need): return "DISCOVERY ONLY (H2) (%s)" % side(h2)
    return "NO DIFFERENCE SHOWN"

def f1(x):
    return "n/a" if x != x else ("%+.1f" % x)

def f2(x):
    return "n/a" if x != x else ("%+.2f" % x)

def ci(pt, lo, hi, fmt=f1):
    return "%s [%s, %s]" % (fmt(pt), fmt(lo), fmt(hi))

# ------------------------------------------------------------------ metrics as (cells per group, stat on one group)
# Each metric: list of per-row values placed in cells, and a function of (sums, counts) for one group.
def m_mean(key):
    return ([lambda r, k=key: r[k]], lambda s, c: s[0] / c[0] if c[0] else float("nan"))

METRICS = {
    "mean target distance, bps": m_mean("T"),
    "mean stop distance, bps": m_mean("S"),
    "mean target distance, ATR": m_mean("TA"),
    "mean ATR, bps of entry": m_mean("atr_bps"),
    "payoff ratio sum T / sum S": ([lambda r: r["T"], lambda r: r["S"]], lambda s, c: s[0] / s[1] if s[1] else float("nan")),
    "gross breakeven rate, pp": ([lambda r: r["T"], lambda r: r["S"]], lambda s, c: 100.0 * s[1] / (s[0] + s[1])),
    "success rate, pp": ([lambda r: r["win"]], lambda s, c: 100.0 * s[0] / c[0] if c[0] else float("nan")),
    "gross edge, pp": ([lambda r: r["win"], lambda r: r["T"], lambda r: r["S"]],
                       lambda s, c: 100.0 * (s[0] / c[0] - s[2] / (s[1] + s[2])) if c[0] else float("nan")),
    "net edge, pp": ([lambda r: r["win"], lambda r: r["T"], lambda r: r["S"]],
                     lambda s, c: 100.0 * (s[0] / c[0] - (s[2] + c[0] * FEE) / (s[1] + s[2])) if c[0] else float("nan")),
    "distance-weighted success rate, pp": ([lambda r: r["win"] * r["W"], lambda r: r["W"]], lambda s, c: 100.0 * s[0] / s[1]),
    "distance-weighted gross edge, pp": ([lambda r: r["win"] * r["W"], lambda r: r["W"], lambda r: r["S"]],
                                         lambda s, c: 100.0 * (s[0] - s[2]) / s[1]),
    "timeout share, pp": ([lambda r: r["open"]], lambda s, c: 100.0 * s[0] / c[0] if c[0] else float("nan")),
    "timeout term, bps": ([lambda r: r["open"] * (r["S"] + r["mark"])], lambda s, c: s[0] / c[0] if c[0] else float("nan")),
    "net EV per trade, bps": m_mean("ev"),
    "success rate, carried 24 h, pp": ([lambda r: r["win24"]], lambda s, c: 100.0 * s[0] / c[0] if c[0] else float("nan")),
    "gross edge, carried 24 h, pp": ([lambda r: r["win24"], lambda r: r["T"], lambda r: r["S"]],
                                     lambda s, c: 100.0 * (s[0] / c[0] - s[2] / (s[1] + s[2])) if c[0] else float("nan")),
    "net EV per trade, carried 24 h, bps": m_mean("ev24"),
}
FMT = {k: (f2 if "ratio" in k else f1) for k in METRICS}

def compare_metric(rows, ga, gb, metric, halves=True):
    vals, st = METRICS[metric]
    k = len(vals)
    def contribs(r):
        o = []
        if ga(r): o.extend((i, v(r)) for i, v in enumerate(vals))
        if gb(r): o.extend((k + i, v(r)) for i, v in enumerate(vals))
        return o
    def stat(s, c):
        try:
            return st(s[:k], c[:k]) - st(s[k:], c[k:])
        except ZeroDivisionError:  # a resample with no row of one group
            return float("nan")
    need = (0, k)
    if not halves:
        return boot(rows, contribs, 2 * k, stat), need
    res = {"FULL": boot(rows, contribs, 2 * k, stat),
           "H1": boot([r for r in rows if r["half"] == "H1"], contribs, 2 * k, stat),
           "H2": boot([r for r in rows if r["half"] == "H2"], contribs, 2 * k, stat)}
    return res, need

def one_group(rows, metric):
    vals, st = METRICS[metric]
    k = len(vals)
    def stat(s, c):
        try:
            return st(s, c)
        except ZeroDivisionError:
            return float("nan")
    return boot(rows, lambda r: [(i, v(r)) for i, v in enumerate(vals)], k, stat)

def nt(r, need):
    return "/".join(str(r[3][k]) for k in need)

LABELS = []
def cmp_line(rows, ga, gb, metric, ctx):
    res, need = compare_metric(rows, ga, gb, metric)
    lab = label(res, need)
    LABELS.append((ctx, metric, lab, res["FULL"][0]))
    fm = FMT[metric]
    return "%s (%s) | %s | %s | %s" % (ci(*res["FULL"][:3], fmt=fm), nt(res["FULL"], need), ci(*res["H1"][:3], fmt=fm),
                                       ci(*res["H2"][:3], fmt=fm), lab)

tier_is = lambda t: (lambda r, t=t: r["tier"] == t)
PAIRS = [("STRONG", "WEAK"), ("MEDIUM", "WEAK"), ("STRONG", "MEDIUM")]

# ------------------------------------------------------------------ descriptive cell
def q5(v):
    s = sorted(v)
    return "/".join("%.1f" % pctl(s, q) for q in (10, 25, 50, 75, 90))

def cell_geom(rows):
    n = len(rows)
    sT = sum(r["T"] for r in rows); sS = sum(r["S"] for r in rows)
    ratios = sorted(r["T"] / r["S"] for r in rows)
    return {"n": n, "Tq": q5([r["T"] for r in rows]), "Sq": q5([r["S"] for r in rows]), "Tm": sT / n, "Sm": sS / n,
            "ratio": sT / sS, "medratio": pctl(ratios, 50), "TA": pctl(sorted(r["TA"] for r in rows), 50),
            "SA": pctl(sorted(r["SA"] for r in rows), 50), "atr": pctl(sorted(r["atr_bps"] for r in rows), 50)}

def cell_out(rows):
    n = len(rows)
    sT = sum(r["T"] for r in rows); sS = sum(r["S"] for r in rows); sW = sT + sS
    succ = 100.0 * sum(r["win"] for r in rows) / n
    stop = 100.0 * sum(r["lose"] for r in rows) / n
    tout = 100.0 * sum(r["open"] for r in rows) / n
    gbe = 100.0 * sS / sW
    nbe = 100.0 * (sS + n * FEE) / sW
    sw = 100.0 * sum(r["win"] * r["W"] for r in rows) / sW
    W = sW / n
    term1 = W * (sw - gbe) / 100.0
    tterm = sum(r["open"] * (r["S"] + r["mark"]) for r in rows) / n
    ev = sum(r["ev"] for r in rows) / n
    resid = ev - (term1 + tterm - FEE)
    return {"n": n, "succ": succ, "stop": stop, "tout": tout, "gbe": gbe, "nbe": nbe, "gedge": succ - gbe, "nedge": succ - nbe,
            "sw": sw, "wedge": sw - gbe, "W": W, "term1": term1, "tterm": tterm, "ev": ev, "resid": resid}

# ================================================================== output
p("# q1d_tier_geometry.py output (Q-1 option (d): target and stop distance by tier)")
p()
p("- Run at (UTC): " + datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S"))
p("- Inputs: `%s` (MD5 %s); `%s` (MD5 %s); `%s` (MD5 %s)." % (args.rows, md5(J(args.rows)), args.prior_rows, md5(J(args.prior_rows)), args.attr, md5(J(args.attr))))
p("- Logs for the stop label: " + "; ".join("`%s` (MD5 %s)" % (lp, md5(J(lp))) for lp in args.logs))
p("- settings.json version %s: fee %.2f bps round trip (maker/maker), stop bound %.2f x ATR, stop floor %.1f USD, fallback stop %.2f x ATR." % (cfg["version"], FEE, STOP_BOUND, STOP_FLOOR, FB_STOP))
p("- Bootstrap: %d resamples of whole UTC trading days, seed %d + call index; readable n >= %d per group." % (R, args.seed, FLOOR))
p()

# ---- 0 self-checks
p("## 0. Self-checks")
p()
p("| Check | Result |")
p("|---|---|")
p("| Rows in --rows | %d |" % len(rows_all))
p("| P0 rows (in --prior-rows) / prior export rows (must be equal) | %d / %d |" % (len(P0), len(prior)))
p("| P0 rows whose fields differ from the prior export, Half excluded (must be 0) | %d |" % n_prior_mismatch)
p("| H3 rows (from 2026-09-14) | %d |" % len(H3))
p("| Rows with no log row for the stop label (must be 0) | %d |" % n_nolog)
p("| Stop label reproduces the logged placed stop (must be all) | %d of %d |" % (sum(v for (l, ok), v in stop_check.items() if ok), sum(stop_check.values())))
tgt_ok = sum(1 for r in pop if r["out"] == 1 and abs(r["ev"] - (r["T"] - FEE)) < 1e-6)
p("| Target-hit rows where net EV = T - fee (must be all) | %d of %d |" % (tgt_ok, sum(1 for r in pop if r["out"] == 1)))
stp_ok = sum(1 for r in pop if r["out"] in (2, 3) and abs(r["ev"] - (-r["S"] - FEE)) < 1e-6)
p("| Stop-hit and same-bar rows where net EV = -S - fee (must be all) | %d of %d |" % (stp_ok, sum(1 for r in pop if r["out"] in (2, 3))))
maxres = 0.0
for seg in (P0, H3):
    for s in SESSIONS:
        for t in TIERS:
            c = [r for r in seg if r["session"] == s and r["tier"] == t]
            if c: maxres = max(maxres, abs(cell_out(c)["resid"]))
p("| Largest absolute residual of the net EV identity over session x tier cells, bps (must be ~0) | %.2e |" % maxres)
p("| Tier = tier of the share (STRONG iff share >= 0.70, MEDIUM iff 0.53 <= share < 0.70), mismatches (must be 0) | %d |" %
  sum(1 for r in pop if (r["share"] >= cfg["scoring"]["verdict_strong_pct"]) != (r["tier"] == "STRONG") or
      ((cfg["scoring"]["verdict_med_pct"] <= r["share"] < cfg["scoring"]["verdict_strong_pct"]) != (r["tier"] == "MEDIUM"))))
p("| POC-fix slice rows in P0 (a superset of the 143 moved population rows) | %d |" % sum(1 for r in P0 if r["pocslice"]))
p()
p("| Segment | Session | Rows | STRONG | MEDIUM | WEAK | Trading days | H1 rows | H2 rows |")
p("|---|---|---|---|---|---|---|---|---|")
for nm, seg in (("P0", P0), ("H3", H3)):
    for s in SESSIONS:
        sr = [r for r in seg if r["session"] == s]
        c = Counter(r["tier"] for r in sr)
        p("| %s | %s | %d | %d | %d | %d | %d | %d | %d |" % (nm, s, len(sr), c["STRONG"], c["MEDIUM"], c["WEAK"], len(set(r["day"] for r in sr)),
                                                           sum(1 for r in sr if r["half"] == "H1"), sum(1 for r in sr if r["half"] == "H2")))
p()

def geom_table(seg, title):
    p(title)
    p()
    p("| Session | Tier | n | Target bps p10/p25/p50/p75/p90 | Mean T | Stop bps p10/p25/p50/p75/p90 | Mean S | Sum T / sum S | Median T/S | Median T, ATR | Median S, ATR | Median ATR, bps |")
    p("|---|---|---|---|---|---|---|---|---|---|---|---|")
    for s in SESSIONS:
        for t in TIERS + ["ALL"]:
            c = [r for r in seg if r["session"] == s and (t == "ALL" or r["tier"] == t)]
            if not c: continue
            g = cell_geom(c)
            p("| %s | %s | %d | %s | %.1f | %s | %.1f | %.2f | %.2f | %.2f | %.2f | %.1f |" % (s, t, g["n"], g["Tq"], g["Tm"], g["Sq"], g["Sm"], g["ratio"], g["medratio"], g["TA"], g["SA"], g["atr"]))
    p()

def mix_table(seg, title):
    p(title)
    p()
    p("| Session | Tier | n | Target: ATR fallback (none) % | swing % | HVN % | POC % | Stop: SWING_STOP % | STOP_CLAMPED % | FALLBACK_ATR % | Mean T by target type: none / swing / HVN |")
    p("|---|---|---|---|---|---|---|---|---|---|---|")
    for s in SESSIONS:
        for t in TIERS:
            c = [r for r in seg if r["session"] == s and r["tier"] == t]
            if not c: continue
            n = len(c)
            cc = Counter(r["cap"] for r in c); sc = Counter(r["slabel"] for r in c)
            mt = []
            for cap in ("none", "swing", "hvn"):
                v = [r["T"] for r in c if r["cap"] == cap]
                mt.append("%.1f (%d)" % (sum(v) / len(v), len(v)) if v else "n/a")
            p("| %s | %s | %d | %.1f | %.1f | %.1f | %.1f | %.1f | %.1f | %.1f | %s |" % (s, t, n, 100.0 * cc["none"] / n, 100.0 * cc["swing"] / n, 100.0 * cc["hvn"] / n, 100.0 * cc["poc"] / n,
                                                                             100.0 * sc["SWING_STOP"] / n, 100.0 * sc["STOP_CLAMPED"] / n, 100.0 * sc["FALLBACK_ATR"] / n, " / ".join(mt)))
    p()

def out_table(seg, title, groups):
    p(title)
    p()
    p("| Session | Cell | n | Success % | Stop hit % | Timeout % | Gross BE % | Net BE % | Gross edge pp | Net edge pp | Dist-weighted success % | Dist-weighted gross edge pp | Mean T+S bps | W x weighted edge | Timeout term | Fee | Net EV bps [95 % CI] |")
    p("|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|")
    for s in SESSIONS:
        for nm, pred in groups:
            c = [r for r in seg if r["session"] == s and pred(r)]
            if not c: continue
            o = cell_out(c)
            b = boot(c, lambda r: [(0, r["ev"])], 1, lambda s_, c_: s_[0] / c_[0] if c_[0] else float("nan"))
            p("| %s | %s | %d%s | %.1f | %.1f | %.1f | %.1f | %.1f | %+.1f | %+.1f | %.1f | %+.1f | %.1f | %+.2f | %+.2f | -%.2f | %s |" % (
                s, nm, o["n"], "" if o["n"] >= FLOOR else " (NOT READABLE)", o["succ"], o["stop"], o["tout"], o["gbe"], o["nbe"], o["gedge"], o["nedge"],
                o["sw"], o["wedge"], o["W"], o["term1"], o["tterm"], FEE, ci(*b[:3])))
    p()

TIER_GROUPS = [(t, tier_is(t)) for t in TIERS]
SHARE_BINS = [(0.0, 0.45, "share < 0.45"), (0.45, 0.53, "share 0.45-0.53"), (0.53, 0.60, "share 0.53-0.60"), (0.60, 0.70, "share 0.60-0.70"), (0.70, 9.0, "share >= 0.70")]
BIN_GROUPS = [(nm, (lambda r, lo=lo, hi=hi: lo <= r["share"] < hi)) for lo, hi, nm in SHARE_BINS]

def why_table(seg, title):
    p(title)
    p()
    p("| Session | Tier | n | No swing target % | Swing target behind entry % | Swing target beyond the 3.5 x ATR bound % | Swing target qualifies % | Target ATR fallback % | Median swing target distance when it qualifies, ATR |")
    p("|---|---|---|---|---|---|---|---|---|")
    for s in SESSIONS:
        for t in TIERS:
            c = [r for r in seg if r["session"] == s and r["tier"] == t]
            if not c: continue
            n = len(c)
            w = Counter(r["swingwhy"] for r in c)
            qd = sorted(r["TA"] for r in c if r["cap"] == "swing")
            p("| %s | %s | %d | %.1f | %.1f | %.1f | %.1f | %.1f | %s |" % (s, t, n, 100.0 * w["no swing target"] / n, 100.0 * w["swing target behind entry"] / n,
                                                                  100.0 * w["swing target beyond bound"] / n, 100.0 * w["swing target qualifies"] / n,
                                                                  100.0 * sum(1 for r in c if r["cap"] == "none") / n, "%.2f" % pctl(qd, 50) if qd else "n/a"))
    p()

geom_table(P0, "## 1. Geometry by session and tier, P0 (placed levels, bps of entry)")
mix_table(P0, "## 2. Target type and stop label by session and tier, P0")
why_table(P0, "### 2.1 Why the swing tier did not place, by tier, P0 (from the logged SwingTarget, Price and ATR)")
p("| Session | Comparison | Metric | FULL d [95 % CI] (n) | H1 d [95 % CI] | H2 d [95 % CI] | Label |")
p("|---|---|---|---|---|---|---|")
METRICS["share with no swing target, pp"] = ([lambda r: 1.0 if r["swingwhy"] == "no swing target" else 0.0], lambda s, c: 100.0 * s[0] / c[0] if c[0] else float("nan"))
METRICS["share with an ATR fallback target, pp"] = ([lambda r: 1.0 if r["cap"] == "none" else 0.0], lambda s, c: 100.0 * s[0] / c[0] if c[0] else float("nan"))
FMT.update({k: f1 for k in METRICS if k not in FMT})
for s in SESSIONS:
    sr = [r for r in P0 if r["session"] == s]
    for a_, b_ in PAIRS[:2]:
        for m in ("share with no swing target, pp", "share with an ATR fallback target, pp"):
            p("| %s | %s - %s | %s | %s |" % (s, a_, b_, m, cmp_line(sr, tier_is(a_), tier_is(b_), m, "2.1 %s %s-%s" % (s, a_, b_))))
p()
out_table(P0, "## 3. Outcome ledger by session and tier, P0, main window (NY 15 min, LONDON and ASIA 45 min)", TIER_GROUPS)
p("- Identity per row: net EV = W x weighted edge + timeout term - fee (section 0 residual). W = mean(T + S).")
p()
out_table(P0, "## 4. Outcome ledger by score-share bin, P0, main window (the prior read's bins; >= 0.70 is STRONG, 0.53-0.70 is MEDIUM)", BIN_GROUPS)

# ---- 5 comparisons with labels
p("## 5. Tier comparisons, P0, main window: d = first tier - second tier, day bootstrap, halves H1 / H2")
p()
p("- Two-sided: the label names the sign it found. A nearer-target hypothesis reads d < 0 on target distance; the opposite reads d > 0.")
p()
p("| Session | Comparison | Metric | FULL d [95 % CI] (n) | H1 d [95 % CI] | H2 d [95 % CI] | Label |")
p("|---|---|---|---|---|---|---|")
CMP_METRICS = ["mean target distance, bps", "mean stop distance, bps", "payoff ratio sum T / sum S", "mean target distance, ATR", "mean ATR, bps of entry",
               "gross breakeven rate, pp", "success rate, pp", "gross edge, pp", "distance-weighted success rate, pp", "distance-weighted gross edge, pp",
               "timeout share, pp", "timeout term, bps", "net EV per trade, bps"]
for s in SESSIONS:
    sr = [r for r in P0 if r["session"] == s]
    for a_, b_ in PAIRS:
        for m in CMP_METRICS:
            p("| %s | %s - %s | %s | %s |" % (s, a_, b_, m, cmp_line(sr, tier_is(a_), tier_is(b_), m, "5 %s %s-%s" % (s, a_, b_))))
p()

# ---- 6 geometry control
p("## 6. Geometry-controlled tier gaps, P0, main window")
p()
p("- Strata: per-signal breakeven S / (T + S) quintile x (T + S) tercile; cut points from the session's H1 rows, all tiers.")
p("- d_raw = A - B. d_within = A re-weighted to B's stratum mix - B on the strata A covers. Geometry share = d_raw - d_within.")
p()

def strata_fn(sr):
    h1 = [r for r in sr if r["half"] == "H1"]
    pb = sorted(r["pbe"] for r in h1); wb = sorted(r["W"] for r in h1)
    qp = [pctl(pb, q) for q in (20, 40, 60, 80)]
    qw = [pctl(wb, q) for q in (100.0 / 3, 200.0 / 3)]
    def st(r):
        i = sum(1 for c in qp if r["pbe"] > c)
        j = sum(1 for c in qw if r["W"] > c)
        return i * 3 + j
    return st, qp, qw

def rw_stat_factory(K):
    def stat(s, c):
        # cells: 2k = A value in stratum k, 2k+1 = B value in stratum k
        cov = [k for k in range(K) if c[2 * k] > 0 and c[2 * k + 1] > 0]
        nb = sum(c[2 * k + 1] for k in cov)
        if nb == 0: return float("nan")
        arw = sum(c[2 * k + 1] / nb * s[2 * k] / c[2 * k] for k in cov)
        bcv = sum(s[2 * k + 1] for k in cov) / nb
        return arw - bcv
    return stat

def within(rows, ga, gb, val, st, K=15):
    def contribs(r):
        o = []
        k = st(r)
        if ga(r): o.append((2 * k, val(r)))
        if gb(r): o.append((2 * k + 1, val(r)))
        return o
    stat = rw_stat_factory(K)
    res = {"FULL": boot(rows, contribs, 2 * K, stat),
           "H1": boot([r for r in rows if r["half"] == "H1"], contribs, 2 * K, stat),
           "H2": boot([r for r in rows if r["half"] == "H2"], contribs, 2 * K, stat)}
    # readability on group totals
    for hn in res:
        pt, lo, hi, cnt = res[hn]
        res[hn] = (pt, lo, hi, [sum(cnt[0::2]), sum(cnt[1::2])])
    return res

p("| Session | Comparison | Outcome | d_raw [95 % CI] | d_within FULL [95 % CI] (n) | H1 d_within | H2 d_within | Label (d_within) | B rows covered % |")
p("|---|---|---|---|---|---|---|---|---|")
STRATA = {}
for s in SESSIONS:
    sr = [r for r in P0 if r["session"] == s]
    st, qp, qw = strata_fn(sr)
    STRATA[s] = (st, qp, qw)
    for a_, b_ in PAIRS[:2]:
        ga, gb = tier_is(a_), tier_is(b_)
        acov = set(st(r) for r in sr if ga(r))
        bn = [r for r in sr if gb(r)]
        cov = 100.0 * sum(1 for r in bn if st(r) in acov) / max(1, len(bn))
        for oname, mname, val, scale in (("success rate, pp", "success rate, pp", lambda r: r["win"], 100.0),
                                         ("timeout share, pp", "timeout share, pp", lambda r: r["open"], 100.0),
                                         ("net EV per trade, bps", "net EV per trade, bps", lambda r: r["ev"], 1.0)):
            raw, _ = compare_metric(sr, ga, gb, mname, halves=False)
            res = within(sr, ga, gb, (lambda r, v=val, sc=scale: sc * v(r)), st)
            lab = label(res, (0, 1))
            LABELS.append(("6 %s %s-%s" % (s, a_, b_), "within-geometry " + oname, lab, res["FULL"][0]))
            p("| %s | %s - %s | %s | %s | %s (%s) | %s | %s | %s | %.1f |" % (s, a_, b_, oname, ci(*raw[:3]), ci(*res["FULL"][:3]), nt(res["FULL"], (0, 1)),
                                                                      ci(*res["H1"][:3]), ci(*res["H2"][:3]), lab, cov))
p()
p("| Session | Breakeven quintile cut points (H1) | T + S tercile cut points, bps (H1) | Occupied strata (P0) |")
p("|---|---|---|---|")
for s in SESSIONS:
    st, qp, qw = STRATA[s]
    p("| %s | %s | %s | %d of 15 |" % (s, " / ".join("%.3f" % x for x in qp), " / ".join("%.1f" % x for x in qw), len(set(st(r) for r in P0 if r["session"] == s))))
p()
p("- Tied cut points: most rows carry the ATR fallback target and the clamped stop, so they share one per-signal breakeven (NY 1.6 / 3.35, LONDON 1.6 / 3.6, ASIA 1.6 / 2.85). Tied quintiles merge into fewer strata; the count above is what the re-weighting uses.")
p()

# ---- 6.1 within target type
p("### 6.1 Tier gaps inside one target type, P0, main window")
p()
p("- The H3 column is the forward segment (no halves, no label).")
p()
p("| Session | Target type | Comparison | Metric | FULL d [95 % CI] (n) | H1 d [95 % CI] | H2 d [95 % CI] | Label | H3 d [95 % CI] (n) |")
p("|---|---|---|---|---|---|---|---|---|")
for s in SESSIONS:
    for cap in ("none", "swing"):
        sr = [r for r in P0 if r["session"] == s and r["cap"] == cap]
        s3 = [r for r in H3 if r["session"] == s and r["cap"] == cap]
        for a_, b_ in PAIRS[:2]:
            for m in ("mean target distance, ATR", "gross breakeven rate, pp", "success rate, pp", "timeout share, pp", "gross edge, pp", "net EV per trade, bps"):
                r3, need3 = compare_metric(s3, tier_is(a_), tier_is(b_), m, halves=False)
                p("| %s | %s | %s - %s | %s | %s | %s (%s) |" % (s, cap, a_, b_, m, cmp_line(sr, tier_is(a_), tier_is(b_), m, "6.1 %s %s %s-%s" % (s, cap, a_, b_)),
                                                             ci(*r3[:3], fmt=FMT[m]), nt(r3, need3)))
p()
p("| Session | Target type | Tier | n | Success % | Timeout % | Gross BE % | Gross edge pp | Net EV bps |")
p("|---|---|---|---|---|---|---|---|---|")
for s in SESSIONS:
    for cap in ("none", "swing", "hvn"):
        for t in TIERS:
            c = [r for r in P0 if r["session"] == s and r["cap"] == cap and r["tier"] == t]
            if not c: continue
            o = cell_out(c)
            p("| %s | %s | %s | %d%s | %.1f | %.1f | %.1f | %+.1f | %+.1f |" % (s, cap, t, o["n"], "" if o["n"] >= FLOOR else " (NOT READABLE)", o["succ"], o["tout"], o["gbe"], o["gedge"], o["ev"]))
p()

# ---- 7 era segments
p("## 7. Era segments (no halves): the key tier gaps inside each settings or code era")
p()
p("- E1 = v51 edge to the v66 collector deploy (2026-08-10 18:36:01); E2 = v66 to the ATR step (2026-08-20); E3 = ATR step to 2026-09-11; H3 = 2026-09-14 to 2026-09-24 08:45 (forward, v68, the 2026-09-21 15:38 code deploy inside it).")
p()
SEGS = [("E1", lambda r: r["seg"] == "P0" and r["ts"] < V66), ("E2", lambda r: r["seg"] == "P0" and V66 <= r["ts"] < ATR_STEP),
        ("E3", lambda r: r["seg"] == "P0" and r["ts"] >= ATR_STEP), ("H3", lambda r: r["seg"] == "H3")]
ERA_METRICS = ["mean target distance, bps", "payoff ratio sum T / sum S", "gross breakeven rate, pp", "success rate, pp", "gross edge, pp", "net EV per trade, bps"]
p("| Session | Comparison | Metric | " + " | ".join("%s d [95 %% CI] (n)" % nm for nm, _ in SEGS) + " |")
p("|---|---|---|" + "---|" * len(SEGS))
for s in SESSIONS:
    for a_, b_ in PAIRS[:2]:
        for m in ERA_METRICS:
            cells = []
            for nm, pr in SEGS:
                rows = [r for r in pop if r["session"] == s and pr(r)]
                res, need = compare_metric(rows, tier_is(a_), tier_is(b_), m, halves=False)
                cells.append("%s (%s)" % (ci(*res[:3], fmt=FMT[m]), nt(res, need)))
            p("| %s | %s - %s | %s | %s |" % (s, a_, b_, m, " | ".join(cells)))
p()

# ---- 8 forward H3 ledger
geom_table(H3, "## 8. Forward segment H3 (2026-09-14 to 2026-09-24): geometry")
out_table(H3, "### 8.1 Forward segment H3: outcome ledger, main window", TIER_GROUPS)

# ---- 9 POC-fix sensitivity
p("## 9. POC-fix sensitivity, P0: the key comparisons with the POC-fix slice removed")
p()
P0x = [r for r in P0 if not r["pocslice"]]
p("| Session | Slice rows: STRONG / MEDIUM / WEAK | Comparison | Metric | With slice (FULL d) | Without slice FULL d [95 % CI] | Label without slice |")
p("|---|---|---|---|---|---|---|")
for s in SESSIONS:
    sl = Counter(r["tier"] for r in P0 if r["session"] == s and r["pocslice"])
    for a_, b_ in PAIRS[:2]:
        for m in ["mean target distance, bps", "gross breakeven rate, pp", "success rate, pp", "gross edge, pp", "net EV per trade, bps"]:
            w, _ = compare_metric([r for r in P0 if r["session"] == s], tier_is(a_), tier_is(b_), m, halves=False)
            res, need = compare_metric([r for r in P0x if r["session"] == s], tier_is(a_), tier_is(b_), m)
            p("| %s | %d / %d / %d | %s - %s | %s | %s | %s | %s |" % (s, sl["STRONG"], sl["MEDIUM"], sl["WEAK"], a_, b_, m, FMT[m](w[0]), ci(*res["FULL"][:3], fmt=FMT[m]), label(res, need)))
p()

# ---- 10 carried 24 h, P0
p("## 10. Carried 24 h (secondary), P0: success rate, gross breakeven rate and net EV by tier")
p()
p("| Session | Tier | n | Success % | Timeout % | Gross BE % | Gross edge pp | Net EV bps [95 % CI] |")
p("|---|---|---|---|---|---|---|---|")
for s in SESSIONS:
    for t in TIERS:
        c = [r for r in P0 if r["session"] == s and r["tier"] == t]
        n = len(c)
        succ = 100.0 * sum(1 for r in c if r["out24"] == 1) / n
        tout = 100.0 * sum(1 for r in c if r["out24"] == 0) / n
        gbe = 100.0 * sum(r["S"] for r in c) / sum(r["W"] for r in c)
        b = boot(c, lambda r: [(0, r["ev24"])], 1, lambda s_, c_: s_[0] / c_[0] if c_[0] else float("nan"))
        p("| %s | %s | %d | %.1f | %.1f | %.1f | %+.1f | %s |" % (s, t, n, succ, tout, gbe, succ - gbe, ci(*b[:3])))
p()
p("| Session | Comparison | Metric | FULL d [95 % CI] (n) | H1 d [95 % CI] | H2 d [95 % CI] | Label |")
p("|---|---|---|---|---|---|---|")
for s in SESSIONS:
    sr = [r for r in P0 if r["session"] == s]
    for a_, b_ in PAIRS[:2]:
        for m in ("success rate, carried 24 h, pp", "gross edge, carried 24 h, pp", "net EV per trade, carried 24 h, bps"):
            p("| %s | %s - %s | %s | %s |" % (s, a_, b_, m, cmp_line(sr, tier_is(a_), tier_is(b_), m, "10 %s %s-%s" % (s, a_, b_))))
p()

# ---- 11 Kelly assumption vs book
p("## 11. What the Kelly EST mode assumed (through v68) against what the book shows, P0, main window (descriptive; v69 retired the EST tier map, see the note below)")
p()
# [F-6, v69] kelly.est_prob_floor/est_prob_scale were RETIRED in settings.json v69
# (docs/kelly-one-class-placed-payoff-spec.md KO-5 (a) - Kelly p/b now come from the
# live eval cache, not a confidence-tier map). This section is a HISTORICAL comparison
# against the EST-mode tier map as it shipped through v68; the v68 values are carried
# here as a documented literal of that version, not read from a key that no longer
# exists in the tracked file.
b_k = cfg["scoring"]["atr_target_multiplier"] / cfg["scoring"]["atr_stop_multiplier"]
EST_PROB_FLOOR_V68 = 0.45
EST_PROB_SCALE_V68 = 0.20
pk = {"STRONG": EST_PROB_FLOOR_V68 + EST_PROB_SCALE_V68, "MEDIUM": EST_PROB_FLOOR_V68 + EST_PROB_SCALE_V68 / 2.0, "WEAK": EST_PROB_FLOOR_V68}
p("- Kelly EST as it shipped through v68 (Core/ScoringEngine_Kelly.vb): p from the confidence tier, b = atr_target_multiplier / atr_stop_multiplier = %.3f for every tier. f* = (b p - (1 - p)) / b. v69 replaced this with the book's own measured p/b (docs/kelly-one-class-placed-payoff-spec.md); the table below stays as the historical baseline this build compared against." % b_k)
p()
p("| Session | Tier | Kelly p | Kelly b | Kelly f* | Measured success rate | Measured payoff sum T / sum S | f* at measured p and b |")
p("|---|---|---|---|---|---|---|---|")
for s in SESSIONS:
    for t in TIERS:
        c = [r for r in P0 if r["session"] == s and r["tier"] == t]
        o = cell_out(c); g = cell_geom(c)
        pm = o["succ"] / 100.0; bm = g["ratio"]
        p("| %s | %s | %.2f | %.3f | %+.3f | %.3f | %.3f | %+.3f |" % (s, t, pk[t], b_k, (b_k * pk[t] - (1 - pk[t])) / b_k, pm, bm, (bm * pm - (1 - pm)) / bm))
p()

# ---- label census
p("## 12. Label census (sections 2.1, 5, 6, 6.1, 9, 10; section 9 labels are not counted)")
p()
cnt = Counter(l.split(" (")[0] for _, _, l, _ in LABELS)
p("| Label | Count |")
p("|---|---|")
for k_, v_ in sorted(cnt.items(), key=lambda x: -x[1]):
    p("| %s | %d |" % (k_, v_))
p()
p("- Labelled comparisons: %d; readable: %d. At a 5 %% false-positive rate per half, the chance that a null comparison reads CONFIRMED is about 0.05 x 0.05 / 2 = 0.00125, so about %.2f false CONFIRMED labels are expected." %
  (len(LABELS), sum(1 for x in LABELS if x[2] != "NOT READABLE"), 0.00125 * sum(1 for x in LABELS if x[2] != "NOT READABLE")))
p()

os.makedirs(os.path.dirname(J(args.out)), exist_ok=True)
with open(J(args.out), "w", encoding="utf-8", newline="\n") as f:
    f.write("\n".join(out) + "\n")
print("wrote %s (%d lines)" % (J(args.out), len(out)))
